---
title: "Linkage"
draft: true
---


from https://marcobaroni.org/tools_and_resources.html

- [EGG](https://github.com/facebookresearch/EGG) a toolkit to implement language emergence games
- [CommAI-env]() is an environment to train and benchmark communication-based AIs [paper](https://arxiv.org/abs/1511.08130) [Meta](https://research.facebook.com/publications/commai-evaluating-the-first-steps-towards-a-useful-general-ai/) Dead
- [SCAN](https://github.com/brendenlake/SCAN) simplified CommAI navigation tasks to evaluate compositional learning and zero-shot generalization;
- [WaCky](https://wacky.sslmit.unibo.it/doku.php?id=start) project a very large Web-derived, POS-tagged and lemmatized corpora of English (with dependency parsing), German, Italian and French: to download them, visit the ;
- [LAMBADA dataset](https://zenodo.org/records/2630551#.XKdhTkNS_CI) for testing broad context understanding of language models;
- The [DISSECT toolkit](https://github.com/composes-toolkit/dissect) to construct and compose distributional semantic representations; [Docs](https://wiki.cimec.unitn.it/tiki-index.php?page=CLIC)
- High-performance distributional semantic vectors;
- The SICK data set for large-scale evaluation of compositional semantic models (for other tools and data sets produced by the COMPOSES project please visit the project page);
- MEN, human-elicited semantic similarity data for the evaluation of computational models;
- BLIND (BLind Italian Norming Data), semantic norms collected from congenitally blind and highly comparable sighted subjects;
- BLESS (Baroni-Lenci Evaluation of Semantic Similarity), a large data set to evaluate computational models of semantic similarity;
- DM: trained model (weighted word-link-word tuples) and utility scripts;
- Semantic norms for German and Italian: available in this archive and documented in this article;
- [zipfR](http://purl.org/stefan.evert/zipfR): a toolkit for lexical statistics in R;
- BootCaT: a toolkit for bootstrapping specialized language corpora and terms from the web;
- Morph-it!, a free Italian morphological lexicon;
- Access to the La Repubblica corpus, a large corpus of Italian newspaper text;
- Web as Corpus post-processing tools, for boilerplate stripping and near-duplicate identification;
- [Knorpora](http://sslmit.unibo.it/~baroni/welcome_to_knorpora.html): the Knoppix Linux live CD remastered with tools and resources for corpus-based computational linguistics students;
- [English token and document frequency lists](http://sslmit.unibo.it/~baroni/brown_lob_fq_lists.html) from the LOB and Brown corpora;
- [regexp_tokenizer](http://sslmit.unibo.it/~baroni/regexp_tokenizer.html): a simple tokenizer based on regular expressions.



NLP
- The [TreeTagger](https://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/) --- a part-of-speech tagger for many languages

