---
title: "lewis game further musings"
date: "2024-06-29"
draft: true
---

I was looking at the benefits of complex signaling systems. The literature suggests
that learning a developing a complex signaling system requires additional coordination
on fundamentals of grammar. 



However I think that in a big way the fundamentals of grammar are likely to be emergent from 
properties of the most basic signaling systems. 

- Agents do not have access to a formal grammar with an arbitrary number of 
  simple signals. They are constrained by the number of signals. 
- Humans have access to about 800 distinct phonemes at their disposal. 
  Notable is the fact that most languages make use of an even smaller subset of 20-80 phonemes
- Lexicons for small languages with few speakers are about 10,000-20,000 words.
  For Major languages the active vocabulary of an average adult is typically around 20,000 to 35,000 words.
- The full vocabulary can be 600,000 and over 1,000,000 if one includes specilised and technical terms used
  to communicate in a professional domain. These belong to different subcultures.
  
- If basic signals are too similar there is a risk of errors and problems with 
  being understood at some distance.
- Also the use of say clicks and whistles can make it more challenging to master the language.
- This leads to concatenation of phonemes to from a larger body of complex signals 
  we call words. Here a morphology aids in organizing the lexicon to facilitate 
  learning and understanding the language.
- Concatenation of phonemes is probably the mechanism responsible for the development of complex signaling systems
  from which context sensitive grammars quickly emerge to correct the deficiencies 
  of partial pooling and transmission errors.
  
  but they can use a prefix to negate a signal.
If there are only a few basic signals
  agents can use
messages are to be transmitted they need to be
  ordered.
- Might they arise by by spontaneous symmetry breaking.
- Natural language are never strictly separating equilibria. They have many synonyms and 
some homonyms to. There is ambiguity at every level. 

Skyrms seems to suggests that the Lewis signaling game plus
the notion of using a prefix might be a precursor to the development of ordered signals
ordered grammar.

I consider that order might develop along side categories.


Besides that extending the Lewis game to include algebraic form of:

1.  different modes of message aggregation
2.  conjunction Danger_Ground & Snake \~ { Danger_Ground,  Snake} and support for logical infrence
    -   prefix to negate danger \~ {Danger_Ground, Not Snake} has precedent in bird
        calls
    -   Bakers bake bread \~ {'subject':'Bakers','verb':'Bake','object':'Bread'}
3.  ordered sequences Not Sanke ~ \<Not,Snake\> \~
    {'subject':M1,'verb':M2,'object':M3} Bakers bake bread \~
    {'subject':'Bakers','verb':'Bake','object':'Bread'}
4.  trees via recursive aggregation
    -   Bakers bake bread \~ {'S': {'NP': {N: 'Bakers'}, {'VP': {V:
        'bake'}, {'NP': {N: 'bread'}}}}}
    -   can be represented by CFG.
      

6.  grammars


a.  regular $\displaystyle L=\{a^{n}b^{n}|n>0\}}$ is generated by the
    Type-3 grammar ${\displaystyle G=(\{S\},\{a,b\},P,S)}$ with the
    productions ${\displaystyle P}$ being the following.
    $S \rightarrow aS$,$S \rightarrow a$

b.  CFG $\displaystyle L=\{a^{n}b^{n}|n>0\}}$ is generated by the Type-2
    grammar ${\displaystyle G=(\{S\},\{a,b\},P,S)}$ with the productions
    ${\displaystyle P}$ being the following.
    $S \rightarrow aSb$,$S \rightarrow ab$

c.  CSG :G = (N

4.  agreement
5.  noisy environment
6.  what if we use embeddings rather than one hot encoded states?


## Lit reviews

Literature Cited in in the context of Lewis Reconstruction Games:

- [@rita2022emergent] Emergent Communication: Generalization and Overfitting in Lewis Games.
- [@chaabouni2019antiefficient] Anti-Efficient Encoding in Emergent Communication - discuss the inversion of Zipf's Law of Abbreviation
  (ZLA) --- where common messages tend to be longer. In [@Lazaridou2023Towards] 
  Angeliki Lazaridou suggest  that these are due to receiver's having greater 
  accuracy in decoding longer messages. 
  I would also add that if Ziff's law is an significant feature of emergent 
  communication this is easy feature to encourage either via loss (message length
  loss) or by adding a risk of sudden death for agents at every bit being transmitted. 
  This will add an intrinsic motivation to compress messages in proportion to 
  their length. So while this is an indicator that the environment isn't realistic, 
  it is far from clear that ZLA is at any level a necessary feature of 
  emergent communication. Anyhow this paper feels like looking for your keys under the
  street light, rather than where you lost them.

- [@Eugene2019Information] Entropy minimization in emergent languages. 
- [@rita2020lazimpa] - presents a solution to [@chaabouni2019antiefficient] 
  by making sender's lazy and receivers impatient. This should be interesting to 
  read, but it just mirrors the solution I mentioned above based on [@skryms2010signals].
  which suggests that senders face risk of death during signaling and receivers 
  have benefits by being able to decode partial messages. Infact a pooling states
  for danger from bellow and danger from above, followed by a second message regarding the 
  specific threat might confer greater fitness (expected rewards/progney) for risky
  communication. Particularly if the second message might come from some other agent who
  is less at risk! (THink that risk of death is a function of message length exeeding
  a certain threshold). This is in comparison with a signaling system that has
  many seperating equilibria for each type of danger. More so if we assume also that
  there are L basic signals and if there are more messages than signals then recievers 
  must guess the intended message or use a string of basic signals to communicate
  the intended message. In this setup we assign a differential cost for signals of
  different lengths. Which is to say that the cost of a signal is a function of its
  length. This is a simple way to encourage the use of shorter messages. All this
  aside this seems to be worth considering for a simple way to motivate the emergence 
  of efficient messages.
- [@rita2022role] 
- Rahma Chaabouni, Eugene Kharitonov, Diane
Bouchacourt, Emmanuel Dupoux, and Marco
Baroni. 2020. Compositionality and generalization in emergent languages. arXiv preprint
arXiv:2004.09124.

----

Videos

- [Deep Emergent Communication: How It Started and How It’s Going](https://www.youtube.com/watch?v=gW6Lt49k27c)
- [Learning to Communicate with Deep Multi-Agent Reinforcement Learning](https://www.youtube.com/watch?v=JUbTWA7gTJ4) - Jakob Foerster
- [Learning to Coorporate: Emergent Communication in Multi-Agent Navigation](https://www.youtube.com/watch?v=uB0OYudLJ7M) Ivana Kajić

- 