---
title: "Courses"
subtitle: Plan for 2026
date: 2026-01-02
categories: [education, learning, courses]
keywords: [courses, education, learning]
bibliography: reference.bib
reference-location: margin
citation-location: margin
---

Here are some courses that I am planning to take in 2026. 
I will update this list as I find more interesting courses.
I wonder which ones I will audit and which ones I will take notes for. 
I will also update this list with the courses that I have completed and my thoughts on them.

I try to focus on courses available on youtube, with slides. In some cases there is no good course available just book and papers and short workshops

## Probability

1. [ ] Measure Theoretic Probability by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching)
 [Playlist](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrO6VtBSiQLsNlo9QBm30nxC)

1. [ ] Monte Carlo Methods by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching) [Playlist (2025)](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrPd90OIZf4rwnCoNqRNUnOx)

1. [ ] Markov Processes by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching) [Playlist 2025](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrPZqHMprAbnqkGHd3Itgr2K) [Markov Spring 2023](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrP3rME2XvFvE4Q5vI3H_7_Z) [](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrMj791M1Cq9nc491Owvtk8V)

1. [ ] Mathematical Statistics by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching) [2025](https://www.youtube.com/watch?v=I0u1cecfXQ4&list=PLLyj1Zd4UWrPZH-fknPLak0tlUpUISBZR) 
[](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrOk5-wIki_oOxHJnNj0_437)

1. [ ] Basic Probability by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching) [Playlist](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrNBa_2hBgdyGFCJdMAqDrZB)

1. [ ] Statistical Estimation for Data Science and AI by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching) | [Coursera](https://www.coursera.org/learn/statistical-inference-for-estimation-in-data-science?specialization=statistical-inference-for-data-science-applications)

1. [ ] Statistical Inference and Hypothesis Testing in Data Science by [Jem N. Corcoran](https://amath.colorado.edu/faculty/corcoran/#teaching) | [Coursera](https://www.coursera.org/learn/statistical-inference-and-hypothesis-testing-in-data-science-applications?specialization=statistical-inference-for-data-science-applications)
https://www.coursera.org/specializations/statistical-inference-for-data-science-applications

---

## Optimization (3 Flavours)


1. [ ] Convex Optimization by [Stephen Boyd](https://stanford.edu/~boyd/) [Playlist](https://www.youtube.com/playlist?list=PLLyj1Zd4UWrPZqHMprAbnqkGHd3Itgr2K) | [Stanford Course](https://web.stanford.edu/class/ee364a/) 
    -  @boyd2004convex [Convex Optimization Book](https://web.stanford.edu/~boyd/cvxbook/)  https://web.stanford.edu/class/ee364a/index.html

1. [ ] Bayesian Optimization By [Geoff Pleiss](https://github.com/gpleiss)  [Stanford EE364A Convex Optimization I Stephen Boyd I 2023](https://www.youtube.com/playlist?list=PLoROMvodv4rMJqxxviPa4AmDClvcbHi6h) | [demos GH](https://github.com/gpleiss/gp_bo_demos) @garnett_bayesoptbook_2023

1. [Nonlinear Optimization](https://www.mit.edu/~gfarina/67220/) by [Gabriele Farina](https://www.mit.edu/~gfarina/about/)

---

## Probabilistic ML & Statistical Learning

1. [ ] Probabilistic ML by [Prof. Philipp Hennig](https://www.youtube.com/@PhilippHennig) [playlist](https://www.youtube.com/watch?v=qg7V43qhOUE&list=PL05umP7R6ij0hPfU7Yuz8J9WXjlb3MFjm) [slidedeck](https://github.com/philipphennig/Probabilistic_ML) [@2020_hennig_pml]

1. [ ] Statistical Machine Learning by [Ulrike von Luxburg](https://www.youtube.com/@UlrikeVonLuxburg), University of Tübingen, Summer Term 2020. [2023](https://www.youtube.com/playlist?list=PL05umP7R6ij2XCvrRzLokX6EoHWaGA2cC) [slidedeck 2020](http://www.tml.cs.uni-tuebingen.de/teaching/2020_statistical_learning) and [slidedeck 2022](http://www.tml.cs.uni-tuebingen.de/teaching/2022_statistical_learning/index.php
)

## RL & MARL

1. [ ] [Topics in Multiagent Learning](https://www.mit.edu/~gfarina/6S890/) by [Gabriele Farina](https://www.mit.edu/~gfarina/about/)

> can local learning result in global game-theoretic equilibrium?

1. Introduction to Computational Thinking [Home](https://computationalthinking.mit.edu/Fall24/) [Course repo](https://github.com/mitmath/computational-thinking/tree/Fall20_)

---

## BNP

### Books

1. [@müller2015bayesian] Bayesian Nonparametric Data Analysis 
2. [@turkman2019computational] Computational Bayesian Statistics - An Introduction [Pdf](https://web.ma.utexas.edu/users/pmueller/compbayes/iebc.pdf)

Maria Antonia AMARAL TURKMAN, Carlos Daniel PAULINO and Peter MUELLER


### Short courses:

1. [ ] Variational Bayes (2020) - Tamara Broderick (MIT) [playlist](https://www.youtube.com/playlist?list=PLxC_ffO4q_rW_8Fflob7SuMwpjlSh5f5K) [page](https://tamarabroderick.com/tutorial_2020_smiles.html) 
    - [1](https://www.youtube.com/watch?v=7t_3dNs4QK4) [slidedeck](https://tamarabroderick.com/files/broderick_tutorial_2020_smiles_vb_part_i.pdf)
    - [2](https://www.youtube.com/watch?v=p175JlCTYRw) [slidedeck](https://tamarabroderick.com/files/broderick_tutorial_2020_smiles_vb_part_ii.pdf)
    - [3](https://www.youtube.com/watch?v=pU1tb9llDPE) [slidedeck](https://tamarabroderick.com/files/broderick_tutorial_2020_smiles_vb_part_iii.pdf)
    - [4](https://www.youtube.com/watch?v=t1jT7VRD1rk) [slidedeck](https://tamarabroderick.com/files/broderick_tutorial_2020_smiles_vb_part_iii.pdf)

1. [ ] Peter Muller (UT Austin) [playlist](https://www.youtube.com/playlist?list=PLHaWeIntAtAIjrTCeQ5ZfNlG2HRvtGOu4) [outline](https://web.ma.utexas.edu/users/pmueller/McGill/outline.pdf)
    - [0](https://www.youtube.com/watch?v=HGOZhgUJ_M0&list=PLHaWeIntAtAIjrTCeQ5ZfNlG2HRvtGOu4&index=1&pp=iAQB) | [Review](https://web.ma.utexas.edu/users/pmueller/McGill/slides0.pdf) | [slidedeck](https://web.ma.utexas.edu/users/pmueller/McGill/slides1.pdf)
    - [1]() 
    - [2]() [slidedeck](https://web.ma.utexas.edu/users/pmueller/McGill/slides2.pdf) 
    - [3]() [slidedeck](https://web.ma.utexas.edu/users/pmueller/McGill/slides3.pdf) 
    - [4]() [slidedeck](https://web.ma.utexas.edu/users/pmueller/McGill/slides4.pdf) 
    

> can dropping a little data change your conclusions?


---

## Classical Problems in Probability