project:
  type: website
  output-dir: docs
  preview:
    port: 7777
  #render: 
    #- '*.qmd'
    #'!posts/2011/npl-python/index.qmd'
    #- '!posts/2012/2012-07-26-wikisym-2012_files/2012-07-26-wikisym-2012.qmd'
execute:
  freeze: auto
  cache: true
website:
  image: "images/banner.jpg"
  favicon: "favicon.png"
  title: "Oren Bochman's Blog"
  site-url: https://orenbochman.github.io/
  description: Personal website, portfolio and blog
  repo-url: https://github.com/OrenBochman/blog
  reader-mode: true
  page-navigation: true
  page-footer:
    center: 
      - "Copyright 2024, Oren Bochman" 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd
  navbar:
    logo: images/logo.png
    background: primary
    left:
       - about.qmd
       - icon: bi-book
         menu:        
         - text: All Notes
           url: notes.qmd
         - text: NLP Specilization
           url: nlp.qmd
         - text: Neural Networks for Machine Learning
           url: dnn.qmd
         - text: Model Thinking
           url: model-thinking.qmd
         - text: XAI
           url: xai.qmd
         - text: Reinforcement Learning (RL) Specialization
           url: rl.qmd
         - text: rhetoric
           url: rhetoric.qmd
         - text: TFP
           url: tfp.qmd
         - text: AB testing
           url: ab-testing.qmd
         - text: cognitive AI
           url: cognitiveai.qmd
    right:
      - icon: twitter
        href: https://twitter.com/orenbochman
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/blog
          - text: Report a Bug
            url: https://github.com/OrenBochman/blog/issues
      - icon: rss
        href: index.xml
      - icon: archive
        href: archive.qmd
  cookie-consent: false
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@orenbochman"
format:
  html:
    theme:
      light: flatly
      dark: darkly
      #light: flatly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
      #dark: [sketchy, darkness.scss]
      #dark: darkly
    highlight-style: arrow
    code-fold: true
    code-copy: true
    code-tools: 
      toggle: true
      source: false
    link-external-newwindow: true
    image-placeholder: images/dnn_cover.png
    from: "markdown+emoji"
filters:
  - shinylive
  - pseudocode
bibliography: references.bib
#csl: citestyle.csl

editor: 
  markdown: 
    wrap: none