project:
  type: website
  preview:
    port: 7777

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/orenbochman
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/blog
          - text: Report a Bug
            url: https://github.com/OrenBochman/blog/issues
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

