project:
  type: website
  output-dir: docs
  preview:
    port: 7777

execute:
  freeze: auto

website:
  title: "Oren Bochman's Blog"
  site-url: https://orenbochman.github.io/blog/
  reader-mode: true
  page-navigation: true
  page-footer: "Copyright 2024, Oren Bochman" 

  navbar:
    background: primary
    left:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/orenbochman
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/blog
          - text: Report a Bug
            url: https://github.com/OrenBochman/blog/issues
      - icon: rss
        href: index.xml
      - icon: archive
        href: archive.qmd
        
sidebar:
  contents: auto



        
  
  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@orenbochman"

        
format:
  html:
    theme: solar
    css: styles.css

editor: visual

