project:
  type: website
  output-dir: docs
  preview:
    port: 7777
  render: 
    - '*.qmd'
    #'!posts/2011/npl-python/index.qmd'
    #- '!posts/2012/2012-07-26-wikisym-2012_files/2012-07-26-wikisym-2012.qmd'
execute:
  freeze: auto

website:
  title: "Oren Bochman's Blog"
  site-url: https://orenbochman.github.io/blog/
  description: Personal website, portfolio and blog
  repo-url: https://github.com/OrenBochman/blog
  image: logo.jpg
  reader-mode: true
  page-navigation: true
  page-footer:
    center: 
      - "Copyright 2024, Oren Bochman" 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
      - text: "Trademark"
        href: trademark.qmd

  navbar:
    background: primary
    left:
      - about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/orenbochman
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/blog
          - text: Report a Bug
            url: https://github.com/OrenBochman/blog/issues
      - icon: rss
        href: index.xml
      - icon: archive
        href: archive.qmd
        
  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@orenbochman"

format:
  html:
    theme: 
      light: lightly
      #solar
      #dark: [cosmo, theme-dark.scss]
      dark: [darkly, theme-dark.scss]
    highlight-style: arrow
    code-fold: true
    code-copy: true
    code-tools: 
      toggle: true
      source: false
    link-external-newwindow: true

bibliography: references.bib
#csl: citestyle.csl

#editor: visual
editor: source
