project:
  type: website
  output-dir: docs
  preview:
    port: 7777
  render: 
    - '*.qmd'
    #'!posts/2011/npl-python/index.qmd'
    #- '!posts/2012/2012-07-26-wikisym-2012_files/2012-07-26-wikisym-2012.qmd'
execute:
  freeze: auto

website:
  title: "Oren Bochman's Blog"
  site-url: https://orenbochman.github.io/blog/
  reader-mode: true
  page-navigation: true
  page-footer: "Copyright 2024, Oren Bochman" 

  navbar:
    background: primary
    left:
      - about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/orenbochman
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/blog
          - text: Report a Bug
            url: https://github.com/OrenBochman/blog/issues
      - icon: rss
        href: index.xml
      - icon: archive
        href: archive.qmd
        
sidebar:
  contents: auto

  cookie-consent: true
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@orenbochman"

format:
  html:
    theme: solar
    css: styles.css

#editor: visual

