project:
  type: website
  output-dir: docs
  preview:
    port: 7777
  #render: 
    #- '*.qmd'
    #'!posts/2011/npl-python/index.qmd'
    #- '!posts/2012/2012-07-26-wikisym-2012_files/2012-07-26-wikisym-2012.qmd'
execute:
  freeze: auto
  cache: true
website:
  title: "Oren Bochman's Blog"
  navbar:
    logo: images/logo.png
    background: primary
    left:
      - text: 'Home'
        url: 'index.qmd'
      - icon: bi-book
      - text: 'About'
        url: "about.qmd" 
    right:
      - icon: twitter
        href: https://twitter.com/orenbochman
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/OrenBochman/blog
          - text: Report a Bug
            url: https://github.com/OrenBochman/blog/issues
      - icon: rss
        href: index.xml
      - icon: archive
        href: archive.qmd
  cookie-consent: false  
  comments: 
    hypothesis: 
      theme: clean
      openSidebar: false

  sidebar:
    contents:
      - section: "Notes"
        type: "dark"
        collapse-level:	2
        title: "notes"
        style: "docked"
        search: true
        background: light
        icon: bi-book
        contents:
          - text: Bayesian Specialization
            url: https://orenbochman.github.io/notes-bayes/
          - text: Reinforcement Learning
            url: https://orenbochman.github.io/notes-rl/            
        # url: notes.qmd
        # contents:        
        #   #- notes.qmd
        #   #- text: All Notes
        #   #   url: notes.qmd
        #   - text: NLP Specialization
        #     url: nlp.qmd
        #   - text: Neural Networks for Machine Learning
        #     url: dnn.qmd
        #   - text: Model Thinking
        #     url: model-thinking.qmd
        #   - text: XAI
        #     url: xai.qmd
        #   - text: Reinforcement Learning
        #     url: rl.qmd
        #   - text: Rhetoric
        #     url: rhetoric.qmd
        #   - text: TFP
        #     url: tfp.qmd
        #   - text: AB testing
        #     url: ab-testing.qmd
        #   - text: Cognitive AI (Udacity)
        #     url: cognitiveai.qmd  
        #   - text: Stats learning
        #     url: islr.qmd 
        #   - text: Deep learning
        #     url: dlfc.qmd           
      - text: "---"
      - section: "Paper Reviews"
        url: reviews.qmd
        contents: reviews
        icon: bi-card-heading
      - text: "---"
      - section: "Blog"  
        collapse-level:	2      
        icon: bi-substack
        contents: posts
        url: posts.qmd
      - text: "---"
    
  #url: contents.qmd
  site-url: https://orenbochman.github.io/
  description: Personal website, portfolio and blog
  repo-url: https://github.com/OrenBochman/blog
  favicon: favicon.ico
  #open-graph: true
  reader-mode: true
  page-navigation: true

  page-footer:
    center: 
      - "Copyright 2025, Oren Bochman"
      - text: "About"
        href: about.qmd
      #- text: "License"
      #  href: license.qmd
      # - text: "Trademark"
      #   href: trademark.qmd
  
  twitter-card: 
    image: thumbnail_blog.png
    card-style: summary_large_image
    creator: "@orenbochman"

format:
  html:
    theme:
      light: flatly
      dark: darkly
      #light: flatly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
      #dark: [sketchy, darkness.scss]
      #dark: darkly
    html-math-method: katex
    highlight-style: arrow
    code-fold: true
    code-copy: true
    code-tools: 
      toggle: true
      source: false
    link-external-newwindow: true
    image-placeholder: images/dnn_cover.png
    from: "markdown+emoji"
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 450px
      gutter-width: 1.5rem 
    include-in-header:
      text: |  
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css" integrity="sha384-5TcZemv2l/9On385z///+d7MSYlvIEw9FuZTIdZ14vJLqWphw7e7ZPuOiCHJcFCP" crossorigin="anonymous">
        <script>
          window.WebFontConfig = {
            custom: {
              families: ['KaTeX_AMS', 'KaTeX_Caligraphic:n4,n7', 'KaTeX_Fraktur:n4,n7',
                'KaTeX_Main:n4,n7,i4,i7', 'KaTeX_Math:i4,i7', 'KaTeX_Script',
                'KaTeX_SansSerif:n4,n7,i4', 'KaTeX_Size1', 'KaTeX_Size2', 'KaTeX_Size3',
                'KaTeX_Size4', 'KaTeX_Typewriter'],
            },
          };
        </script>
        <script  src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js" integrity="sha384-cMkvdD8LoxVzGF/RPUKAcvmm49FQ0oxwDF3BGKtDXcEc+T1b2N+teh/OJfpU0jr6" crossorigin="anonymous"></script>
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/contrib/auto-render.min.js" integrity="sha384-hCXGrW6PitJEwbkoStFjeJxv+fSOOQKOPbJxSfM6G5sWZjAyWhXiTIIAmQqnlLlh" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>

        <script  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>


bibliography: references.bib
#csl: citestyle.csl
date-format: full
#date: last-modified

editor: 
  markdown: 
    wrap: none

brand: brand/_brand.yml


crossref:
  custom:
    - kind: float
      key: algo
      reference-prefix: "Algorithm"
      caption-prefix: "Algorithm"
      latex-env: algo
      latex-list-of-description: Algorithm

filters:
  - shinylive
  - pseudocode
  - diagram

pseudocode:
  caption-prefix: "Algorithm"
  reference-prefix: "Algorithm"
  caption-number: true