---
title: "Convoluted Intuitions"
categories: [math, probability]
keywords: [convolutions, fourier transforms, fft, probability, signal processing]
date: 2026-01-03
---

Convolutions arise in many areas of mathematics, physics, and engineering, particularly in signal processing and image analysis. At its core, a convolution is a mathematical operation that combines two functions to produce a third function that expresses how the shape of one is modified by the other.

## Definition and initial intuition

Here is the mathematical definition of the convolution of two functions f and g:

$$
(f * g)(t) = \int_{-\infty}^{\infty} f(\tau) g(t - \tau) d\tau
$$

It's a shame that when we meet this formula as students we usually don't have a good ~~intuitive~~ understanding of what this is suppose to mean.

This integral essentially slides one function over another, multiplying and integrating at each point to produce a new function. The result of the convolution operation can be interpreted in various ways depending on the context, such as blurring an image, filtering a signal, or combining probability distributions.

## In probability and statistics

Convolutions can be used to uniquely define a distribution in terms of its characteristic function [characteristic function]{.column-margin} or its moment generating function [moment generating function]{.column-margin}. While use of moment generating functions is more common in introductory probability courses, characteristic functions have some advantages, particularly in theoretical work and are more both more fundamental and guaranteed to exist for all probability distributions, something unfortunately not true of moment generating functions as some distributions do not have the requisite moments.

One area It is particularly useful is probability theory and statistics, where convolutions are used to determine the distribution of the sum of two independent random variables. If X and Y are independent random variables with probability density functions (PDFs) $f_X(x)$ and $f_Y(y)$, respectively, then the PDF of the sum $Z = X + Y$ is given by the convolution of $f_X$ and $f_Y$ : 


## Next lets explore convolutions further using some videos

:::
{{< video https://www.youtube.com/watch?v=KuXjwB4LzSA width="400" height="300" title="But what is a convolution?" >}}
:::

This is a very powerful

0:00 - Where do convolutions show up?
2:07 - Add two random variables
6:28 - A simple example
7:25 - Moving averages
8:32 - Image processing
13:42 - Measuring runtime
14:40 - Polynomial multiplication
18:10 - Speeding up with FFTs
21:22 - Concluding thoughts


{{< video https://www.youtube.com/watch?v=KuXjwB4LzSA width="400" height="300" title="Convolutions | Why X+Y in probability is a beautiful mess?" >}}


{{< video https://www.youtube.com/watch?v=8rrHTtUzyZA width="400" height="300" title="Convolutions | Convolutions in Image Processing" >}}


- [Introduction to Computational Thinking](https://computationalthinking.mit.edu/Fall24/)
- [Course repo](https://github.com/mitmath/computational-thinking/tree/Fall20_)


{{< video https://www.youtube.com/watch?v=KuXjwB4LzSA width="400" height="300" title="Convolutions | Why X+Y in probability is a beautiful mess?" >}}


{{< video https://www.youtube.com/watch?v=KuXjwB4LzSA width="400" height="300" title="Convolutions | Why X+Y in probability is a beautiful mess?" >}}