
## The Oracle of Saliency

In many cases the arduous task $O(n^2)$ of coordination that makes signaling hard might be avoided. If both agents share some mechanism for enumerating the pre-linguistic objects they encounter, they can systematically enumerate them before the game start. The enumeration is a lexicon and can be used as a signaling system.

You mention that oracles are cryptic - 
 They can now pick use the binary number as canonically they can avoid some or all of the cost of coordination. 

::: {.callout-note}

### Story: The Oracle of Saliency

The sender in an ex-ante step consults an oracle, perhaps the `I Ching` asking what to do for each prelinguistic objects. Each consultation returns a cryptic message not unlike a cryptographic hash. The sender then sorts the objects in increasing order of the cryptic messages, assigning each subsequent binary number to each. 

The receiver also uses the same process with his copy of the oracle. 

Since both the sender and receiver now have access to the same lexicon, they can use it as a signaling system.
:::


1. Even is the oracle does not provide unique enumerations it will reduce the task from $O(N^2)$ to $O(N)$. as once the oracle is consulted the sender and receiver can proceed by trial and error to further coordinate on the ambiguous signals. e.g. by assigning a sub-index to each prelinguistic object that share a signal. This will now look more like a prefix coding scheme.
2. In the lewis game errors cost nothing, but in RL we often encode a sense of urgency by adding a penalty to time wasting moves. If there a penalty e.g. -1 for wasting time on miscoodination, we might call the game the `Lewis game with urgency`. Agents that get to play an infinite nuymber of time would see an infinite rewards past at most $O(n^2)$ penalties and want to play. In this case though even if consulting the oracle has a cost C, so long a the expected cost of trial and error is greater than  k i.e. if there are k^2 uncoordinated states agents would have incentive to consult the oracle. 
3. In the previous points we ignored the reality in which states are not uniformly distributed and that agents may not be able to pay the oracle upfront. If the agents know the most likely states they this knowledge to setup a self-financing scheme to raise funds for consultations of the oracle as well as reduce thier cost of coordination. However it's worth pointing out that our next scenario considers how knowing the distribution of states is just another type of oracle.

Two cases come to mind.

1. They have booth been observing the state space long enough to infer the distribution of states to a high degree of confidence. [**coordinate via the state distribution**]{.column-margin}
2. They can listen to a third party who knows the distribution and learn to signal from them. [**coordinate by imitation**]{.column-margin}
3. They can access a state classifier and send it random noise thus deriving an empirical distribution of states in the classifier (not nature) and use it to learn the signaling system. [**coordinate via a classifier**]{.column-margin}

Once a distribution of states in known it can be used to create huffman codes using 0 and 1. These signals are then ranked.

There is a distribution of the states of the word known to all players.

-   In the easiest case each state has a different probability of occurring. -It is easiest because all players can infer a `canonical signal system` from such a distribution of states.
    - They order states and corresponding actions in decreasing expected value. The canonical system is the one mapping between the states and the actions.
    - Thus the salience distribution breaks the symmetry of all viable signaling systems and leaves just one option.[^1]
-   In each subsequently harder case there are two or more states with equal probability of occurring. These probabilistic symmetry of these states cannot be broken as before and require the use of coordination. The coordinators can break the symmetry by trial and error when that state arises. Once all the symmetries have been coordinated the players can infer the rest via the canonical signal system from the distribution of states.
-   In the worst case all states have equal probability of occurring. This is the hardest case because after each state signal pair the problem is still maximally symmetric. The players need to solve this by using trial and error.

[^1]: This is notion of a most salient mapping acts as an optimal policy for agents who need to quickly avoid the long run costs of a non salient signaling system

::: {.callout-tip}

### MARL Formulation

In terms of the MARL formulation:

- A PMDP has states $S$ and actions $A$. 
    - States are observed by agents of type S whose actions are signals 
    - Actions are performed by agents of type R.
    - Rewards are assigned symmetrically to both All senders and receivers when the receiver action matches the sender observed state.

- States can be uniformly distributed or be drawn from a distribution. 
- We like to call such a distribution the saliency distribution after Schelling notion of a focal point AKA (Schelling point) in his book The Strategy of Conflict. In a lewis signaling game there are n! signaling systems if there are n states, signals and actions. If the states are uniformly distributed then all signaling systems are equivalent. But if the states probabilities are monotonicaly distributed then there is a unique optimal signaling system which is precisely the Schelling point.

- Since saliency 
:::

::: {.callout-caution}
It is also worth noting that many algorithms for MARL use shared parameters, the same critic and so on. And if the agents can access this system the oracle of saliency provides a shortcut to a cannonical emergent language for all agents as well as a general purpose coordination mechanism they might use to coordinate on other tasks. Thus such oracles should be treated with care if we also wish to study the the emergence of a universal language
:::
