
## Bringing Up Baby

This is another trivial case where learning is O(N) where N is the number of states

::: {.callout-note}

### Story: Bringing Up Baby 

Here the sender is tha parent and the receiver the child. 
Each time the child learn a new action the teacher also adds new signal is added to the signaling system. 
Since the other signals are known the child can learn the new signal in a single step. 

:::

Although I discovered this scenario independently, it appears to have been described by Skryms in a talk [@cn]
According to a talk by Skyrms, the child can learn a new signal in a single step.


### Hoppe's Urn 

::: {.callout-note}

### Incremental Learning

In RL this is called incremental learning. 
We can also assign such signals to sequences of actions which we call capabilities. 
The child can learn a new capability in a single step. This is the most efficient way to learn a signaling system incrementally.

:::


Skyrms discusses two methods that agents can use to learn a signaling system incrementally. 
First is the Chinese restaurant process and the second is the Hoppe urn. 
He suggest that they are equivalent. 

I too came up with the Hoppe urn model - as I had already investigated how to codify the most common probability distributions as urn models.


Another way to make learning easier is to always have just one action in context when we need to learn. 
This allows the receiver to learn the signal system in a single step. 
It might work with a student learning to signal and act in tandem. [**incremental learning with one new action**]{.column-margin}

In this case urn used in learning have an Hoppe urn with a black stone indicating that a new state action pair is being learned. If the receiver learns the new signal action pair, the agents keep track of it otherwise the new signal and action are discarded.

Note that if the there is only one new state and action a suitable algorithm can learn it immediately. IF there is an exploration - this may cause an error.

We retain this mechanism and might use it for expanding a signaling systems incrementally in the presence of new data.

Note: if there are saliency distributions is being used a new signal would be the last signal in the saliency distribution or in the last group. Over time signals that are not in use might be discarded if thier saliency is bellow the minimum saliency threshold.
