## The steady navigator

Indeed they can do better. If the sender picks a signal and sticks with it the receiver can eliminate an action each turn. This is the optimal strategy for this, the most common setting of the Lewis signaling game.

::: {.callout-note}

### Story: The Steady navigator

Senders and Receivers lack all prior knowledge. For each new state, the sender picks a signal at random but if the state is the same as the last state the sender sticks to the same signal. The receiver must explore an action at random but if the signal is the same as the a previous seen signal the receiver will explore an an untested action for the signal until they get a reward. 
:::

Lets estimate the expected rewards under this strategy for a state T and N states, signals and actions.

- Sender has 1 signal and
- Since the sender sticks with the same signal the receiver can eliminate an action each turn.
- Receiver has N choices initially with 1 correct choice so we has a expected chance of 1/N of getting a reward.
- Next he can eliminate his first choice and has N-1 choices with 1 correct choice so we has a expected chance of 1/(N-1) of getting a reward.
- And after k tries he has N-k+1 choices with 1 correct choice so we has a expected chance of 1/(N-k+1) of getting a reward.
- In the worst case he will have to try all N actions but
- The Expected number of steps 
$$
\begin{aligned}
\mathbb{E}[steps] &= \sum_{k=1}^{N} \frac{1}{P_{\text{success k}}} \times P_\text{failure up to k} \newline
&= \sum_{k=1}^{N} \frac{1}{{N-(k-1)}} \underbrace{\times \prod_{i=1}^{k-1} \frac{N-i}{N-i+1}}_{\text{telescopic product}} \newline
&= \sum_{k=1}^{N} \frac{1}{\cancel{{N-(k-1)}}} \times \frac{\cancel{{N-(k-1)}}}{N} \newline
\end{aligned}
$$




::: {.callout-tip}

### MARL Formulation

This is basicaly an optimistic initialization strategy. The sender does not explore. The reciever intilizes all signal action pairs optimisticaly with value of 0.5.  This way he will keep exploring untill he gets a reward of 1.0 At this point exploration ends.

:::


So we can expect that the number of steps needed to learn to signal the state T is N.
They should pick a signal for a state and stick with with it. 
