
## Knight & Knaves -- Bayesian Adversarial Signaling

I had this idea a while back regarding how to address two different problems.

1. How agents in non-cooperative games might evolve signaling systems that are robust to adversarial agents. I.e. could they learn based on the positive domain by inferring that certain action are more cooperative or at least not prone to deception? Could they learn in the Negative domain. I.E. could they learn to infer the opponents type by using bayesian updating for cases where action are predominantly adversarial?
2. Can agents use contrafactual reasoning to accelerate learning to signaling. This is a system where agents infer private information of another agents (e.g. their type, thier lexicon and or grammar rules) based on observation the other agents behavior, which is more costly to use for deception than say cheap talk. This uses the idea of measuring contrafactual influence.

:::{.callout-note}
### Deception by Knight & Knaves 

There are multiple senders and each state is known to all of the multiple senders

Each sender has a voracity parameter $\nu \in [0,1]$, this is the probability that they send a faithful signal. 

For a complex game this can be interpreted as the probability that the sender will make a error when sending a signal

More generally we might have three parameters $\nu_s, \mu_r, \nu_c$ which are respectively the voracity for the sender, the channel and the receiver.

:::

This is an idea is similar to the approach used by [@Nowak2006Evolutionary] on errors in signaling. However in this case we are more interested in the case where there are adversarial agents who are trying to deceive the receivers and the problem of these receivers to learn a signaling system that is robust to adversarial agents

At the extreme the agents have types (like knights and knaves) and the receivers must learn to classify the agents by type and then learn to both signaling and reason. 

One idea based on knight and knaves might be to allow reveivers to request request a response to a query i.e. if the state is %X% what is the signal that you would send? the signal $Y$?

A novel idea here is to learn a Bayesian hierarchical cognitive model that captures 

1. the voracity of the senders $V_i \sym Beta(\alpha, \beta)$
2. $H_i$ hypotesis on different states of the world i.e. the voracity of the senders
3. how each and all statements made by the senders are consistent with each hypothesis $H_i$
