
## Babbling Bayesian Babies

This is a simple model of babbling in language development.

<!-- Note: rename since babbling equilibria is a term used in the literature for completely pooling equilibria. -->

Babies in the babbling stage of language development are learning to signal. 
They are sending all possible phonemes and the parents and thier parents either respond or talk to each other. 
The babies are collecting the feedback and reinforcing both positively and negatively until they only use the phonemes that are in the language of thier parents.

Typical They start with over 300 phonemes and end up with 40-50. 

In this scenario the sender operates at random. Both the sender and the receiver must observe the rewards and reinforce state signal action triplets.

Different cognitive dynamics to model via bayesian learning

1. Just learning the phonemes by passive listening to the parents etc.
    - Positive v.s. negative examples i.e. are the babies asked to repeat and get rewards or do they just observe states passively.
2. Active teaching (Parents also present a prelinguistic object for the phoneme) 
    - should boost rate of learning more phonemes particularly 
    - Positive v.s. negative examples
3. Adding learning a syllable structure to the language then the babies should learn not just the phonemes but the syllables. This adds another layer to the hierarchical model.
4. Adding picking the syllables from a number of options
    - Positive v.s. negative examples
5. Adding phonotactic constraints and that the babies should learn the constraints. 
    - Positive v.s. negative examples

