---
date: "2025-03-24"
bibliography: ./bibliography.bib
---



## Imitation Learning 

what else is this called

::: {.callout-note}
### Story: Imitation <!-- Population Dynamics -->

In nature one species, say primates can gain fitness benefits if it can learn and imitate the signals of other species say birds.

If they can understand but cannot reproduce the signals (e.g. bird calls) they may resort to using a different set of signals (e.g. hand signals) to communicate with each other. 

:::


### Dynamics 

We do not require that the original signals come from one species, there may be a number of species that can provide signals that are useful to the primate and these might change seasonally or due to migration to new habitats.

Once a rudimentary signaling system is established, it may be natural to extend it to more sophisticated system that can be used to communicate additional states. 

The ability to signal may well lead the tribe to become more cohesive and more efficient at hunting and gathering and avoiding predators. Some examples are:

1. It now becomes more useful to assign idle or less productive members to roles of sentry or lookout while the others broadcast their messages.

1. Also this creates a new benefit that takes the form of social welfare. This means that derelict members of the watch or those that raise false alarms will be subject to punishment by thier peers. This is a form of **costly signaling** that is used to maintain the integrity of the tribe.

1. Less capable forgers will be able to more quickly learn the locations of food sources by sharing  signals of the more experienced foragers whenever they return to the safety of the tribe. This may also allow the tribe to better exploit the food sources that are available to them in a far larger area.
Thus the carrying capacity of the tribe is increased by sharing of information, and the tribe might also become more localized and less nomadic. They may choose to migrate to new areas only when the food sources are depleted in a larger neighborhood.

1. Stag hunts - hunting large game that requires coordination of multiple hunters, the ability to signal and coordinate the hunt using this new signaling system may allow the tribe to hunt larger game that they would not have been able to hunt before. This will also let them specialize in hunting.

These and numerous other social benefits may accrue to the tribe that is able to learn by imitation augmented by invention. 



### In natural language

Imitation is prevalent in natural languages as well. Loan words as well as idioms are often borrowed from other languages and may have similar sound structures as well as semantic meanings. Loan words frequently require some adaptation to the phonetic structure of the borrowing language. Some languages like english preserve the original phonetic structure of the loan word, while others like Japanese may adapt the phonetic structure of the loan word to the phonetic structure of the borrowing language. 

In many cases if the words are used a lot and it is a poor fit for the phonetic structure of the borrowing language. it will be replaced by another word that is a better fit and the original word will be forgotten. 

This mechanism is likely understood as part of `Hamming Moat Formation` that keeps languages from merging


### Sources 

A number of sources for this phenomenon are available in [@]


