{
  "hash": "8ee2246746234d41ddcaeb0b04d284d9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 'Under the Hood: Training a Digit Classifier'\njupyter:\n  jupytext:\n    split_at_heading: true\n  kernelspec:\n    display_name: Python 3\n    language: python\n    name: python3\n---\n\n::: {#f45b1346 .cell execution_count=1}\n``` {.python .cell-code}\n#hide\n!pip install -Uqq fastbook\nimport fastbook\nfastbook.setup_book()\n```\n:::\n\n\n::: {#772effcf .cell execution_count=2}\n``` {.python .cell-code}\n#hide\nfrom fastai.vision.all import *\nfrom fastbook import *\n\nmatplotlib.rc('image', cmap='Greys')\n```\n:::\n\n\n[[chapter_mnist_basics]]\n\n\n\nHaving seen what it looks like to actually train a variety of models in Chapter 2, let’s now look under the hood and see exactly what is going on. We’ll start by using computer vision to introduce fundamental tools and concepts for deep learning.\n\nTo be exact, we'll discuss the roles of arrays and tensors and of broadcasting, a powerful technique for using them expressively. We'll explain stochastic gradient descent (SGD), the mechanism for learning by updating weights automatically. We'll discuss the choice of a loss function for our basic classification task, and the role of mini-batches. We'll also describe the math that a basic neural network is actually doing. Finally, we'll put all these pieces together.\n\nIn future chapters we’ll do deep dives into other applications as well, and see how these concepts and tools generalize. But this chapter is about laying foundation stones. To be frank, that also makes this one of the hardest chapters, because of how these concepts all depend on each other. Like an arch, all the stones need to be in place for the structure to stay up. Also like an arch, once that happens, it's a powerful structure that can support other things. But it requires some patience to assemble.\n\nLet's begin. The first step is to consider how images are represented in a computer.\n\n## Pixels: The Foundations of Computer Vision\n\nIn order to understand what happens in a computer vision model, we first have to understand how computers handle images. We'll use one of the most famous datasets in computer vision, [MNIST](https://en.wikipedia.org/wiki/MNIST_database), for our experiments. MNIST contains images of handwritten digits, collected by the National Institute of Standards and Technology and collated into a machine learning dataset by Yann Lecun and his colleagues. Lecun used MNIST in 1998 in [Lenet-5](http://yann.lecun.com/exdb/lenet/), the first computer system to demonstrate practically useful recognition of handwritten digit sequences. This was one of the most important breakthroughs in the history of AI.\n\n## Sidebar: Tenacity and Deep Learning\n\nThe story of deep learning is one of tenacity and grit by a handful of dedicated researchers. After early hopes (and hype!) neural networks went out of favor in the 1990's and 2000's, and just a handful of researchers kept trying to make them work well. Three of them, Yann Lecun, Yoshua Bengio, and Geoffrey Hinton, were awarded the highest honor in computer science, the Turing Award (generally considered the \"Nobel Prize of computer science\"), in 2018 after triumphing despite the deep skepticism and disinterest of the wider machine learning and statistics community.\n\nGeoff Hinton has told of how even academic papers showing dramatically better results than anything previously published would be rejected by top journals and conferences, just because they used a neural network. Yann Lecun's work on convolutional neural networks, which we will study in the next section, showed that these models could read handwritten text—something that had never been achieved before. However, his breakthrough was ignored by most researchers, even as it was used commercially to read 10% of the checks in the US!\n\nIn addition to these three Turing Award winners, there are many other researchers who have battled to get us to where we are today. For instance, Jurgen Schmidhuber (who many believe should have shared in the Turing Award) pioneered many important ideas, including working with his student Sepp Hochreiter on the long short-term memory (LSTM) architecture (widely used for speech recognition and other text modeling tasks, and used in the IMDb example in <<chapter_intro>>). Perhaps most important of all, Paul Werbos in 1974 invented back-propagation for neural networks, the technique shown in this chapter and used universally for training neural networks ([Werbos 1994](https://books.google.com/books/about/The_Roots_of_Backpropagation.html?id=WdR3OOM2gBwC)). His development was almost entirely ignored for decades, but today it is considered the most important foundation of modern AI.\n\nThere is a lesson here for all of us! On your deep learning journey you will face many obstacles, both technical, and (even more difficult) posed by people around you who don't believe you'll be successful. There's one *guaranteed* way to fail, and that's to stop trying. We've seen that the only consistent trait amongst every fast.ai student that's gone on to be a world-class practitioner is that they are all very tenacious.\n\n## End sidebar\n\nFor this initial tutorial we are just going to try to create a model that can classify any image as a 3 or a 7. So let's download a sample of MNIST that contains images of just these digits:\n\n::: {#ae85e13b .cell execution_count=3}\n``` {.python .cell-code}\npath = untar_data(URLs.MNIST_SAMPLE)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n\n<style>\n    /* Turns off some styling */\n    progress {\n        /* gets rid of default border in Firefox and Opera. */\n        border: none;\n        /* Needs to be in here for Safari polyfill so background images work as expected. */\n        background-size: auto;\n    }\n    progress:not([value]), progress:not([value])::-webkit-progress-bar {\n        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);\n    }\n    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {\n        background: #F44336;\n    }\n</style>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n\n    <div>\n      <progress value='3219456' class='' max='3214948' style='width:300px; height:20px; vertical-align: middle;'></progress>\n      100.14% [3219456/3214948 00:12&lt;00:00]\n    </div>\n    \n```\n:::\n:::\n\n\n::: {#bfd2a3b1 .cell execution_count=4}\n``` {.python .cell-code}\n#hide\nPath.BASE_PATH = path\n```\n:::\n\n\nWe can see what's in this directory by using `ls`, a method added by fastai. This method returns an object of a special fastai class called `L`, which has all the same functionality of Python's built-in `list`, plus a lot more. One of its handy features is that, when printed, it displays the count of items, before listing the items themselves (if there are more than 10 items, it just shows the first few):\n\n::: {#289039b5 .cell execution_count=5}\n``` {.python .cell-code}\npath.ls()\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n(#3) [Path('train'),Path('labels.csv'),Path('valid')]\n```\n:::\n:::\n\n\nThe MNIST dataset follows a common layout for machine learning datasets: separate folders for the training set and the validation set (and/or test set). Let's see what's inside the training set:\n\n::: {#aff793a2 .cell execution_count=6}\n``` {.python .cell-code}\n(path/'train').ls()\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n(#2) [Path('train/3'),Path('train/7')]\n```\n:::\n:::\n\n\nThere's a folder of 3s, and a folder of 7s. In machine learning parlance, we say that \"3\" and \"7\" are the *labels* (or targets) in this dataset. Let's take a look in one of these folders (using `sorted` to ensure we all get the same order of files):\n\n::: {#f89bf0a5 .cell execution_count=7}\n``` {.python .cell-code}\nthrees = (path/'train'/'3').ls().sorted()\nsevens = (path/'train'/'7').ls().sorted()\nthrees\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n(#6131) [Path('train/3/10.png'),Path('train/3/10000.png'),Path('train/3/10011.png'),Path('train/3/10031.png'),Path('train/3/10034.png'),Path('train/3/10042.png'),Path('train/3/10052.png'),Path('train/3/1007.png'),Path('train/3/10074.png'),Path('train/3/10091.png'),Path('train/3/10093.png'),Path('train/3/10097.png'),Path('train/3/10099.png'),Path('train/3/10116.png'),Path('train/3/10125.png'),Path('train/3/10137.png'),Path('train/3/10141.png'),Path('train/3/10144.png'),Path('train/3/10155.png'),Path('train/3/10161.png')...]\n```\n:::\n:::\n\n\nAs we might expect, it's full of image files. Let’s take a look at one now. Here’s an image of a handwritten number 3, taken from the famous MNIST dataset of handwritten numbers:\n\n::: {#6680a7dd .cell execution_count=8}\n``` {.python .cell-code}\nim3_path = threes[1]\nim3 = Image.open(im3_path)\nim3\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n![](04_mnist_basics_files/figure-html/cell-9-output-1.png){}\n:::\n:::\n\n\nHere we are using the `Image` class from the *Python Imaging Library* (PIL), which is the most widely used Python package for opening, manipulating, and viewing images. Jupyter knows about PIL images, so it displays the image for us automatically.\n\nIn a computer, everything is represented as a number. To view the numbers that make up this image, we have to convert it to a *NumPy array* or a *PyTorch tensor*. For instance, here's what a section of the image looks like, converted to a NumPy array:\n\n::: {#09f7449f .cell execution_count=9}\n``` {.python .cell-code}\narray(im3)[4:10,4:10]\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\narray([[  0,   0,   0,   0,   0,   0],\n       [  0,   0,   0,   0,   0,  29],\n       [  0,   0,   0,  48, 166, 224],\n       [  0,  93, 244, 249, 253, 187],\n       [  0, 107, 253, 253, 230,  48],\n       [  0,   3,  20,  20,  15,   0]], dtype=uint8)\n```\n:::\n:::\n\n\nThe `4:10` indicates we requested the rows from index 4 (included) to 10 (not included) and the same for the columns. NumPy indexes from top to bottom and left to right, so this section is located in the top-left corner of the image. Here's the same thing as a PyTorch tensor:\n\n::: {#b6fa9fde .cell execution_count=10}\n``` {.python .cell-code}\ntensor(im3)[4:10,4:10]\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\ntensor([[  0,   0,   0,   0,   0,   0],\n        [  0,   0,   0,   0,   0,  29],\n        [  0,   0,   0,  48, 166, 224],\n        [  0,  93, 244, 249, 253, 187],\n        [  0, 107, 253, 253, 230,  48],\n        [  0,   3,  20,  20,  15,   0]], dtype=torch.uint8)\n```\n:::\n:::\n\n\nWe can slice the array to pick just the part with the top of the digit in it, and then use a Pandas DataFrame to color-code the values using a gradient, which shows us clearly how the image is created from the pixel values:\n\n::: {#e139172b .cell execution_count=11}\n``` {.python .cell-code}\n#hide_output\nim3_t = tensor(im3)\ndf = pd.DataFrame(im3_t[4:15,4:22])\ndf.style.set_properties(**{'font-size':'6pt'}).background_gradient('Greys')\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<style type=\"text/css\">\n#T_cb960_row0_col0, #T_cb960_row0_col1, #T_cb960_row0_col2, #T_cb960_row0_col3, #T_cb960_row0_col4, #T_cb960_row0_col5, #T_cb960_row0_col6, #T_cb960_row0_col7, #T_cb960_row0_col8, #T_cb960_row0_col9, #T_cb960_row0_col10, #T_cb960_row0_col11, #T_cb960_row0_col12, #T_cb960_row0_col13, #T_cb960_row0_col14, #T_cb960_row0_col15, #T_cb960_row0_col16, #T_cb960_row0_col17, #T_cb960_row1_col0, #T_cb960_row1_col1, #T_cb960_row1_col2, #T_cb960_row1_col3, #T_cb960_row1_col4, #T_cb960_row1_col15, #T_cb960_row1_col16, #T_cb960_row1_col17, #T_cb960_row2_col0, #T_cb960_row2_col1, #T_cb960_row2_col2, #T_cb960_row2_col15, #T_cb960_row2_col16, #T_cb960_row2_col17, #T_cb960_row3_col0, #T_cb960_row3_col15, #T_cb960_row3_col16, #T_cb960_row3_col17, #T_cb960_row4_col0, #T_cb960_row4_col6, #T_cb960_row4_col7, #T_cb960_row4_col8, #T_cb960_row4_col9, #T_cb960_row4_col10, #T_cb960_row4_col15, #T_cb960_row4_col16, #T_cb960_row4_col17, #T_cb960_row5_col0, #T_cb960_row5_col5, #T_cb960_row5_col6, #T_cb960_row5_col7, #T_cb960_row5_col8, #T_cb960_row5_col9, #T_cb960_row5_col15, #T_cb960_row5_col16, #T_cb960_row5_col17, #T_cb960_row6_col0, #T_cb960_row6_col1, #T_cb960_row6_col2, #T_cb960_row6_col3, #T_cb960_row6_col4, #T_cb960_row6_col5, #T_cb960_row6_col6, #T_cb960_row6_col7, #T_cb960_row6_col8, #T_cb960_row6_col9, #T_cb960_row6_col14, #T_cb960_row6_col15, #T_cb960_row6_col16, #T_cb960_row6_col17, #T_cb960_row7_col0, #T_cb960_row7_col1, #T_cb960_row7_col2, #T_cb960_row7_col3, #T_cb960_row7_col4, #T_cb960_row7_col5, #T_cb960_row7_col6, #T_cb960_row7_col13, #T_cb960_row7_col14, #T_cb960_row7_col15, #T_cb960_row7_col16, #T_cb960_row7_col17, #T_cb960_row8_col0, #T_cb960_row8_col1, #T_cb960_row8_col2, #T_cb960_row8_col3, #T_cb960_row8_col4, #T_cb960_row8_col13, #T_cb960_row8_col14, #T_cb960_row8_col15, #T_cb960_row8_col16, #T_cb960_row8_col17, #T_cb960_row9_col0, #T_cb960_row9_col1, #T_cb960_row9_col2, #T_cb960_row9_col3, #T_cb960_row9_col4, #T_cb960_row9_col16, #T_cb960_row9_col17, #T_cb960_row10_col0, #T_cb960_row10_col1, #T_cb960_row10_col2, #T_cb960_row10_col3, #T_cb960_row10_col4, #T_cb960_row10_col5, #T_cb960_row10_col6, #T_cb960_row10_col17 {\n  font-size: 6pt;\n  background-color: #ffffff;\n  color: #000000;\n}\n#T_cb960_row1_col5 {\n  font-size: 6pt;\n  background-color: #efefef;\n  color: #000000;\n}\n#T_cb960_row1_col6, #T_cb960_row1_col13 {\n  font-size: 6pt;\n  background-color: #7c7c7c;\n  color: #f1f1f1;\n}\n#T_cb960_row1_col7 {\n  font-size: 6pt;\n  background-color: #4a4a4a;\n  color: #f1f1f1;\n}\n#T_cb960_row1_col8, #T_cb960_row1_col9, #T_cb960_row1_col10, #T_cb960_row2_col5, #T_cb960_row2_col6, #T_cb960_row2_col7, #T_cb960_row2_col11, #T_cb960_row2_col12, #T_cb960_row2_col13, #T_cb960_row3_col4, #T_cb960_row3_col12, #T_cb960_row3_col13, #T_cb960_row4_col1, #T_cb960_row4_col2, #T_cb960_row4_col3, #T_cb960_row4_col12, #T_cb960_row4_col13, #T_cb960_row5_col12, #T_cb960_row6_col11, #T_cb960_row9_col11, #T_cb960_row10_col11, #T_cb960_row10_col12, #T_cb960_row10_col13, #T_cb960_row10_col14, #T_cb960_row10_col15, #T_cb960_row10_col16 {\n  font-size: 6pt;\n  background-color: #000000;\n  color: #f1f1f1;\n}\n#T_cb960_row1_col11 {\n  font-size: 6pt;\n  background-color: #606060;\n  color: #f1f1f1;\n}\n#T_cb960_row1_col12 {\n  font-size: 6pt;\n  background-color: #4d4d4d;\n  color: #f1f1f1;\n}\n#T_cb960_row1_col14 {\n  font-size: 6pt;\n  background-color: #bbbbbb;\n  color: #000000;\n}\n#T_cb960_row2_col3 {\n  font-size: 6pt;\n  background-color: #e4e4e4;\n  color: #000000;\n}\n#T_cb960_row2_col4, #T_cb960_row8_col6 {\n  font-size: 6pt;\n  background-color: #6b6b6b;\n  color: #f1f1f1;\n}\n#T_cb960_row2_col8, #T_cb960_row2_col14, #T_cb960_row3_col14 {\n  font-size: 6pt;\n  background-color: #171717;\n  color: #f1f1f1;\n}\n#T_cb960_row2_col9, #T_cb960_row3_col11 {\n  font-size: 6pt;\n  background-color: #4b4b4b;\n  color: #f1f1f1;\n}\n#T_cb960_row2_col10, #T_cb960_row7_col10, #T_cb960_row8_col8, #T_cb960_row8_col10, #T_cb960_row9_col8, #T_cb960_row9_col10 {\n  font-size: 6pt;\n  background-color: #010101;\n  color: #f1f1f1;\n}\n#T_cb960_row3_col1 {\n  font-size: 6pt;\n  background-color: #272727;\n  color: #f1f1f1;\n}\n#T_cb960_row3_col2 {\n  font-size: 6pt;\n  background-color: #0a0a0a;\n  color: #f1f1f1;\n}\n#T_cb960_row3_col3 {\n  font-size: 6pt;\n  background-color: #050505;\n  color: #f1f1f1;\n}\n#T_cb960_row3_col5 {\n  font-size: 6pt;\n  background-color: #333333;\n  color: #f1f1f1;\n}\n#T_cb960_row3_col6 {\n  font-size: 6pt;\n  background-color: #e6e6e6;\n  color: #000000;\n}\n#T_cb960_row3_col7, #T_cb960_row3_col10 {\n  font-size: 6pt;\n  background-color: #fafafa;\n  color: #000000;\n}\n#T_cb960_row3_col8 {\n  font-size: 6pt;\n  background-color: #fbfbfb;\n  color: #000000;\n}\n#T_cb960_row3_col9 {\n  font-size: 6pt;\n  background-color: #fdfdfd;\n  color: #000000;\n}\n#T_cb960_row4_col4 {\n  font-size: 6pt;\n  background-color: #1b1b1b;\n  color: #f1f1f1;\n}\n#T_cb960_row4_col5 {\n  font-size: 6pt;\n  background-color: #e0e0e0;\n  color: #000000;\n}\n#T_cb960_row4_col11 {\n  font-size: 6pt;\n  background-color: #4e4e4e;\n  color: #f1f1f1;\n}\n#T_cb960_row4_col14 {\n  font-size: 6pt;\n  background-color: #767676;\n  color: #f1f1f1;\n}\n#T_cb960_row5_col1 {\n  font-size: 6pt;\n  background-color: #fcfcfc;\n  color: #000000;\n}\n#T_cb960_row5_col2, #T_cb960_row5_col3 {\n  font-size: 6pt;\n  background-color: #f6f6f6;\n  color: #000000;\n}\n#T_cb960_row5_col4, #T_cb960_row7_col7 {\n  font-size: 6pt;\n  background-color: #f8f8f8;\n  color: #000000;\n}\n#T_cb960_row5_col10, #T_cb960_row10_col7 {\n  font-size: 6pt;\n  background-color: #e8e8e8;\n  color: #000000;\n}\n#T_cb960_row5_col11 {\n  font-size: 6pt;\n  background-color: #222222;\n  color: #f1f1f1;\n}\n#T_cb960_row5_col13, #T_cb960_row6_col12 {\n  font-size: 6pt;\n  background-color: #090909;\n  color: #f1f1f1;\n}\n#T_cb960_row5_col14 {\n  font-size: 6pt;\n  background-color: #d0d0d0;\n  color: #000000;\n}\n#T_cb960_row6_col10, #T_cb960_row7_col11, #T_cb960_row9_col6 {\n  font-size: 6pt;\n  background-color: #060606;\n  color: #f1f1f1;\n}\n#T_cb960_row6_col13 {\n  font-size: 6pt;\n  background-color: #979797;\n  color: #f1f1f1;\n}\n#T_cb960_row7_col8 {\n  font-size: 6pt;\n  background-color: #b6b6b6;\n  color: #000000;\n}\n#T_cb960_row7_col9 {\n  font-size: 6pt;\n  background-color: #252525;\n  color: #f1f1f1;\n}\n#T_cb960_row7_col12 {\n  font-size: 6pt;\n  background-color: #999999;\n  color: #f1f1f1;\n}\n#T_cb960_row8_col5 {\n  font-size: 6pt;\n  background-color: #f9f9f9;\n  color: #000000;\n}\n#T_cb960_row8_col7 {\n  font-size: 6pt;\n  background-color: #101010;\n  color: #f1f1f1;\n}\n#T_cb960_row8_col9, #T_cb960_row9_col9 {\n  font-size: 6pt;\n  background-color: #020202;\n  color: #f1f1f1;\n}\n#T_cb960_row8_col11 {\n  font-size: 6pt;\n  background-color: #545454;\n  color: #f1f1f1;\n}\n#T_cb960_row8_col12 {\n  font-size: 6pt;\n  background-color: #f1f1f1;\n  color: #000000;\n}\n#T_cb960_row9_col5 {\n  font-size: 6pt;\n  background-color: #f7f7f7;\n  color: #000000;\n}\n#T_cb960_row9_col7 {\n  font-size: 6pt;\n  background-color: #030303;\n  color: #f1f1f1;\n}\n#T_cb960_row9_col12 {\n  font-size: 6pt;\n  background-color: #181818;\n  color: #f1f1f1;\n}\n#T_cb960_row9_col13 {\n  font-size: 6pt;\n  background-color: #303030;\n  color: #f1f1f1;\n}\n#T_cb960_row9_col14 {\n  font-size: 6pt;\n  background-color: #a9a9a9;\n  color: #f1f1f1;\n}\n#T_cb960_row9_col15 {\n  font-size: 6pt;\n  background-color: #fefefe;\n  color: #000000;\n}\n#T_cb960_row10_col8, #T_cb960_row10_col9 {\n  font-size: 6pt;\n  background-color: #bababa;\n  color: #000000;\n}\n#T_cb960_row10_col10 {\n  font-size: 6pt;\n  background-color: #393939;\n  color: #f1f1f1;\n}\n</style>\n<table id=\"T_cb960\">\n  <thead>\n    <tr>\n      <th class=\"blank level0\" >&nbsp;</th>\n      <th id=\"T_cb960_level0_col0\" class=\"col_heading level0 col0\" >0</th>\n      <th id=\"T_cb960_level0_col1\" class=\"col_heading level0 col1\" >1</th>\n      <th id=\"T_cb960_level0_col2\" class=\"col_heading level0 col2\" >2</th>\n      <th id=\"T_cb960_level0_col3\" class=\"col_heading level0 col3\" >3</th>\n      <th id=\"T_cb960_level0_col4\" class=\"col_heading level0 col4\" >4</th>\n      <th id=\"T_cb960_level0_col5\" class=\"col_heading level0 col5\" >5</th>\n      <th id=\"T_cb960_level0_col6\" class=\"col_heading level0 col6\" >6</th>\n      <th id=\"T_cb960_level0_col7\" class=\"col_heading level0 col7\" >7</th>\n      <th id=\"T_cb960_level0_col8\" class=\"col_heading level0 col8\" >8</th>\n      <th id=\"T_cb960_level0_col9\" class=\"col_heading level0 col9\" >9</th>\n      <th id=\"T_cb960_level0_col10\" class=\"col_heading level0 col10\" >10</th>\n      <th id=\"T_cb960_level0_col11\" class=\"col_heading level0 col11\" >11</th>\n      <th id=\"T_cb960_level0_col12\" class=\"col_heading level0 col12\" >12</th>\n      <th id=\"T_cb960_level0_col13\" class=\"col_heading level0 col13\" >13</th>\n      <th id=\"T_cb960_level0_col14\" class=\"col_heading level0 col14\" >14</th>\n      <th id=\"T_cb960_level0_col15\" class=\"col_heading level0 col15\" >15</th>\n      <th id=\"T_cb960_level0_col16\" class=\"col_heading level0 col16\" >16</th>\n      <th id=\"T_cb960_level0_col17\" class=\"col_heading level0 col17\" >17</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id=\"T_cb960_level0_row0\" class=\"row_heading level0 row0\" >0</th>\n      <td id=\"T_cb960_row0_col0\" class=\"data row0 col0\" >0</td>\n      <td id=\"T_cb960_row0_col1\" class=\"data row0 col1\" >0</td>\n      <td id=\"T_cb960_row0_col2\" class=\"data row0 col2\" >0</td>\n      <td id=\"T_cb960_row0_col3\" class=\"data row0 col3\" >0</td>\n      <td id=\"T_cb960_row0_col4\" class=\"data row0 col4\" >0</td>\n      <td id=\"T_cb960_row0_col5\" class=\"data row0 col5\" >0</td>\n      <td id=\"T_cb960_row0_col6\" class=\"data row0 col6\" >0</td>\n      <td id=\"T_cb960_row0_col7\" class=\"data row0 col7\" >0</td>\n      <td id=\"T_cb960_row0_col8\" class=\"data row0 col8\" >0</td>\n      <td id=\"T_cb960_row0_col9\" class=\"data row0 col9\" >0</td>\n      <td id=\"T_cb960_row0_col10\" class=\"data row0 col10\" >0</td>\n      <td id=\"T_cb960_row0_col11\" class=\"data row0 col11\" >0</td>\n      <td id=\"T_cb960_row0_col12\" class=\"data row0 col12\" >0</td>\n      <td id=\"T_cb960_row0_col13\" class=\"data row0 col13\" >0</td>\n      <td id=\"T_cb960_row0_col14\" class=\"data row0 col14\" >0</td>\n      <td id=\"T_cb960_row0_col15\" class=\"data row0 col15\" >0</td>\n      <td id=\"T_cb960_row0_col16\" class=\"data row0 col16\" >0</td>\n      <td id=\"T_cb960_row0_col17\" class=\"data row0 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row1\" class=\"row_heading level0 row1\" >1</th>\n      <td id=\"T_cb960_row1_col0\" class=\"data row1 col0\" >0</td>\n      <td id=\"T_cb960_row1_col1\" class=\"data row1 col1\" >0</td>\n      <td id=\"T_cb960_row1_col2\" class=\"data row1 col2\" >0</td>\n      <td id=\"T_cb960_row1_col3\" class=\"data row1 col3\" >0</td>\n      <td id=\"T_cb960_row1_col4\" class=\"data row1 col4\" >0</td>\n      <td id=\"T_cb960_row1_col5\" class=\"data row1 col5\" >29</td>\n      <td id=\"T_cb960_row1_col6\" class=\"data row1 col6\" >150</td>\n      <td id=\"T_cb960_row1_col7\" class=\"data row1 col7\" >195</td>\n      <td id=\"T_cb960_row1_col8\" class=\"data row1 col8\" >254</td>\n      <td id=\"T_cb960_row1_col9\" class=\"data row1 col9\" >255</td>\n      <td id=\"T_cb960_row1_col10\" class=\"data row1 col10\" >254</td>\n      <td id=\"T_cb960_row1_col11\" class=\"data row1 col11\" >176</td>\n      <td id=\"T_cb960_row1_col12\" class=\"data row1 col12\" >193</td>\n      <td id=\"T_cb960_row1_col13\" class=\"data row1 col13\" >150</td>\n      <td id=\"T_cb960_row1_col14\" class=\"data row1 col14\" >96</td>\n      <td id=\"T_cb960_row1_col15\" class=\"data row1 col15\" >0</td>\n      <td id=\"T_cb960_row1_col16\" class=\"data row1 col16\" >0</td>\n      <td id=\"T_cb960_row1_col17\" class=\"data row1 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row2\" class=\"row_heading level0 row2\" >2</th>\n      <td id=\"T_cb960_row2_col0\" class=\"data row2 col0\" >0</td>\n      <td id=\"T_cb960_row2_col1\" class=\"data row2 col1\" >0</td>\n      <td id=\"T_cb960_row2_col2\" class=\"data row2 col2\" >0</td>\n      <td id=\"T_cb960_row2_col3\" class=\"data row2 col3\" >48</td>\n      <td id=\"T_cb960_row2_col4\" class=\"data row2 col4\" >166</td>\n      <td id=\"T_cb960_row2_col5\" class=\"data row2 col5\" >224</td>\n      <td id=\"T_cb960_row2_col6\" class=\"data row2 col6\" >253</td>\n      <td id=\"T_cb960_row2_col7\" class=\"data row2 col7\" >253</td>\n      <td id=\"T_cb960_row2_col8\" class=\"data row2 col8\" >234</td>\n      <td id=\"T_cb960_row2_col9\" class=\"data row2 col9\" >196</td>\n      <td id=\"T_cb960_row2_col10\" class=\"data row2 col10\" >253</td>\n      <td id=\"T_cb960_row2_col11\" class=\"data row2 col11\" >253</td>\n      <td id=\"T_cb960_row2_col12\" class=\"data row2 col12\" >253</td>\n      <td id=\"T_cb960_row2_col13\" class=\"data row2 col13\" >253</td>\n      <td id=\"T_cb960_row2_col14\" class=\"data row2 col14\" >233</td>\n      <td id=\"T_cb960_row2_col15\" class=\"data row2 col15\" >0</td>\n      <td id=\"T_cb960_row2_col16\" class=\"data row2 col16\" >0</td>\n      <td id=\"T_cb960_row2_col17\" class=\"data row2 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row3\" class=\"row_heading level0 row3\" >3</th>\n      <td id=\"T_cb960_row3_col0\" class=\"data row3 col0\" >0</td>\n      <td id=\"T_cb960_row3_col1\" class=\"data row3 col1\" >93</td>\n      <td id=\"T_cb960_row3_col2\" class=\"data row3 col2\" >244</td>\n      <td id=\"T_cb960_row3_col3\" class=\"data row3 col3\" >249</td>\n      <td id=\"T_cb960_row3_col4\" class=\"data row3 col4\" >253</td>\n      <td id=\"T_cb960_row3_col5\" class=\"data row3 col5\" >187</td>\n      <td id=\"T_cb960_row3_col6\" class=\"data row3 col6\" >46</td>\n      <td id=\"T_cb960_row3_col7\" class=\"data row3 col7\" >10</td>\n      <td id=\"T_cb960_row3_col8\" class=\"data row3 col8\" >8</td>\n      <td id=\"T_cb960_row3_col9\" class=\"data row3 col9\" >4</td>\n      <td id=\"T_cb960_row3_col10\" class=\"data row3 col10\" >10</td>\n      <td id=\"T_cb960_row3_col11\" class=\"data row3 col11\" >194</td>\n      <td id=\"T_cb960_row3_col12\" class=\"data row3 col12\" >253</td>\n      <td id=\"T_cb960_row3_col13\" class=\"data row3 col13\" >253</td>\n      <td id=\"T_cb960_row3_col14\" class=\"data row3 col14\" >233</td>\n      <td id=\"T_cb960_row3_col15\" class=\"data row3 col15\" >0</td>\n      <td id=\"T_cb960_row3_col16\" class=\"data row3 col16\" >0</td>\n      <td id=\"T_cb960_row3_col17\" class=\"data row3 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row4\" class=\"row_heading level0 row4\" >4</th>\n      <td id=\"T_cb960_row4_col0\" class=\"data row4 col0\" >0</td>\n      <td id=\"T_cb960_row4_col1\" class=\"data row4 col1\" >107</td>\n      <td id=\"T_cb960_row4_col2\" class=\"data row4 col2\" >253</td>\n      <td id=\"T_cb960_row4_col3\" class=\"data row4 col3\" >253</td>\n      <td id=\"T_cb960_row4_col4\" class=\"data row4 col4\" >230</td>\n      <td id=\"T_cb960_row4_col5\" class=\"data row4 col5\" >48</td>\n      <td id=\"T_cb960_row4_col6\" class=\"data row4 col6\" >0</td>\n      <td id=\"T_cb960_row4_col7\" class=\"data row4 col7\" >0</td>\n      <td id=\"T_cb960_row4_col8\" class=\"data row4 col8\" >0</td>\n      <td id=\"T_cb960_row4_col9\" class=\"data row4 col9\" >0</td>\n      <td id=\"T_cb960_row4_col10\" class=\"data row4 col10\" >0</td>\n      <td id=\"T_cb960_row4_col11\" class=\"data row4 col11\" >192</td>\n      <td id=\"T_cb960_row4_col12\" class=\"data row4 col12\" >253</td>\n      <td id=\"T_cb960_row4_col13\" class=\"data row4 col13\" >253</td>\n      <td id=\"T_cb960_row4_col14\" class=\"data row4 col14\" >156</td>\n      <td id=\"T_cb960_row4_col15\" class=\"data row4 col15\" >0</td>\n      <td id=\"T_cb960_row4_col16\" class=\"data row4 col16\" >0</td>\n      <td id=\"T_cb960_row4_col17\" class=\"data row4 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row5\" class=\"row_heading level0 row5\" >5</th>\n      <td id=\"T_cb960_row5_col0\" class=\"data row5 col0\" >0</td>\n      <td id=\"T_cb960_row5_col1\" class=\"data row5 col1\" >3</td>\n      <td id=\"T_cb960_row5_col2\" class=\"data row5 col2\" >20</td>\n      <td id=\"T_cb960_row5_col3\" class=\"data row5 col3\" >20</td>\n      <td id=\"T_cb960_row5_col4\" class=\"data row5 col4\" >15</td>\n      <td id=\"T_cb960_row5_col5\" class=\"data row5 col5\" >0</td>\n      <td id=\"T_cb960_row5_col6\" class=\"data row5 col6\" >0</td>\n      <td id=\"T_cb960_row5_col7\" class=\"data row5 col7\" >0</td>\n      <td id=\"T_cb960_row5_col8\" class=\"data row5 col8\" >0</td>\n      <td id=\"T_cb960_row5_col9\" class=\"data row5 col9\" >0</td>\n      <td id=\"T_cb960_row5_col10\" class=\"data row5 col10\" >43</td>\n      <td id=\"T_cb960_row5_col11\" class=\"data row5 col11\" >224</td>\n      <td id=\"T_cb960_row5_col12\" class=\"data row5 col12\" >253</td>\n      <td id=\"T_cb960_row5_col13\" class=\"data row5 col13\" >245</td>\n      <td id=\"T_cb960_row5_col14\" class=\"data row5 col14\" >74</td>\n      <td id=\"T_cb960_row5_col15\" class=\"data row5 col15\" >0</td>\n      <td id=\"T_cb960_row5_col16\" class=\"data row5 col16\" >0</td>\n      <td id=\"T_cb960_row5_col17\" class=\"data row5 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row6\" class=\"row_heading level0 row6\" >6</th>\n      <td id=\"T_cb960_row6_col0\" class=\"data row6 col0\" >0</td>\n      <td id=\"T_cb960_row6_col1\" class=\"data row6 col1\" >0</td>\n      <td id=\"T_cb960_row6_col2\" class=\"data row6 col2\" >0</td>\n      <td id=\"T_cb960_row6_col3\" class=\"data row6 col3\" >0</td>\n      <td id=\"T_cb960_row6_col4\" class=\"data row6 col4\" >0</td>\n      <td id=\"T_cb960_row6_col5\" class=\"data row6 col5\" >0</td>\n      <td id=\"T_cb960_row6_col6\" class=\"data row6 col6\" >0</td>\n      <td id=\"T_cb960_row6_col7\" class=\"data row6 col7\" >0</td>\n      <td id=\"T_cb960_row6_col8\" class=\"data row6 col8\" >0</td>\n      <td id=\"T_cb960_row6_col9\" class=\"data row6 col9\" >0</td>\n      <td id=\"T_cb960_row6_col10\" class=\"data row6 col10\" >249</td>\n      <td id=\"T_cb960_row6_col11\" class=\"data row6 col11\" >253</td>\n      <td id=\"T_cb960_row6_col12\" class=\"data row6 col12\" >245</td>\n      <td id=\"T_cb960_row6_col13\" class=\"data row6 col13\" >126</td>\n      <td id=\"T_cb960_row6_col14\" class=\"data row6 col14\" >0</td>\n      <td id=\"T_cb960_row6_col15\" class=\"data row6 col15\" >0</td>\n      <td id=\"T_cb960_row6_col16\" class=\"data row6 col16\" >0</td>\n      <td id=\"T_cb960_row6_col17\" class=\"data row6 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row7\" class=\"row_heading level0 row7\" >7</th>\n      <td id=\"T_cb960_row7_col0\" class=\"data row7 col0\" >0</td>\n      <td id=\"T_cb960_row7_col1\" class=\"data row7 col1\" >0</td>\n      <td id=\"T_cb960_row7_col2\" class=\"data row7 col2\" >0</td>\n      <td id=\"T_cb960_row7_col3\" class=\"data row7 col3\" >0</td>\n      <td id=\"T_cb960_row7_col4\" class=\"data row7 col4\" >0</td>\n      <td id=\"T_cb960_row7_col5\" class=\"data row7 col5\" >0</td>\n      <td id=\"T_cb960_row7_col6\" class=\"data row7 col6\" >0</td>\n      <td id=\"T_cb960_row7_col7\" class=\"data row7 col7\" >14</td>\n      <td id=\"T_cb960_row7_col8\" class=\"data row7 col8\" >101</td>\n      <td id=\"T_cb960_row7_col9\" class=\"data row7 col9\" >223</td>\n      <td id=\"T_cb960_row7_col10\" class=\"data row7 col10\" >253</td>\n      <td id=\"T_cb960_row7_col11\" class=\"data row7 col11\" >248</td>\n      <td id=\"T_cb960_row7_col12\" class=\"data row7 col12\" >124</td>\n      <td id=\"T_cb960_row7_col13\" class=\"data row7 col13\" >0</td>\n      <td id=\"T_cb960_row7_col14\" class=\"data row7 col14\" >0</td>\n      <td id=\"T_cb960_row7_col15\" class=\"data row7 col15\" >0</td>\n      <td id=\"T_cb960_row7_col16\" class=\"data row7 col16\" >0</td>\n      <td id=\"T_cb960_row7_col17\" class=\"data row7 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row8\" class=\"row_heading level0 row8\" >8</th>\n      <td id=\"T_cb960_row8_col0\" class=\"data row8 col0\" >0</td>\n      <td id=\"T_cb960_row8_col1\" class=\"data row8 col1\" >0</td>\n      <td id=\"T_cb960_row8_col2\" class=\"data row8 col2\" >0</td>\n      <td id=\"T_cb960_row8_col3\" class=\"data row8 col3\" >0</td>\n      <td id=\"T_cb960_row8_col4\" class=\"data row8 col4\" >0</td>\n      <td id=\"T_cb960_row8_col5\" class=\"data row8 col5\" >11</td>\n      <td id=\"T_cb960_row8_col6\" class=\"data row8 col6\" >166</td>\n      <td id=\"T_cb960_row8_col7\" class=\"data row8 col7\" >239</td>\n      <td id=\"T_cb960_row8_col8\" class=\"data row8 col8\" >253</td>\n      <td id=\"T_cb960_row8_col9\" class=\"data row8 col9\" >253</td>\n      <td id=\"T_cb960_row8_col10\" class=\"data row8 col10\" >253</td>\n      <td id=\"T_cb960_row8_col11\" class=\"data row8 col11\" >187</td>\n      <td id=\"T_cb960_row8_col12\" class=\"data row8 col12\" >30</td>\n      <td id=\"T_cb960_row8_col13\" class=\"data row8 col13\" >0</td>\n      <td id=\"T_cb960_row8_col14\" class=\"data row8 col14\" >0</td>\n      <td id=\"T_cb960_row8_col15\" class=\"data row8 col15\" >0</td>\n      <td id=\"T_cb960_row8_col16\" class=\"data row8 col16\" >0</td>\n      <td id=\"T_cb960_row8_col17\" class=\"data row8 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row9\" class=\"row_heading level0 row9\" >9</th>\n      <td id=\"T_cb960_row9_col0\" class=\"data row9 col0\" >0</td>\n      <td id=\"T_cb960_row9_col1\" class=\"data row9 col1\" >0</td>\n      <td id=\"T_cb960_row9_col2\" class=\"data row9 col2\" >0</td>\n      <td id=\"T_cb960_row9_col3\" class=\"data row9 col3\" >0</td>\n      <td id=\"T_cb960_row9_col4\" class=\"data row9 col4\" >0</td>\n      <td id=\"T_cb960_row9_col5\" class=\"data row9 col5\" >16</td>\n      <td id=\"T_cb960_row9_col6\" class=\"data row9 col6\" >248</td>\n      <td id=\"T_cb960_row9_col7\" class=\"data row9 col7\" >250</td>\n      <td id=\"T_cb960_row9_col8\" class=\"data row9 col8\" >253</td>\n      <td id=\"T_cb960_row9_col9\" class=\"data row9 col9\" >253</td>\n      <td id=\"T_cb960_row9_col10\" class=\"data row9 col10\" >253</td>\n      <td id=\"T_cb960_row9_col11\" class=\"data row9 col11\" >253</td>\n      <td id=\"T_cb960_row9_col12\" class=\"data row9 col12\" >232</td>\n      <td id=\"T_cb960_row9_col13\" class=\"data row9 col13\" >213</td>\n      <td id=\"T_cb960_row9_col14\" class=\"data row9 col14\" >111</td>\n      <td id=\"T_cb960_row9_col15\" class=\"data row9 col15\" >2</td>\n      <td id=\"T_cb960_row9_col16\" class=\"data row9 col16\" >0</td>\n      <td id=\"T_cb960_row9_col17\" class=\"data row9 col17\" >0</td>\n    </tr>\n    <tr>\n      <th id=\"T_cb960_level0_row10\" class=\"row_heading level0 row10\" >10</th>\n      <td id=\"T_cb960_row10_col0\" class=\"data row10 col0\" >0</td>\n      <td id=\"T_cb960_row10_col1\" class=\"data row10 col1\" >0</td>\n      <td id=\"T_cb960_row10_col2\" class=\"data row10 col2\" >0</td>\n      <td id=\"T_cb960_row10_col3\" class=\"data row10 col3\" >0</td>\n      <td id=\"T_cb960_row10_col4\" class=\"data row10 col4\" >0</td>\n      <td id=\"T_cb960_row10_col5\" class=\"data row10 col5\" >0</td>\n      <td id=\"T_cb960_row10_col6\" class=\"data row10 col6\" >0</td>\n      <td id=\"T_cb960_row10_col7\" class=\"data row10 col7\" >43</td>\n      <td id=\"T_cb960_row10_col8\" class=\"data row10 col8\" >98</td>\n      <td id=\"T_cb960_row10_col9\" class=\"data row10 col9\" >98</td>\n      <td id=\"T_cb960_row10_col10\" class=\"data row10 col10\" >208</td>\n      <td id=\"T_cb960_row10_col11\" class=\"data row10 col11\" >253</td>\n      <td id=\"T_cb960_row10_col12\" class=\"data row10 col12\" >253</td>\n      <td id=\"T_cb960_row10_col13\" class=\"data row10 col13\" >253</td>\n      <td id=\"T_cb960_row10_col14\" class=\"data row10 col14\" >253</td>\n      <td id=\"T_cb960_row10_col15\" class=\"data row10 col15\" >187</td>\n      <td id=\"T_cb960_row10_col16\" class=\"data row10 col16\" >22</td>\n      <td id=\"T_cb960_row10_col17\" class=\"data row10 col17\" >0</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\n<img width=\"453\" id=\"output_pd_pixels\" src=\"images/att_00058.png\">\n\nYou can see that the background white pixels are stored as the number 0, black is the number 255, and shades of gray are between the two. The entire image contains 28 pixels across and 28 pixels down, for a total of 784 pixels. (This is much smaller than an image that you would get from a phone camera, which has millions of pixels, but is a convenient size for our initial learning and experiments. We will build up to bigger, full-color images soon.)\n\nSo, now you've seen what an image looks like to a computer, let's recall our goal: create a model that can recognize 3s and 7s. How might you go about getting a computer to do that?\n\n> Warning: Stop and Think!: Before you read on, take a moment to think about how a computer might be able to recognize these two different digits. What kinds of features might it be able to look at? How might it be able to identify these features? How could it combine them together? Learning works best when you try to solve problems yourself, rather than just reading somebody else's answers; so step away from this book for a few minutes, grab a piece of paper and pen, and jot some ideas down…\n\n## First Try: Pixel Similarity\n\nSo, here is a first idea: how about we find the average pixel value for every pixel of the 3s, then do the same for the 7s. This will give us two group averages, defining what we might call the \"ideal\" 3 and 7. Then, to classify an image as one digit or the other, we see which of these two ideal digits the image is most similar to. This certainly seems like it should be better than nothing, so it will make a good baseline.\n\n> jargon: Baseline: A simple model which you are confident should perform reasonably well. It should be very simple to implement, and very easy to test, so that you can then test each of your improved ideas, and make sure they are always better than your baseline. Without starting with a sensible baseline, it is very difficult to know whether your super-fancy models are actually any good. One good approach to creating a baseline is doing what we have done here: think of a simple, easy-to-implement model. Another good approach is to search around to find other people that have solved similar problems to yours, and download and run their code on your dataset. Ideally, try both of these!\n\nStep one for our simple model is to get the average of pixel values for each of our two groups. In the process of doing this, we will learn a lot of neat Python numeric programming tricks!\n\nLet's create a tensor containing all of our 3s stacked together. We already know how to create a tensor containing a single image. To create a tensor containing all the images in a directory, we will first use a Python list comprehension to create a plain list of the single image tensors.\n\nWe will use Jupyter to do some little checks of our work along the way—in this case, making sure that the number of returned items seems reasonable:\n\n::: {#51f21408 .cell execution_count=12}\n``` {.python .cell-code}\nseven_tensors = [tensor(Image.open(o)) for o in sevens]\nthree_tensors = [tensor(Image.open(o)) for o in threes]\nlen(three_tensors),len(seven_tensors)\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\n(6131, 6265)\n```\n:::\n:::\n\n\n> note: List Comprehensions: List and dictionary comprehensions are a wonderful feature of Python. Many Python programmers use them every day, including the authors of this book—they are part of \"idiomatic Python.\" But programmers coming from other languages may have never seen them before. There are a lot of great tutorials just a web search away, so we won't spend a long time discussing them now. Here is a quick explanation and example to get you started. A list comprehension looks like this: `new_list = [f(o) for o in a_list if o>0]`. This will return every element of `a_list` that is greater than 0, after passing it to the function `f`. There are three parts here: the collection you are iterating over (`a_list`), an optional filter (`if o>0`), and something to do to each element (`f(o)`). It's not only shorter to write but way faster than the alternative ways of creating the same list with a loop.\n\nWe'll also check that one of the images looks okay. Since we now have tensors (which Jupyter by default will print as values), rather than PIL images (which Jupyter by default will display as images), we need to use fastai's `show_image` function to display it:\n\n::: {#cb300186 .cell execution_count=13}\n``` {.python .cell-code}\nshow_image(three_tensors[1]);\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-14-output-1.png){width=93 height=93}\n:::\n:::\n\n\nFor every pixel position, we want to compute the average over all the images of the intensity of that pixel. To do this we first combine all the images in this list into a single three-dimensional tensor. The most common way to describe such a tensor is to call it a *rank-3 tensor*. We often need to stack up individual tensors in a collection into a single tensor. Unsurprisingly, PyTorch comes with a function called `stack` that we can use for this purpose.\n\nSome operations in PyTorch, such as taking a mean, require us to *cast* our integer types to float types. Since we'll be needing this later, we'll also cast our stacked tensor to `float` now. Casting in PyTorch is as simple as typing the name of the type you wish to cast to, and treating it as a method.\n\nGenerally when images are floats, the pixel values are expected to be between 0 and 1, so we will also divide by 255 here:\n\n::: {#852b1a21 .cell execution_count=14}\n``` {.python .cell-code}\nstacked_sevens = torch.stack(seven_tensors).float()/255\nstacked_threes = torch.stack(three_tensors).float()/255\nstacked_threes.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\ntorch.Size([6131, 28, 28])\n```\n:::\n:::\n\n\nPerhaps the most important attribute of a tensor is its *shape*. This tells you the length of each axis. In this case, we can see that we have 6,131 images, each of size 28×28 pixels. There is nothing specifically about this tensor that says that the first axis is the number of images, the second is the height, and the third is the width—the semantics of a tensor are entirely up to us, and how we construct it. As far as PyTorch is concerned, it is just a bunch of numbers in memory.\n\nThe *length* of a tensor's shape is its rank:\n\n::: {#1b2eb7b2 .cell execution_count=15}\n``` {.python .cell-code}\nlen(stacked_threes.shape)\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n3\n```\n:::\n:::\n\n\nIt is really important for you to commit to memory and practice these bits of tensor jargon: _rank_ is the number of axes or dimensions in a tensor; _shape_ is the size of each axis of a tensor.\n\n> A: Watch out because the term \"dimension\" is sometimes used in two ways. Consider that we live in \"three-dimensonal space\" where a physical position can be described by a 3-vector `v`. But according to PyTorch, the attribute `v.ndim` (which sure looks like the \"number of dimensions\" of `v`) equals one, not three! Why? Because `v` is a vector, which is a tensor of rank one, meaning that it has only one _axis_ (even if that axis has a length of three). In other words, sometimes dimension is used for the size of an axis (\"space is three-dimensional\"); other times, it is used for the rank, or the number of axes (\"a matrix has two dimensions\"). When confused, I find it helpful to translate all statements into terms of rank, axis, and length, which are unambiguous terms.\n\nWe can also get a tensor's rank directly with `ndim`:\n\n::: {#ac4437f7 .cell execution_count=16}\n``` {.python .cell-code}\nstacked_threes.ndim\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n3\n```\n:::\n:::\n\n\nFinally, we can compute what the ideal 3 looks like. We calculate the mean of all the image tensors by taking the mean along dimension 0 of our stacked, rank-3 tensor. This is the dimension that indexes over all the images.\n\nIn other words, for every pixel position, this will compute the average of that pixel over all images. The result will be one value for every pixel position, or a single image. Here it is:\n\n::: {#00b3990a .cell execution_count=17}\n``` {.python .cell-code}\nmean3 = stacked_threes.mean(0)\nshow_image(mean3);\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-18-output-1.png){width=93 height=93}\n:::\n:::\n\n\nAccording to this dataset, this is the ideal number 3! (You may not like it, but this is what peak number 3 performance looks like.) You can see how it's very dark where all the images agree it should be dark, but it becomes wispy and blurry where the images disagree. \n\nLet's do the same thing for the 7s, but put all the steps together at once to save some time:\n\n::: {#de57324f .cell execution_count=18}\n``` {.python .cell-code}\nmean7 = stacked_sevens.mean(0)\nshow_image(mean7);\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-19-output-1.png){width=93 height=93}\n:::\n:::\n\n\nLet's now pick an arbitrary 3 and measure its *distance* from our \"ideal digits.\"\n\n> stop: Stop and Think!: How would you calculate how similar a particular image is to each of our ideal digits? Remember to step away from this book and jot down some ideas before you move on! Research shows that recall and understanding improves dramatically when you are engaged with the learning process by solving problems, experimenting, and trying new ideas yourself\n\nHere's a sample 3:\n\n::: {#bf018de4 .cell execution_count=19}\n``` {.python .cell-code}\na_3 = stacked_threes[1]\nshow_image(a_3);\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-20-output-1.png){width=93 height=93}\n:::\n:::\n\n\nHow can we determine its distance from our ideal 3? We can't just add up the differences between the pixels of this image and the ideal digit. Some differences will be positive while others will be negative, and these differences will cancel out, resulting in a situation where an image that is too dark in some places and too light in others might be shown as having zero total differences from the ideal. That would be misleading!\n\nTo avoid this, there are two main ways data scientists measure distance in this context:\n\n- Take the mean of the *absolute value* of differences (absolute value is the function that replaces negative values with positive values). This is called the *mean absolute difference* or *L1 norm*\n- Take the mean of the *square* of differences (which makes everything positive) and then take the *square root* (which undoes the squaring). This is called the *root mean squared error* (RMSE) or *L2 norm*.\n\n> important: It's Okay to Have Forgotten Your Math: In this book we generally assume that you have completed high school math, and remember at least some of it... But everybody forgets some things! It all depends on what you happen to have had reason to practice in the meantime. Perhaps you have forgotten what a _square root_ is, or exactly how they work. No problem! Any time you come across a maths concept that is not explained fully in this book, don't just keep moving on; instead, stop and look it up. Make sure you understand the basic idea, how it works, and why we might be using it. One of the best places to refresh your understanding is Khan Academy. For instance, Khan Academy has a great [introduction to square roots](https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:rational-exponents-radicals/x2f8bb11595b61c86:radicals/v/understanding-square-roots).\n\nLet's try both of these now:\n\n::: {#06b4842c .cell execution_count=20}\n``` {.python .cell-code}\ndist_3_abs = (a_3 - mean3).abs().mean()\ndist_3_sqr = ((a_3 - mean3)**2).mean().sqrt()\ndist_3_abs,dist_3_sqr\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n(tensor(0.1114), tensor(0.2021))\n```\n:::\n:::\n\n\n::: {#e92a3fcb .cell execution_count=21}\n``` {.python .cell-code}\ndist_7_abs = (a_3 - mean7).abs().mean()\ndist_7_sqr = ((a_3 - mean7)**2).mean().sqrt()\ndist_7_abs,dist_7_sqr\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\n(tensor(0.1586), tensor(0.3021))\n```\n:::\n:::\n\n\nIn both cases, the distance between our 3 and the \"ideal\" 3 is less than the distance to the ideal 7. So our simple model will give the right prediction in this case.\n\nPyTorch already provides both of these as *loss functions*. You'll find these inside `torch.nn.functional`, which the PyTorch team recommends importing as `F` (and is available by default under that name in fastai):\n\n::: {#aa26047a .cell execution_count=22}\n``` {.python .cell-code}\nF.l1_loss(a_3.float(),mean7), F.mse_loss(a_3,mean7).sqrt()\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n(tensor(0.1586), tensor(0.3021))\n```\n:::\n:::\n\n\nHere `mse` stands for *mean squared error*, and `l1` refers to the standard mathematical jargon for *mean absolute value* (in math it's called the *L1 norm*).\n\n> S: Intuitively, the difference between L1 norm and mean squared error (MSE) is that the latter will penalize bigger mistakes more heavily than the former (and be more lenient with small mistakes).\n\n> J: When I first came across this \"L1\" thingie, I looked it up to see what on earth it meant. I found on Google that it is a _vector norm_ using _absolute value_, so looked up _vector norm_ and started reading: _Given a vector space V over a field F of the real or complex numbers, a norm on V is a nonnegative-valued any function p: V → \\[0,+∞) with the following properties: For all a ∈ F and all u, v ∈ V, p(u + v) ≤ p(u) + p(v)..._ Then I stopped reading. \"Ugh, I'll never understand math!\" I thought, for the thousandth time. Since then I've learned that every time these complex mathy bits of jargon come up in practice, it turns out I can replace them with a tiny bit of code! Like, the _L1 loss_ is just equal to `(a-b).abs().mean()`, where `a` and `b` are tensors. I guess mathy folks just think differently than me... I'll make sure in this book that every time some mathy jargon comes up, I'll give you the little bit of code it's equal to as well, and explain in common-sense terms what's going on.\n\nWe just completed various mathematical operations on PyTorch tensors. If you've done some numeric programming in PyTorch before, you may recognize these as being similar to NumPy arrays. Let's have a look at those two very important data structures.\n\n### NumPy Arrays and PyTorch Tensors\n\n[NumPy](https://numpy.org/) is the most widely used library for scientific and numeric programming in Python. It provides very similar functionality and a very similar API to that provided by PyTorch; however, it does not support using the GPU or calculating gradients, which are both critical for deep learning. Therefore, in this book we will generally use PyTorch tensors instead of NumPy arrays, where possible.\n\n(Note that fastai adds some features to NumPy and PyTorch to make them a bit more similar to each other. If any code in this book doesn't work on your computer, it's possible that you forgot to include a line like this at the start of your notebook: `from fastai.vision.all import *`.)\n\nBut what are arrays and tensors, and why should you care?\n\nPython is slow compared to many languages. Anything fast in Python, NumPy, or PyTorch is likely to be a wrapper for a compiled object written (and optimized) in another language—specifically C. In fact, **NumPy arrays and PyTorch tensors can finish computations many thousands of times faster than using pure Python.**\n\nA NumPy array is a multidimensional table of data, with all items of the same type. Since that can be any type at all, they can even be arrays of arrays, with the innermost arrays potentially being different sizes—this is called a \"jagged array.\" By \"multidimensional table\" we mean, for instance, a list (dimension of one), a table or matrix (dimension of two), a \"table of tables\" or \"cube\" (dimension of three), and so forth. If the items are all of some simple type such as integer or float, then NumPy will store them as a compact C data structure in memory. This is where NumPy shines. NumPy has a wide variety of operators and methods that can run computations on these compact structures at the same speed as optimized C, because they are written in optimized C.\n\nA PyTorch tensor is nearly the same thing as a NumPy array, but with an additional restriction that unlocks some additional capabilities. It's the same in that it, too, is a multidimensional table of data, with all items of the same type. However, the restriction is that a tensor cannot use just any old type—it has to use a single basic numeric type for all components. For example, a PyTorch tensor cannot be jagged. It is always a regularly shaped multidimensional rectangular structure.\n\nThe vast majority of methods and operators supported by NumPy on these structures are also supported by PyTorch, but PyTorch tensors have additional capabilities. One major capability is that these structures can live on the GPU, in which case their computation will be optimized for the GPU and can run much faster (given lots of values to work on). In addition, PyTorch can automatically calculate derivatives of these operations, including combinations of operations. As you'll see, it would be impossible to do deep learning in practice without this capability.\n\n> S: If you don't know what C is, don't worry as you won't need it at all. In a nutshell, it's a low-level  (low-level means more similar to the language that computers use internally) language that is very fast compared to Python. To take advantage of its speed while programming in Python, try to avoid as much as possible writing loops, and replace them by commands that work directly on arrays or tensors.\n\nPerhaps the most important new coding skill for a Python programmer to learn is how to effectively use the array/tensor APIs. We will be showing lots more tricks later in this book, but here's a summary of the key things you need to know for now.\n\nTo create an array or tensor, pass a list (or list of lists, or list of lists of lists, etc.) to `array()` or `tensor()`:\n\n::: {#cc7faec9 .cell execution_count=23}\n``` {.python .cell-code}\ndata = [[1,2,3],[4,5,6]]\narr = array (data)\ntns = tensor(data)\n```\n:::\n\n\n::: {#7c369898 .cell execution_count=24}\n``` {.python .cell-code}\narr  # numpy\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```\narray([[1, 2, 3],\n       [4, 5, 6]])\n```\n:::\n:::\n\n\n::: {#3ff4b48d .cell execution_count=25}\n``` {.python .cell-code}\ntns  # pytorch\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\ntensor([[1, 2, 3],\n        [4, 5, 6]])\n```\n:::\n:::\n\n\nAll the operations that follow are shown on tensors, but the syntax and results for NumPy arrays is identical.\n\nYou can select a row (note that, like lists in Python, tensors are 0-indexed so 1 refers to the second row/column):\n\n::: {#3c99bcff .cell execution_count=26}\n``` {.python .cell-code}\ntns[1]\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\ntensor([4, 5, 6])\n```\n:::\n:::\n\n\nor a column, by using `:` to indicate *all of the first axis* (we sometimes refer to the dimensions of tensors/arrays as *axes*):\n\n::: {#7152e7b2 .cell execution_count=27}\n``` {.python .cell-code}\ntns[:,1]\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```\ntensor([2, 5])\n```\n:::\n:::\n\n\nYou can combine these with Python slice syntax (`[start:end]` with `end` being excluded) to select part of a row or column:\n\n::: {#ddbccb69 .cell execution_count=28}\n``` {.python .cell-code}\ntns[1,1:3]\n```\n\n::: {.cell-output .cell-output-display execution_count=28}\n```\ntensor([5, 6])\n```\n:::\n:::\n\n\nAnd you can use the standard operators such as `+`, `-`, `*`, `/`:\n\n::: {#ad21aeb7 .cell execution_count=29}\n``` {.python .cell-code}\ntns+1\n```\n\n::: {.cell-output .cell-output-display execution_count=29}\n```\ntensor([[2, 3, 4],\n        [5, 6, 7]])\n```\n:::\n:::\n\n\nTensors have a type:\n\n::: {#9f5ca6bd .cell execution_count=30}\n``` {.python .cell-code}\ntns.type()\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```\n'torch.LongTensor'\n```\n:::\n:::\n\n\nAnd will automatically change type as needed, for example from `int` to `float`:\n\n::: {#cf44fb5e .cell execution_count=31}\n``` {.python .cell-code}\ntns*1.5\n```\n\n::: {.cell-output .cell-output-display execution_count=31}\n```\ntensor([[1.5000, 3.0000, 4.5000],\n        [6.0000, 7.5000, 9.0000]])\n```\n:::\n:::\n\n\nSo, is our baseline model any good? To quantify this, we must define a metric.\n\n## Computing Metrics Using Broadcasting\n\nRecall that a metric is a number that is calculated based on the predictions of our model, and the correct labels in our dataset, in order to tell us how good our model is. For instance, we could use either of the functions we saw in the previous section, mean squared error, or mean absolute error, and take the average of them over the whole dataset. However, neither of these are numbers that are very understandable to most people; in practice, we normally use *accuracy* as the metric for classification models.\n\nAs we've discussed, we want to calculate our metric over a *validation set*. This is so that we don't inadvertently overfit—that is, train a model to work well only on our training data. This is not really a risk with the pixel similarity model we're using here as a first try, since it has no trained components, but we'll use a validation set anyway to follow normal practices and to be ready for our second try later.\n\nTo get a validation set we need to remove some of the data from training entirely, so it is not seen by the model at all. As it turns out, the creators of the MNIST dataset have already done this for us. Do you remember how there was a whole separate directory called *valid*? That's what this directory is for!\n\nSo to start with, let's create tensors for our 3s and 7s from that directory. These are the tensors we will use to calculate a metric measuring the quality of our first-try model, which measures distance from an ideal image:\n\n::: {#fc4c41ab .cell execution_count=32}\n``` {.python .cell-code}\nvalid_3_tens = torch.stack([tensor(Image.open(o)) \n                            for o in (path/'valid'/'3').ls()])\nvalid_3_tens = valid_3_tens.float()/255\nvalid_7_tens = torch.stack([tensor(Image.open(o)) \n                            for o in (path/'valid'/'7').ls()])\nvalid_7_tens = valid_7_tens.float()/255\nvalid_3_tens.shape,valid_7_tens.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=32}\n```\n(torch.Size([1010, 28, 28]), torch.Size([1028, 28, 28]))\n```\n:::\n:::\n\n\nIt's good to get in the habit of checking shapes as you go. Here we see two tensors, one representing the 3s validation set of 1,010 images of size 28×28, and one representing the 7s validation set of 1,028 images of size 28×28.\n\nWe ultimately want to write a function, `is_3`, that will decide if an arbitrary image is a 3 or a 7. It will do this by deciding which of our two \"ideal digits\" this arbitrary image is closer to. For that we need to define a notion of distance—that is, a function that calculates the distance between two images.\n\nWe can write a simple function that calculates the mean absolute error using an expression very similar to the one we wrote in the last section:\n\n::: {#734fbc20 .cell execution_count=33}\n``` {.python .cell-code}\ndef mnist_distance(a,b): return (a-b).abs().mean((-1,-2))\nmnist_distance(a_3, mean3)\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n```\ntensor(0.1114)\n```\n:::\n:::\n\n\nThis is the same value we previously calculated for the distance between these two images, the ideal 3 `mean_3` and the arbitrary sample 3 `a_3`, which are both single-image tensors with a shape of `[28,28]`.\n\nBut in order to calculate a metric for overall accuracy, we will need to calculate the distance to the ideal 3 for _every_ image in the validation set. How do we do that calculation? We could write a loop over all of the single-image tensors that are stacked within our validation set tensor, `valid_3_tens`, which has a shape of `[1010,28,28]` representing 1,010 images. But there is a better way.\n\nSomething very interesting happens when we take this exact same distance function, designed for comparing two single images, but pass in as an argument `valid_3_tens`, the tensor that represents the 3s validation set:\n\n::: {#e90642bf .cell execution_count=34}\n``` {.python .cell-code}\nvalid_3_dist = mnist_distance(valid_3_tens, mean3)\nvalid_3_dist, valid_3_dist.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=34}\n```\n(tensor([0.1055, 0.1276, 0.1132,  ..., 0.1300, 0.1100, 0.1123]),\n torch.Size([1010]))\n```\n:::\n:::\n\n\nInstead of complaining about shapes not matching, it returned the distance for every single image as a vector (i.e., a rank-1 tensor) of length 1,010 (the number of 3s in our validation set). How did that happen?\n\nTake another look at our function `mnist_distance`, and you'll see we have there the subtraction `(a-b)`. The magic trick is that PyTorch, when it tries to perform a simple subtraction operation between two tensors of different ranks, will use *broadcasting*. That is, it will automatically expand the tensor with the smaller rank to have the same size as the one with the larger rank. Broadcasting is an important capability that makes tensor code much easier to write.\n\nAfter broadcasting so the two argument tensors have the same rank, PyTorch applies its usual logic for two tensors of the same rank: it performs the operation on each corresponding element of the two tensors, and returns the tensor result. For instance:\n\n::: {#821bd35a .cell execution_count=35}\n``` {.python .cell-code}\ntensor([1,2,3]) + tensor([1,1,1])\n```\n\n::: {.cell-output .cell-output-display execution_count=35}\n```\ntensor([2, 3, 4])\n```\n:::\n:::\n\n\nSo in this case, PyTorch treats `mean3`, a rank-2 tensor representing a single image, as if it were 1,010 copies of the same image, and then subtracts each of those copies from each 3 in our validation set. What shape would you expect this tensor to have? Try to figure it out yourself before you look at the answer below:\n\n::: {#5e95fa08 .cell execution_count=36}\n``` {.python .cell-code}\n(valid_3_tens-mean3).shape\n```\n\n::: {.cell-output .cell-output-display execution_count=36}\n```\ntorch.Size([1010, 28, 28])\n```\n:::\n:::\n\n\nWe are calculating the difference between our \"ideal 3\" and each of the 1,010 3s in the validation set, for each of 28×28 images, resulting in the shape `[1010,28,28]`.\n\nThere are a couple of important points about how broadcasting is implemented, which make it valuable not just for expressivity but also for performance:\n\n- PyTorch doesn't *actually* copy `mean3` 1,010 times. It *pretends* it were a tensor of that shape, but doesn't actually allocate any additional memory\n- It does the whole calculation in C (or, if you're using a GPU, in CUDA, the equivalent of C on the GPU), tens of thousands of times faster than pure Python (up to millions of times faster on a GPU!).\n\nThis is true of all broadcasting and elementwise operations and functions done in PyTorch. *It's the most important technique for you to know to create efficient PyTorch code.*\n\nNext in `mnist_distance` we see `abs`. You might be able to guess now what this does when applied to a tensor. It applies the method to each individual element in the tensor, and returns a tensor of the results (that is, it applies the method \"elementwise\"). So in this case, we'll get back 1,010 matrices of absolute values.\n\nFinally, our function calls `mean((-1,-2))`. The tuple `(-1,-2)` represents a range of axes. In Python, `-1` refers to the last element, and `-2` refers to the second-to-last. So in this case, this tells PyTorch that we want to take the mean ranging over the values indexed by the last two axes of the tensor. The last two axes are the horizontal and vertical dimensions of an image. After taking the mean over the last two axes, we are left with just the first tensor axis, which indexes over our images, which is why our final size was `(1010)`. In other words, for every image, we averaged the intensity of all the pixels in that image.\n\nWe'll be learning lots more about broadcasting throughout this book, especially in <<chapter_foundations>>, and will be practicing it regularly too.\n\nWe can use `mnist_distance` to figure out whether an image is a 3 or not by using the following logic: if the distance between the digit in question and the ideal 3 is less than the distance to the ideal 7, then it's a 3. This function will automatically do broadcasting and be applied elementwise, just like all PyTorch functions and operators:\n\n::: {#8876b120 .cell execution_count=37}\n``` {.python .cell-code}\ndef is_3(x): return mnist_distance(x,mean3) < mnist_distance(x,mean7)\n```\n:::\n\n\nLet's test it on our example case:\n\n::: {#eb0e44a6 .cell execution_count=38}\n``` {.python .cell-code}\nis_3(a_3), is_3(a_3).float()\n```\n\n::: {.cell-output .cell-output-display execution_count=38}\n```\n(tensor(True), tensor(1.))\n```\n:::\n:::\n\n\nNote that when we convert the Boolean response to a float, we get `1.0` for `True` and `0.0` for `False`. Thanks to broadcasting, we can also test it on the full validation set of 3s:\n\n::: {#fed47ade .cell execution_count=39}\n``` {.python .cell-code}\nis_3(valid_3_tens)\n```\n\n::: {.cell-output .cell-output-display execution_count=39}\n```\ntensor([True, True, True,  ..., True, True, True])\n```\n:::\n:::\n\n\nNow we can calculate the accuracy for each of the 3s and 7s by taking the average of that function for all 3s and its inverse for all 7s:\n\n::: {#52f736f3 .cell execution_count=40}\n``` {.python .cell-code}\naccuracy_3s =      is_3(valid_3_tens).float() .mean()\naccuracy_7s = (1 - is_3(valid_7_tens).float()).mean()\n\naccuracy_3s,accuracy_7s,(accuracy_3s+accuracy_7s)/2\n```\n\n::: {.cell-output .cell-output-display execution_count=40}\n```\n(tensor(0.9168), tensor(0.9854), tensor(0.9511))\n```\n:::\n:::\n\n\nThis looks like a pretty good start! We're getting over 90% accuracy on both 3s and 7s, and we've seen how to define a metric conveniently using broadcasting.\n\nBut let's be honest: 3s and 7s are very different-looking digits. And we're only classifying 2 out of the 10 possible digits so far. So we're going to need to do better!\n\nTo do better, perhaps it is time to try a system that does some real learning—that is, that can automatically modify itself to improve its performance. In other words, it's time to talk about the training process, and SGD.\n\n## Stochastic Gradient Descent (SGD)\n\nDo you remember the way that Arthur Samuel described machine learning, which we quoted in <<chapter_intro>>?\n\n> : Suppose we arrange for some automatic means of testing the effectiveness of any current weight assignment in terms of actual performance and provide a mechanism for altering the weight assignment so as to maximize the performance. We need not go into the details of such a procedure to see that it could be made entirely automatic and to see that a machine so programmed would \"learn\" from its experience.\n\nAs we discussed, this is the key to allowing us to have a model that can get better and better—that can learn. But our pixel similarity approach does not really do this. We do not have any kind of weight assignment, or any way of improving based on testing the effectiveness of a weight assignment. In other words, we can't really improve our pixel similarity approach by modifying a set of parameters. In order to take advantage of the power of deep learning, we will first have to represent our task in the way that Arthur Samuel described it.\n\nInstead of trying to find the similarity between an image and an \"ideal image,\" we could instead look at each individual pixel and come up with a set of weights for each one, such that the highest weights are associated with those pixels most likely to be black for a particular category. For instance, pixels toward the bottom right are not very likely to be activated for a 7, so they should have a low weight for a 7, but they are likely to be activated for an 8, so they should have a high weight for an 8. This can be represented as a function and set of weight values for each possible category—for instance the probability of being the number 8:\n\n```\ndef pr_eight(x,w): return (x*w).sum()\n```\n\nHere we are assuming that `x` is the image, represented as a vector—in other words, with all of the rows stacked up end to end into a single long line. And we are assuming that the weights are a vector `w`. If we have this function, then we just need some way to update the weights to make them a little bit better. With such an approach, we can repeat that step a number of times, making the weights better and better, until they are as good as we can make them.\n\nWe want to find the specific values for the vector `w` that causes the result of our function to be high for those images that are actually 8s, and low for those images that are not. Searching for the best vector `w` is a way to search for the best function for recognising 8s. (Because we are not yet using a deep neural network, we are limited by what our function can actually do—we are going to fix that constraint later in this chapter.) \n\nTo be more specific, here are the steps that we are going to require, to turn this function into a machine learning classifier:\n\n1. *Initialize* the weights.\n1. For each image, use these weights to *predict* whether it appears to be a 3 or a 7.\n1. Based on these predictions, calculate how good the model is (its *loss*).\n1. Calculate the *gradient*, which measures for each weight, how changing that weight would change the loss\n1. *Step* (that is, change) all the weights based on that calculation.\n1. Go back to the step 2, and *repeat* the process.\n1. Iterate until you decide to *stop* the training process (for instance, because the model is good enough or you don't want to wait any longer).\n\nThese seven steps, illustrated in <<gradient_descent>>, are the key to the training of all deep learning models. That deep learning turns out to rely entirely on these steps is extremely surprising and counterintuitive. It's amazing that this process can solve such complex problems. But, as you'll see, it really does!\n\n::: {#a890c423 .cell hide_input='true' execution_count=41}\n``` {.python .cell-code}\n#id gradient_descent\n#caption The gradient descent process\n#alt Graph showing the steps for Gradient Descent\ngv('''\ninit->predict->loss->gradient->step->stop\nstep->predict[label=repeat]\n''')\n```\n\n::: {.cell-output .cell-output-display execution_count=41}\n![](04_mnist_basics_files/figure-html/cell-42-output-1.svg){}\n:::\n:::\n\n\nThere are many different ways to do each of these seven steps, and we will be learning about them throughout the rest of this book. These are the details that make a big difference for deep learning practitioners, but it turns out that the general approach to each one generally follows some basic principles. Here are a few guidelines:\n\n- Initialize:: We initialize the parameters to random values. This may sound surprising. There are certainly other choices we could make, such as initializing them to the percentage of times that pixel is activated for that category—but since we already know that we have a routine to improve these weights, it turns out that just starting with random weights works perfectly well.\n- Loss:: This is what Samuel referred to when he spoke of *testing the effectiveness of any current weight assignment in terms of actual performance*. We need some function that will return a number that is small if the performance of the model is good (the standard approach is to treat a small loss as good, and a large loss as bad, although this is just a convention).\n- Step:: A simple way to figure out whether a weight should be increased a bit, or decreased a bit, would be just to try it: increase the weight by a small amount, and see if the loss goes up or down. Once you find the correct direction, you could then change that amount by a bit more, and a bit less, until you find an amount that works well. However, this is slow! As we will see, the magic of calculus allows us to directly figure out in which direction, and by roughly how much, to change each weight, without having to try all these small changes. The way to do this is by calculating *gradients*. This is just a performance optimization, we would get exactly the same results by using the slower manual process as well.\n- Stop:: Once we've decided how many epochs to train the model for (a few suggestions for this were given in the earlier list), we apply that decision. This is where that decision is applied. For our digit classifier, we would keep training until the accuracy of the model started getting worse, or we ran out of time.\n\nBefore applying these steps to our image classification problem, let's illustrate what they look like in a simpler case. First we will define a very simple function, the quadratic—let's pretend that this is our loss function, and `x` is a weight parameter of the function:\n\n::: {#bc1839fa .cell execution_count=42}\n``` {.python .cell-code}\ndef f(x): return x**2\n```\n:::\n\n\nHere is a graph of that function:\n\n::: {#ca83abda .cell execution_count=43}\n``` {.python .cell-code}\nplot_function(f, 'x', 'x**2')\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-44-output-1.png){width=521 height=361}\n:::\n:::\n\n\nThe sequence of steps we described earlier starts by picking some random value for a parameter, and calculating the value of the loss:\n\n::: {#c9164d5c .cell execution_count=44}\n``` {.python .cell-code}\nplot_function(f, 'x', 'x**2')\nplt.scatter(-1.5, f(-1.5), color='red');\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-45-output-1.png){width=521 height=361}\n:::\n:::\n\n\nNow we look to see what would happen if we increased or decreased our parameter by a little bit—the *adjustment*. This is simply the slope at a particular point:\n\n<img alt=\"A graph showing the squared function with the slope at one point\" width=\"400\" src=\"images/grad_illustration.svg\"/>\n\nWe can change our weight by a little in the direction of the slope, calculate our loss and adjustment again, and repeat this a few times. Eventually, we will get to the lowest point on our curve:\n\n<img alt=\"An illustration of gradient descent\" width=\"400\" src=\"images/chapter2_perfect.svg\"/>\n\nThis basic idea goes all the way back to Isaac Newton, who pointed out that we can optimize arbitrary functions in this way. Regardless of how complicated our functions become, this basic approach of gradient descent will not significantly change. The only minor changes we will see later in this book are some handy ways we can make it faster, by finding better steps.\n\n### Calculating Gradients\n\nThe one magic step is the bit where we calculate the gradients. As we mentioned, we use calculus as a performance optimization; it allows us to more quickly calculate whether our loss will go up or down when we adjust our parameters up or down. In other words, the gradients will tell us how much we have to change each weight to make our model better.\n\nYou may remember from your high school calculus class that the *derivative* of a function tells you how much a change in its parameters will change its result. If not, don't worry, lots of us forget calculus once high school is behind us! But you will have to have some intuitive understanding of what a derivative is before you continue, so if this is all very fuzzy in your head, head over to Khan Academy and complete the [lessons on basic derivatives](https://www.khanacademy.org/math/differential-calculus/dc-diff-intro). You won't have to know how to calculate them yourselves, you just have to know what a derivative is.\n\nThe key point about a derivative is this: for any function, such as the quadratic function we saw in the previous section, we can calculate its derivative. The derivative is another function. It calculates the change, rather than the value. For instance, the derivative of the quadratic function at the value 3 tells us how rapidly the function changes at the value 3. More specifically, you may recall that gradient is defined as *rise/run*, that is, the change in the value of the function, divided by the change in the value of the parameter. When we know how our function will change, then we know what we need to do to make it smaller. This is the key to machine learning: having a way to change the parameters of a function to make it smaller. Calculus provides us with a computational shortcut, the derivative, which lets us directly calculate the gradients of our functions.\n\nOne important thing to be aware of is that our function has lots of weights that we need to adjust, so when we calculate the derivative we won't get back one number, but lots of them—a gradient for every weight. But there is nothing mathematically tricky here; you can calculate the derivative with respect to one weight, and treat all the other ones as constant, then repeat that for each other weight. This is how all of the gradients are calculated, for every weight.\n\nWe mentioned just now that you won't have to calculate any gradients yourself. How can that be? Amazingly enough, PyTorch is able to automatically compute the derivative of nearly any function! What's more, it does it very fast. Most of the time, it will be at least as fast as any derivative function that you can create by hand. Let's see an example.\n\nFirst, let's pick a tensor value which we want gradients at:\n\n::: {#0882ea5f .cell execution_count=45}\n``` {.python .cell-code}\nxt = tensor(3.).requires_grad_()\n```\n:::\n\n\nNotice the special method `requires_grad_`? That's the magical incantation we use to tell PyTorch that we want to calculate gradients with respect to that variable at that value. It is essentially tagging the variable, so PyTorch will remember to keep track of how to compute gradients of the other, direct calculations on it that you will ask for.\n\n> a: This API might throw you off if you're coming from math or physics. In those contexts the \"gradient\" of a function is just another function (i.e., its derivative), so you might expect gradient-related APIs to give you a new function. But in deep learning, \"gradients\" usually means the _value_ of a function's derivative at a particular argument value. The PyTorch API also puts the focus on the argument, not the function you're actually computing the gradients of. It may feel backwards at first, but it's just a different perspective.\n\nNow we calculate our function with that value. Notice how PyTorch prints not just the value calculated, but also a note that it has a gradient function it'll be using to calculate our gradients when needed:\n\n::: {#7a549c7c .cell execution_count=46}\n``` {.python .cell-code}\nyt = f(xt)\nyt\n```\n\n::: {.cell-output .cell-output-display execution_count=46}\n```\ntensor(9., grad_fn=<PowBackward0>)\n```\n:::\n:::\n\n\nFinally, we tell PyTorch to calculate the gradients for us:\n\n::: {#bea8ba20 .cell execution_count=47}\n``` {.python .cell-code}\nyt.backward()\n```\n:::\n\n\nThe \"backward\" here refers to *backpropagation*, which is the name given to the process of calculating the derivative of each layer. We'll see how this is done exactly in chapter <<chapter_foundations>>, when we calculate the gradients of a deep neural net from scratch. This is called the \"backward pass\" of the network, as opposed to the \"forward pass,\" which is where the activations are calculated. Life would probably be easier if `backward` was just called `calculate_grad`, but deep learning folks really do like to add jargon everywhere they can!\n\nWe can now view the gradients by checking the `grad` attribute of our tensor:\n\n::: {#2fa2247f .cell execution_count=48}\n``` {.python .cell-code}\nxt.grad\n```\n\n::: {.cell-output .cell-output-display execution_count=48}\n```\ntensor(6.)\n```\n:::\n:::\n\n\nIf you remember your high school calculus rules, the derivative of `x**2` is `2*x`, and we have `x=3`, so the gradients should be `2*3=6`, which is what PyTorch calculated for us!\n\nNow we'll repeat the preceding steps, but with a vector argument for our function:\n\n::: {#ebdf4c5e .cell execution_count=49}\n``` {.python .cell-code}\nxt = tensor([3.,4.,10.]).requires_grad_()\nxt\n```\n\n::: {.cell-output .cell-output-display execution_count=49}\n```\ntensor([ 3.,  4., 10.], requires_grad=True)\n```\n:::\n:::\n\n\nAnd we'll add `sum` to our function so it can take a vector (i.e., a rank-1 tensor), and return a scalar (i.e., a rank-0 tensor):\n\n::: {#4665afb8 .cell execution_count=50}\n``` {.python .cell-code}\ndef f(x): return (x**2).sum()\n\nyt = f(xt)\nyt\n```\n\n::: {.cell-output .cell-output-display execution_count=50}\n```\ntensor(125., grad_fn=<SumBackward0>)\n```\n:::\n:::\n\n\nOur gradients are `2*xt`, as we'd expect!\n\n::: {#ee1e79b5 .cell execution_count=51}\n``` {.python .cell-code}\nyt.backward()\nxt.grad\n```\n\n::: {.cell-output .cell-output-display execution_count=51}\n```\ntensor([ 6.,  8., 20.])\n```\n:::\n:::\n\n\nThe gradients only tell us the slope of our function, they don't actually tell us exactly how far to adjust the parameters. But it gives us some idea of how far; if the slope is very large, then that may suggest that we have more adjustments to do, whereas if the slope is very small, that may suggest that we are close to the optimal value.\n\n### Stepping With a Learning Rate\n\nDeciding how to change our parameters based on the values of the gradients is an important part of the deep learning process. Nearly all approaches start with the basic idea of multiplying the gradient by some small number, called the *learning rate* (LR). The learning rate is often a number between 0.001 and 0.1, although it could be anything. Often, people select a learning rate just by trying a few, and finding which results in the best model after training (we'll show you a better approach later in this book, called the *learning rate finder*). Once you've picked a learning rate, you can adjust your parameters using this simple function:\n\n```\nw -= gradient(w) * lr\n```\n\nThis is known as *stepping* your parameters, using an *optimizer step*.\n\nIf you pick a learning rate that's too low, it can mean having to do a lot of steps. <<descent_small>> illustrates that.\n\n<img alt=\"An illustration of gradient descent with a LR too low\" width=\"400\" caption=\"Gradient descent with low LR\" src=\"images/chapter2_small.svg\" id=\"descent_small\"/>\n\nBut picking a learning rate that's too high is even worse—it can actually result in the loss getting *worse*, as we see in <<descent_div>>!\n\n<img alt=\"An illustration of gradient descent with a LR too high\" width=\"400\" caption=\"Gradient descent with high LR\" src=\"images/chapter2_div.svg\" id=\"descent_div\"/>\n\nIf the learning rate is too high, it may also \"bounce\" around, rather than actually diverging; <<descent_bouncy>> shows how this has the result of taking many steps to train successfully.\n\n<img alt=\"An illustation of gradient descent with a bouncy LR\" width=\"400\" caption=\"Gradient descent with bouncy LR\" src=\"images/chapter2_bouncy.svg\" id=\"descent_bouncy\"/>\n\nNow let's apply all of this in an end-to-end example.\n\n### An End-to-End SGD Example\n\nWe've seen how to use gradients to find a minimum. Now it's time to look at an SGD example and see how finding a minimum can be used to train a model to fit data better.\n\nLet's start with a simple, synthetic, example model. Imagine you were measuring the speed of a roller coaster as it went over the top of a hump. It would start fast, and then get slower as it went up the hill; it would be slowest at the top, and it would then speed up again as it went downhill. You want to build a model of how the speed changes over time. If you were measuring the speed manually every second for 20 seconds, it might look something like this:\n\n::: {#1039b72c .cell execution_count=52}\n``` {.python .cell-code}\ntime = torch.arange(0,20).float(); time\n```\n\n::: {.cell-output .cell-output-display execution_count=52}\n```\ntensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])\n```\n:::\n:::\n\n\n::: {#a1954f38 .cell execution_count=53}\n``` {.python .cell-code}\nspeed = torch.randn(20)*3 + 0.75*(time-9.5)**2 + 1\nplt.scatter(time,speed);\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-54-output-1.png){width=570 height=414}\n:::\n:::\n\n\nWe've added a bit of random noise, since measuring things manually isn't precise. This means it's not that easy to answer the question: what was the roller coaster's speed? Using SGD we can try to find a function that matches our observations. We can't consider every possible function, so let's use a guess that it will be quadratic; i.e., a function of the form `a*(time**2)+(b*time)+c`.\n\nWe want to distinguish clearly between the function's input (the time when we are measuring the coaster's speed) and its parameters (the values that define *which* quadratic we're trying). So, let's collect the parameters in one argument and thus separate the input, `t`, and the parameters, `params`, in the function's signature: \n\n::: {#64fd03ae .cell execution_count=54}\n``` {.python .cell-code}\ndef f(t, params):\n    a,b,c = params\n    return a*(t**2) + (b*t) + c\n```\n:::\n\n\nIn other words, we've restricted the problem of finding the best imaginable function that fits the data, to finding the best *quadratic* function. This greatly simplifies the problem, since every quadratic function is fully defined by the three parameters `a`, `b`, and `c`. Thus, to find the best quadratic function, we only need to find the best values for `a`, `b`, and `c`.\n\nIf we can solve this problem for the three parameters of a quadratic function, we'll be able to apply the same approach for other, more complex functions with more parameters—such as a neural net. Let's find the parameters for `f` first, and then we'll come back and do the same thing for the MNIST dataset with a neural net.\n\nWe need to define first what we mean by \"best.\" We define this precisely by choosing a *loss function*, which will return a value based on a prediction and a target, where lower values of the function correspond to \"better\" predictions. For continuous data, it's common to use *mean squared error*:\n\n::: {#76a099ef .cell execution_count=55}\n``` {.python .cell-code}\ndef mse(preds, targets): return ((preds-targets)**2).mean().sqrt()\n```\n:::\n\n\nNow, let's work through our 7 step process.\n\n#### Step 1: Initialize the parameters\n\nFirst, we initialize the parameters to random values, and tell PyTorch that we want to track their gradients, using `requires_grad_`:\n\n::: {#69497360 .cell execution_count=56}\n``` {.python .cell-code}\nparams = torch.randn(3).requires_grad_()\n```\n:::\n\n\n::: {#78ded143 .cell execution_count=57}\n``` {.python .cell-code}\n#hide\norig_params = params.clone()\n```\n:::\n\n\n#### Step 2: Calculate the predictions\n\nNext, we calculate the predictions:\n\n::: {#0b16670c .cell execution_count=58}\n``` {.python .cell-code}\npreds = f(time, params)\n```\n:::\n\n\nLet's create a little function to see how close our predictions are to our targets, and take a look:\n\n::: {#544b9121 .cell execution_count=59}\n``` {.python .cell-code}\ndef show_preds(preds, ax=None):\n    if ax is None: ax=plt.subplots()[1]\n    ax.scatter(time, speed)\n    ax.scatter(time, to_np(preds), color='red')\n    ax.set_ylim(-300,100)\n```\n:::\n\n\n::: {#c9dbec4d .cell execution_count=60}\n``` {.python .cell-code}\nshow_preds(preds)\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-61-output-1.png){width=593 height=420}\n:::\n:::\n\n\nThis doesn't look very close—our random parameters suggest that the roller coaster will end up going backwards, since we have negative speeds!\n\n#### Step 3: Calculate the loss\n\nWe calculate the loss as follows:\n\n::: {#62449fe9 .cell execution_count=61}\n``` {.python .cell-code}\nloss = mse(preds, speed)\nloss\n```\n\n::: {.cell-output .cell-output-display execution_count=61}\n```\ntensor(160.6979, grad_fn=<SqrtBackward0>)\n```\n:::\n:::\n\n\nOur goal is now to improve this. To do that, we'll need to know the gradients.\n\n#### Step 4: Calculate the gradients\n\nThe next step is to calculate the gradients. In other words, calculate an approximation of how the parameters need to change:\n\n::: {#0324ebae .cell execution_count=62}\n``` {.python .cell-code}\nloss.backward()\nparams.grad\n```\n\n::: {.cell-output .cell-output-display execution_count=62}\n```\ntensor([-165.5151,  -10.6402,   -0.7900])\n```\n:::\n:::\n\n\n::: {#675d69fa .cell execution_count=63}\n``` {.python .cell-code}\nparams.grad * 1e-5\n```\n\n::: {.cell-output .cell-output-display execution_count=63}\n```\ntensor([-1.6552e-03, -1.0640e-04, -7.8996e-06])\n```\n:::\n:::\n\n\nWe can use these gradients to improve our parameters. We'll need to pick a learning rate (we'll discuss how to do that in practice in the next chapter; for now we'll just use 1e-5, or 0.00001):\n\n::: {#49e9b8c7 .cell execution_count=64}\n``` {.python .cell-code}\nparams\n```\n\n::: {.cell-output .cell-output-display execution_count=64}\n```\ntensor([-0.7658, -0.7506,  1.3525], requires_grad=True)\n```\n:::\n:::\n\n\n#### Step 5: Step the weights. \n\nNow we need to update the parameters based on the gradients we just calculated:\n\n::: {#7f8600ad .cell execution_count=65}\n``` {.python .cell-code}\nlr = 1e-5\nparams.data -= lr * params.grad.data\nparams.grad = None\n```\n:::\n\n\n> a: Understanding this bit depends on remembering recent history. To calculate the gradients we call `backward` on the `loss`. But this `loss` was itself calculated by `mse`, which in turn took `preds` as an input, which was calculated using `f` taking as an input `params`, which was the object on which we originally called `required_grads_`—which is the original call that now allows us to call `backward` on `loss`. This chain of function calls represents the mathematical composition of functions, which enables PyTorch to use calculus's chain rule under the hood to calculate these gradients.\n\nLet's see if the loss has improved:\n\n::: {#d0adb91e .cell execution_count=66}\n``` {.python .cell-code}\npreds = f(time,params)\nmse(preds, speed)\n```\n\n::: {.cell-output .cell-output-display execution_count=66}\n```\ntensor(160.4228, grad_fn=<SqrtBackward0>)\n```\n:::\n:::\n\n\nAnd take a look at the plot:\n\n::: {#e774f99d .cell execution_count=67}\n``` {.python .cell-code}\nshow_preds(preds)\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-68-output-1.png){width=593 height=420}\n:::\n:::\n\n\nWe need to repeat this a few times, so we'll create a function to apply one step:\n\n::: {#aed2b41b .cell execution_count=68}\n``` {.python .cell-code}\ndef apply_step(params, prn=True):\n    preds = f(time, params)\n    loss = mse(preds, speed)\n    loss.backward()\n    params.data -= lr * params.grad.data\n    params.grad = None\n    if prn: print(loss.item())\n    return preds\n```\n:::\n\n\n#### Step 6: Repeat the process \n\nNow we iterate. By looping and performing many improvements, we hope to reach a good result:\n\n::: {#a7eaf8ad .cell execution_count=69}\n``` {.python .cell-code}\nfor i in range(10): apply_step(params)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n160.42279052734375\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.6214e-01, -3.2052e+00, -7.7766e+00, -1.3876e+01, -2.1505e+01, -3.0661e+01, -4.1346e+01, -5.3559e+01, -6.7301e+01, -8.2571e+01, -9.9369e+01, -1.1770e+02, -1.3755e+02,\n        -1.5893e+02, -1.8185e+02, -2.0629e+02, -2.3226e+02, -2.5975e+02, -2.8878e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n160.14772033691406\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.6037e-01, -3.1984e+00, -7.7614e+00, -1.3850e+01, -2.1463e+01, -3.0601e+01, -4.1264e+01, -5.3453e+01, -6.7166e+01, -8.2404e+01, -9.9168e+01, -1.1746e+02, -1.3727e+02,\n        -1.5861e+02, -1.8147e+02, -2.0586e+02, -2.3178e+02, -2.5921e+02, -2.8818e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n159.87269592285156\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.5861e-01, -3.1915e+00, -7.7462e+00, -1.3823e+01, -2.1421e+01, -3.0541e+01, -4.1182e+01, -5.3346e+01, -6.7031e+01, -8.2238e+01, -9.8966e+01, -1.1722e+02, -1.3699e+02,\n        -1.5828e+02, -1.8110e+02, -2.0544e+02, -2.3129e+02, -2.5868e+02, -2.8758e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n159.59768676757812\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.5684e-01, -3.1847e+00, -7.7310e+00, -1.3796e+01, -2.1379e+01, -3.0480e+01, -4.1101e+01, -5.3239e+01, -6.6896e+01, -8.2071e+01, -9.8765e+01, -1.1698e+02, -1.3671e+02,\n        -1.5796e+02, -1.8072e+02, -2.0501e+02, -2.3081e+02, -2.5814e+02, -2.8698e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n159.3227081298828\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.5507e-01, -3.1778e+00, -7.7158e+00, -1.3769e+01, -2.1337e+01, -3.0420e+01, -4.1019e+01, -5.3132e+01, -6.6761e+01, -8.1905e+01, -9.8564e+01, -1.1674e+02, -1.3643e+02,\n        -1.5763e+02, -1.8035e+02, -2.0459e+02, -2.3033e+02, -2.5760e+02, -2.8638e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n159.04774475097656\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.5330e-01, -3.1710e+00, -7.7005e+00, -1.3742e+01, -2.1295e+01, -3.0360e+01, -4.0937e+01, -5.3025e+01, -6.6626e+01, -8.1738e+01, -9.8362e+01, -1.1650e+02, -1.3615e+02,\n        -1.5731e+02, -1.7998e+02, -2.0416e+02, -2.2985e+02, -2.5706e+02, -2.8578e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n158.7728271484375\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.5153e-01, -3.1642e+00, -7.6853e+00, -1.3715e+01, -2.1253e+01, -3.0300e+01, -4.0855e+01, -5.2919e+01, -6.6491e+01, -8.1572e+01, -9.8161e+01, -1.1626e+02, -1.3586e+02,\n        -1.5698e+02, -1.7960e+02, -2.0373e+02, -2.2937e+02, -2.5652e+02, -2.8518e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n158.4979248046875\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.4976e-01, -3.1573e+00, -7.6701e+00, -1.3688e+01, -2.1211e+01, -3.0240e+01, -4.0773e+01, -5.2812e+01, -6.6356e+01, -8.1405e+01, -9.7959e+01, -1.1602e+02, -1.3558e+02,\n        -1.5665e+02, -1.7923e+02, -2.0331e+02, -2.2889e+02, -2.5599e+02, -2.8458e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n158.22305297851562\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.4799e-01, -3.1505e+00, -7.6549e+00, -1.3661e+01, -2.1169e+01, -3.0179e+01, -4.0691e+01, -5.2705e+01, -6.6221e+01, -8.1239e+01, -9.7758e+01, -1.1578e+02, -1.3530e+02,\n        -1.5633e+02, -1.7885e+02, -2.0288e+02, -2.2841e+02, -2.5545e+02, -2.8398e+02], grad_fn=<AddBackward0>)\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n157.9481964111328\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=69}\n```\ntensor([ 1.3526e+00, -1.4622e-01, -3.1437e+00, -7.6397e+00, -1.3634e+01, -2.1127e+01, -3.0119e+01, -4.0610e+01, -5.2598e+01, -6.6086e+01, -8.1072e+01, -9.7557e+01, -1.1554e+02, -1.3502e+02,\n        -1.5600e+02, -1.7848e+02, -2.0246e+02, -2.2793e+02, -2.5491e+02, -2.8338e+02], grad_fn=<AddBackward0>)\n```\n:::\n:::\n\n\n::: {#4b92827e .cell execution_count=70}\n``` {.python .cell-code}\n#hide\nparams = orig_params.detach().requires_grad_()\n```\n:::\n\n\nThe loss is going down, just as we hoped! But looking only at these loss numbers disguises the fact that each iteration represents an entirely different quadratic function being tried, on the way to finding the best possible quadratic function. We can see this process visually if, instead of printing out the loss function, we plot the function at every step. Then we can see how the shape is approaching the best possible quadratic function for our data:\n\n::: {#1f03d850 .cell execution_count=71}\n``` {.python .cell-code}\n_,axs = plt.subplots(1,4,figsize=(12,3))\nfor ax in axs: show_preds(apply_step(params, False), ax)\nplt.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-72-output-1.png){width=1137 height=273}\n:::\n:::\n\n\n#### Step 7: stop\n\nWe just decided to stop after 10 epochs arbitrarily. In practice, we would watch the training and validation losses and our metrics to decide when to stop, as we've discussed.\n\n### Summarizing Gradient Descent\n\n::: {#36683416 .cell hide_input='false' execution_count=72}\n``` {.python .cell-code}\n#hide_input\n#id gradient_descent\n#caption The gradient descent process\n#alt Graph showing the steps for Gradient Descent\ngv('''\ninit->predict->loss->gradient->step->stop\nstep->predict[label=repeat]\n''')\n```\n\n::: {.cell-output .cell-output-display execution_count=72}\n![](04_mnist_basics_files/figure-html/cell-73-output-1.svg){}\n:::\n:::\n\n\nTo summarize, at the beginning, the weights of our model can be random (training *from scratch*) or come from a pretrained model (*transfer learning*). In the first case, the output we will get from our inputs won't have anything to do with what we want, and even in the second case, it's very likely the pretrained model won't be very good at the specific task we are targeting. So the model will need to *learn* better weights.\n\nWe begin by comparing the outputs the model gives us with our targets (we have labeled data, so we know what result the model should give) using a *loss function*, which returns a number that we want to make as low as possible by improving our weights. To do this, we take a few data items (such as images) from the training set and feed them to our model. We compare the corresponding targets using our loss function, and the score we get tells us how wrong our predictions were. We then change the weights a little bit to make it slightly better.\n\nTo find how to change the weights to make the loss a bit better, we use calculus to calculate the *gradients*. (Actually, we let PyTorch do it for us!) Let's consider an analogy. Imagine you are lost in the mountains with your car parked at the lowest point. To find your way back to it, you might wander in a random direction, but that probably wouldn't help much. Since you know your vehicle is at the lowest point, you would be better off going downhill. By always taking a step in the direction of the steepest downward slope, you should eventually arrive at your destination. We use the magnitude of the gradient (i.e., the steepness of the slope) to tell us how big a step to take; specifically, we multiply the gradient by a number we choose called the *learning rate* to decide on the step size. We then *iterate* until we have reached the lowest point, which will be our parking lot, then we can *stop*.\n\nAll of that we just saw can be transposed directly to the MNIST dataset, except for the loss function. Let's now see how we can define a good training objective. \n\n## The MNIST Loss Function\n\nWe already have our dependent variables `x`—these are the images themselves. We'll concatenate them all into a single tensor, and also change them from a list of matrices (a rank-3 tensor) to a list of vectors (a rank-2 tensor). We can do this using `view`, which is a PyTorch method that changes the shape of a tensor without changing its contents. `-1` is a special parameter to `view` that means \"make this axis as big as necessary to fit all the data\":\n\n::: {#d6c5625c .cell execution_count=73}\n``` {.python .cell-code}\ntrain_x = torch.cat([stacked_threes, stacked_sevens]).view(-1, 28*28)\n```\n:::\n\n\nWe need a label for each image. We'll use `1` for 3s and `0` for 7s:\n\n::: {#c4529a26 .cell execution_count=74}\n``` {.python .cell-code}\ntrain_y = tensor([1]*len(threes) + [0]*len(sevens)).unsqueeze(1)\ntrain_x.shape,train_y.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=74}\n```\n(torch.Size([12396, 784]), torch.Size([12396, 1]))\n```\n:::\n:::\n\n\nA `Dataset` in PyTorch is required to return a tuple of `(x,y)` when indexed. Python provides a `zip` function which, when combined with `list`, provides a simple way to get this functionality:\n\n::: {#1ccc84eb .cell execution_count=75}\n``` {.python .cell-code}\ndset = list(zip(train_x,train_y))\nx,y = dset[0]\nx.shape,y\n```\n\n::: {.cell-output .cell-output-display execution_count=75}\n```\n(torch.Size([784]), tensor([1]))\n```\n:::\n:::\n\n\n::: {#6d759769 .cell execution_count=76}\n``` {.python .cell-code}\nvalid_x = torch.cat([valid_3_tens, valid_7_tens]).view(-1, 28*28)\nvalid_y = tensor([1]*len(valid_3_tens) + [0]*len(valid_7_tens)).unsqueeze(1)\nvalid_dset = list(zip(valid_x,valid_y))\n```\n:::\n\n\nNow we need an (initially random) weight for every pixel (this is the *initialize* step in our seven-step process):\n\n::: {#ccc7e103 .cell execution_count=77}\n``` {.python .cell-code}\ndef init_params(size, std=1.0): return (torch.randn(size)*std).requires_grad_()\n```\n:::\n\n\n::: {#70c7ff94 .cell execution_count=78}\n``` {.python .cell-code}\nweights = init_params((28*28,1))\n```\n:::\n\n\nThe function `weights*pixels` won't be flexible enough—it is always equal to 0 when the pixels are equal to 0 (i.e., its *intercept* is 0). You might remember from high school math that the formula for a line is `y=w*x+b`; we still need the `b`. We'll initialize it to a random number too:\n\n::: {#2688871e .cell execution_count=79}\n``` {.python .cell-code}\nbias = init_params(1)\n```\n:::\n\n\nIn neural networks, the `w` in the equation `y=w*x+b` is called the *weights*, and the `b` is called the *bias*. Together, the weights and bias make up the *parameters*.\n\n> jargon: Parameters: The _weights_ and _biases_ of a model. The weights are the `w` in the equation `w*x+b`, and the biases are the `b` in that equation.\n\nWe can now calculate a prediction for one image:\n\n::: {#a7433f9c .cell execution_count=80}\n``` {.python .cell-code}\n(train_x[0]*weights.T).sum() + bias\n```\n\n::: {.cell-output .cell-output-display execution_count=80}\n```\ntensor([20.2336], grad_fn=<AddBackward0>)\n```\n:::\n:::\n\n\nWhile we could use a Python `for` loop to calculate the prediction for each image, that would be very slow. Because Python loops don't run on the GPU, and because Python is a slow language for loops in general, we need to represent as much of the computation in a model as possible using higher-level functions.\n\nIn this case, there's an extremely convenient mathematical operation that calculates `w*x` for every row of a matrix—it's called *matrix multiplication*. <<matmul>> shows what matrix multiplication looks like.\n\n<img alt=\"Matrix multiplication\" width=\"400\" caption=\"Matrix multiplication\" src=\"images/matmul2.svg\" id=\"matmul\"/>\n\nThis image shows two matrices, `A` and `B`, being multiplied together. Each item of the result, which we'll call `AB`, contains each item of its corresponding row of `A` multiplied by each item of its corresponding column of `B`, added together. For instance, row 1, column 2 (the orange dot with a red border) is calculated as $a_{1,1} * b_{1,2} + a_{1,2} * b_{2,2}$. If you need a refresher on matrix multiplication, we suggest you take a look at the [Intro to Matrix Multiplication](https://youtu.be/kT4Mp9EdVqs) on *Khan Academy*, since this is the most important mathematical operation in deep learning.\n\nIn Python, matrix multiplication is represented with the `@` operator. Let's try it:\n\n::: {#bc6d9d92 .cell execution_count=81}\n``` {.python .cell-code}\ndef linear1(xb): return xb@weights + bias\npreds = linear1(train_x)\npreds\n```\n\n::: {.cell-output .cell-output-display execution_count=81}\n```\ntensor([[20.2336],\n        [17.0644],\n        [15.2384],\n        ...,\n        [18.3804],\n        [23.8567],\n        [28.6816]], grad_fn=<AddBackward0>)\n```\n:::\n:::\n\n\nThe first element is the same as we calculated before, as we'd expect. This equation, `batch@weights + bias`, is one of the two fundamental equations of any neural network (the other one is the *activation function*, which we'll see in a moment).\n\nLet's check our accuracy. To decide if an output represents a 3 or a 7, we can just check whether it's greater than 0, so our accuracy for each item can be calculated (using broadcasting, so no loops!) with:\n\n::: {#bef97cdf .cell execution_count=82}\n``` {.python .cell-code}\ncorrects = (preds>0.0).float() == train_y\ncorrects\n```\n\n::: {.cell-output .cell-output-display execution_count=82}\n```\ntensor([[ True],\n        [ True],\n        [ True],\n        ...,\n        [False],\n        [False],\n        [False]])\n```\n:::\n:::\n\n\n::: {#f2f837c1 .cell execution_count=83}\n``` {.python .cell-code}\ncorrects.float().mean().item()\n```\n\n::: {.cell-output .cell-output-display execution_count=83}\n```\n0.4912068545818329\n```\n:::\n:::\n\n\nNow let's see what the change in accuracy is for a small change in one of the weights:\n\n::: {#a2fd7c94 .cell execution_count=84}\n``` {.python .cell-code}\nweights[0] *= 1.0001\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-red-fg\">---------------------------------------------------------------------------</span>\n<span class=\"ansi-red-fg\">RuntimeError</span>                              Traceback (most recent call last)\nCell <span class=\"ansi-green-fg\">In[84], line 1</span>\n<span class=\"ansi-green-fg\">----&gt; 1</span> weights[<span style=\"color:rgb(98,98,98)\">0</span>] <span style=\"color:rgb(98,98,98)\">*</span><span style=\"color:rgb(98,98,98)\">=</span> <span style=\"color:rgb(98,98,98)\">1.0001</span>\n\n<span class=\"ansi-red-fg\">RuntimeError</span>: a view of a leaf Variable that requires grad is being used in an in-place operation.</pre>\n```\n:::\n\n:::\n:::\n\n\n::: {#37583c56 .cell execution_count=85}\n``` {.python .cell-code}\npreds = linear1(train_x)\n((preds>0.0).float() == train_y).float().mean().item()\n```\n\n::: {.cell-output .cell-output-display execution_count=85}\n```\n0.4912068545818329\n```\n:::\n:::\n\n\nAs we've seen, we need gradients in order to improve our model using SGD, and in order to calculate gradients we need some *loss function* that represents how good our model is. That is because the gradients are a measure of how that loss function changes with small tweaks to the weights.\n\nSo, we need to choose a loss function. The obvious approach would be to use accuracy, which is our metric, as our loss function as well. In this case, we would calculate our prediction for each image, collect these values to calculate an overall accuracy, and then calculate the gradients of each weight with respect to that overall accuracy.\n\nUnfortunately, we have a significant technical problem here. The gradient of a function is its *slope*, or its steepness, which can be defined as *rise over run*—that is, how much the value of the function goes up or down, divided by how much we changed the input. We can write this in mathematically as: `(y_new - y_old) / (x_new - x_old)`. This gives us a good approximation of the gradient when `x_new` is very similar to `x_old`, meaning that their difference is very small. But accuracy only changes at all when a prediction changes from a 3 to a 7, or vice versa. The problem is that a small change in weights from `x_old` to `x_new` isn't likely to cause any prediction to change, so `(y_new - y_old)` will almost always be 0. In other words, the gradient is 0 almost everywhere.\n\nA very small change in the value of a weight will often not actually change the accuracy at all. This means it is not useful to use accuracy as a loss function—if we do, most of the time our gradients will actually be 0, and the model will not be able to learn from that number.\n\n> S: In mathematical terms, accuracy is a function that is constant almost everywhere (except at the threshold, 0.5), so its derivative is nil almost everywhere (and infinity at the threshold). This then gives gradients that are 0 or infinite, which are useless for updating the model.\n\nInstead, we need a loss function which, when our weights result in slightly better predictions, gives us a slightly better loss. So what does a \"slightly better prediction\" look like, exactly? Well, in this case, it means that if the correct answer is a 3 the score is a little higher, or if the correct answer is a 7 the score is a little lower.\n\nLet's write such a function now. What form does it take?\n\nThe loss function receives not the images themselves, but the predictions from the model. Let's make one argument, `prds`, of values between 0 and 1, where each value is the prediction that an image is a 3. It is a vector (i.e., a rank-1 tensor), indexed over the images.\n\nThe purpose of the loss function is to measure the difference between predicted values and the true values — that is, the targets (aka labels). Let's make another argument, `trgts`, with values of 0 or 1 which tells whether an image actually is a 3 or not. It is also a vector (i.e., another rank-1 tensor), indexed over the images.\n\nSo, for instance, suppose we had three images which we knew were a 3, a 7, and a 3. And suppose our model predicted with high confidence (`0.9`) that the first was a 3, with slight confidence (`0.4`) that the second was a 7, and with fair confidence (`0.2`), but incorrectly, that the last was a 7. This would mean our loss function would receive these values as its inputs:\n\n::: {#1ec88903 .cell execution_count=86}\n``` {.python .cell-code}\ntrgts  = tensor([1,0,1])\nprds   = tensor([0.9, 0.4, 0.2])\n```\n:::\n\n\nHere's a first try at a loss function that measures the distance between `predictions` and `targets`:\n\n::: {#387a64d4 .cell execution_count=87}\n``` {.python .cell-code}\ndef mnist_loss(predictions, targets):\n    return torch.where(targets==1, 1-predictions, predictions).mean()\n```\n:::\n\n\nWe're using a new function, `torch.where(a,b,c)`. This is the same as running the list comprehension `[b[i] if a[i] else c[i] for i in range(len(a))]`, except it works on tensors, at C/CUDA speed. In plain English, this function will measure how distant each prediction is from 1 if it should be 1, and how distant it is from 0 if it should be 0, and then it will take the mean of all those distances.\n\n> note: Read the Docs: It's important to learn about PyTorch functions like this, because looping over tensors in Python performs at Python speed, not C/CUDA speed! Try running `help(torch.where)` now to read the docs for this function, or, better still, look it up on the PyTorch documentation site.\n\nLet's try it on our `prds` and `trgts`:\n\n::: {#b8ab879f .cell execution_count=88}\n``` {.python .cell-code}\ntorch.where(trgts==1, 1-prds, prds)\n```\n\n::: {.cell-output .cell-output-display execution_count=88}\n```\ntensor([0.1000, 0.4000, 0.8000])\n```\n:::\n:::\n\n\nYou can see that this function returns a lower number when predictions are more accurate, when accurate predictions are more confident (higher absolute values), and when inaccurate predictions are less confident. In PyTorch, we always assume that a lower value of a loss function is better. Since we need a scalar for the final loss, `mnist_loss` takes the mean of the previous tensor:\n\n::: {#2dfe8f4b .cell execution_count=89}\n``` {.python .cell-code}\nmnist_loss(prds,trgts)\n```\n\n::: {.cell-output .cell-output-display execution_count=89}\n```\ntensor(0.4333)\n```\n:::\n:::\n\n\nFor instance, if we change our prediction for the one \"false\" target from `0.2` to `0.8` the loss will go down, indicating that this is a better prediction:\n\n::: {#bdb8f366 .cell execution_count=90}\n``` {.python .cell-code}\nmnist_loss(tensor([0.9, 0.4, 0.8]),trgts)\n```\n\n::: {.cell-output .cell-output-display execution_count=90}\n```\ntensor(0.2333)\n```\n:::\n:::\n\n\nOne problem with `mnist_loss` as currently defined is that it assumes that predictions are always between 0 and 1. We need to ensure, then, that this is actually the case! As it happens, there is a function that does exactly that—let's take a look.\n\n### Sigmoid\n\nThe `sigmoid` function always outputs a number between 0 and 1. It's defined as follows:\n\n::: {#ed020796 .cell execution_count=91}\n``` {.python .cell-code}\ndef sigmoid(x): return 1/(1+torch.exp(-x))\n```\n:::\n\n\nPytorch defines an accelerated version for us, so we don’t really need our own. This is an important function in deep learning, since we often want to ensure values are between 0 and 1. This is what it looks like:\n\n::: {#a7dfbcd8 .cell execution_count=92}\n``` {.python .cell-code}\nplot_function(torch.sigmoid, title='Sigmoid', min=-4, max=4)\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-93-output-1.png){width=500 height=362}\n:::\n:::\n\n\nAs you can see, it takes any input value, positive or negative, and smooshes it onto an output value between 0 and 1. It's also a smooth curve that only goes up, which makes it easier for SGD to find meaningful gradients. \n\nLet's update `mnist_loss` to first apply `sigmoid` to the inputs:\n\n::: {#f5d85b6b .cell execution_count=93}\n``` {.python .cell-code}\ndef mnist_loss(predictions, targets):\n    predictions = predictions.sigmoid()\n    return torch.where(targets==1, 1-predictions, predictions).mean()\n```\n:::\n\n\nNow we can be confident our loss function will work, even if the predictions are not between 0 and 1. All that is required is that a higher prediction corresponds to higher confidence an image is a 3.\n\nHaving defined a loss function, now is a good moment to recapitulate why we did this. After all, we already had a metric, which was overall accuracy. So why did we define a loss?\n\nThe key difference is that the metric is to drive human understanding and the loss is to drive automated learning. To drive automated learning, the loss must be a function that has a meaningful derivative. It can't have big flat sections and large jumps, but instead must be reasonably smooth. This is why we designed a loss function that would respond to small changes in confidence level. This requirement means that sometimes it does not really reflect exactly what we are trying to achieve, but is rather a compromise between our real goal, and a function that can be optimized using its gradient. The loss function is calculated for each item in our dataset, and then at the end of an epoch the loss values are all averaged and the overall mean is reported for the epoch.\n\nMetrics, on the other hand, are the numbers that we really care about. These are the values that are printed at the end of each epoch that tell us how our model is really doing. It is important that we learn to focus on these metrics, rather than the loss, when judging the performance of a model.\n\n### SGD and Mini-Batches\n\nNow that we have a loss function that is suitable for driving SGD, we can consider some of the details involved in the next phase of the learning process, which is to change or update the weights based on the gradients. This is called an *optimization step*.\n\nIn order to take an optimization step we need to calculate the loss over one or more data items. How many should we use? We could calculate it for the whole dataset, and take the average, or we could calculate it for a single data item. But neither of these is ideal. Calculating it for the whole dataset would take a very long time. Calculating it for a single item would not use much information, so it would result in a very imprecise and unstable gradient. That is, you'd be going to the trouble of updating the weights, but taking into account only how that would improve the model's performance on that single item.\n\nSo instead we take a compromise between the two: we calculate the average loss for a few data items at a time. This is called a *mini-batch*. The number of data items in the mini-batch is called the *batch size*. A larger batch size means that you will get a more accurate and stable estimate of your dataset's gradients from the loss function, but it will take longer, and you will process fewer mini-batches per epoch. Choosing a good batch size is one of the decisions you need to make as a deep learning practitioner to train your model quickly and accurately. We will talk about how to make this choice throughout this book.\n\nAnother good reason for using mini-batches rather than calculating the gradient on individual data items is that, in practice, we nearly always do our training on an accelerator such as a GPU. These accelerators only perform well if they have lots of work to do at a time, so it's helpful if we can give them lots of data items to work on. Using mini-batches is one of the best ways to do this. However, if you give them too much data to work on at once, they run out of memory—making GPUs happy is also tricky!\n\nAs we saw in our discussion of data augmentation in <<chapter_production>>, we get better generalization if we can vary things during training. One simple and effective thing we can vary is what data items we put in each mini-batch. Rather than simply enumerating our dataset in order for every epoch, instead what we normally do is randomly shuffle it on every epoch, before we create mini-batches. PyTorch and fastai provide a class that will do the shuffling and mini-batch collation for you, called `DataLoader`.\n\nA `DataLoader` can take any Python collection and turn it into an iterator over many batches, like so:\n\n::: {#b6cbfadd .cell execution_count=94}\n``` {.python .cell-code}\ncoll = range(15)\ndl = DataLoader(coll, batch_size=5, shuffle=True)\nlist(dl)\n```\n\n::: {.cell-output .cell-output-display execution_count=94}\n```\n[tensor([ 3, 12,  8, 10,  2]),\n tensor([ 9,  4,  7, 14,  5]),\n tensor([ 1, 13,  0,  6, 11])]\n```\n:::\n:::\n\n\nFor training a model, we don't just want any Python collection, but a collection containing independent and dependent variables (that is, the inputs and targets of the model). A collection that contains tuples of independent and dependent variables is known in PyTorch as a `Dataset`. Here's an example of an extremely simple `Dataset`:\n\n::: {#39296e70 .cell execution_count=95}\n``` {.python .cell-code}\nds = L(enumerate(string.ascii_lowercase))\nds\n```\n\n::: {.cell-output .cell-output-display execution_count=95}\n```\n(#26) [(0, 'a'),(1, 'b'),(2, 'c'),(3, 'd'),(4, 'e'),(5, 'f'),(6, 'g'),(7, 'h'),(8, 'i'),(9, 'j'),(10, 'k'),(11, 'l'),(12, 'm'),(13, 'n'),(14, 'o'),(15, 'p'),(16, 'q'),(17, 'r'),(18, 's'),(19, 't')...]\n```\n:::\n:::\n\n\nWhen we pass a `Dataset` to a `DataLoader` we will get back many batches which are themselves tuples of tensors representing batches of independent and dependent variables:\n\n::: {#9df47448 .cell execution_count=96}\n``` {.python .cell-code}\ndl = DataLoader(ds, batch_size=6, shuffle=True)\nlist(dl)\n```\n\n::: {.cell-output .cell-output-display execution_count=96}\n```\n[(tensor([17, 18, 10, 22,  8, 14]), ('r', 's', 'k', 'w', 'i', 'o')),\n (tensor([20, 15,  9, 13, 21, 12]), ('u', 'p', 'j', 'n', 'v', 'm')),\n (tensor([ 7, 25,  6,  5, 11, 23]), ('h', 'z', 'g', 'f', 'l', 'x')),\n (tensor([ 1,  3,  0, 24, 19, 16]), ('b', 'd', 'a', 'y', 't', 'q')),\n (tensor([2, 4]), ('c', 'e'))]\n```\n:::\n:::\n\n\nWe are now ready to write our first training loop for a model using SGD!\n\n## Putting It All Together\n\nIt's time to implement the process we saw in <<gradient_descent>>. In code, our process will be implemented something like this for each epoch:\n\n```python\nfor x,y in dl:\n    pred = model(x)\n    loss = loss_func(pred, y)\n    loss.backward()\n    parameters -= parameters.grad * lr\n```\n\nFirst, let's re-initialize our parameters:\n\n::: {#dad199fd .cell execution_count=97}\n``` {.python .cell-code}\nweights = init_params((28*28,1))\nbias = init_params(1)\n```\n:::\n\n\nA `DataLoader` can be created from a `Dataset`:\n\n::: {#a1b7c1d6 .cell execution_count=98}\n``` {.python .cell-code}\ndl = DataLoader(dset, batch_size=256)\nxb,yb = first(dl)\nxb.shape,yb.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=98}\n```\n(torch.Size([256, 784]), torch.Size([256, 1]))\n```\n:::\n:::\n\n\nWe'll do the same for the validation set:\n\n::: {#4f223d83 .cell execution_count=99}\n``` {.python .cell-code}\nvalid_dl = DataLoader(valid_dset, batch_size=256)\n```\n:::\n\n\nLet's create a mini-batch of size 4 for testing:\n\n::: {#3e58d73c .cell execution_count=100}\n``` {.python .cell-code}\nbatch = train_x[:4]\nbatch.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=100}\n```\ntorch.Size([4, 784])\n```\n:::\n:::\n\n\n::: {#3962ad56 .cell execution_count=101}\n``` {.python .cell-code}\npreds = linear1(batch)\npreds\n```\n\n::: {.cell-output .cell-output-display execution_count=101}\n```\ntensor([[-2.1876],\n        [-8.3973],\n        [ 2.5000],\n        [-4.9473]], grad_fn=<AddBackward0>)\n```\n:::\n:::\n\n\n::: {#b4fc61ba .cell execution_count=102}\n``` {.python .cell-code}\nloss = mnist_loss(preds, train_y[:4])\nloss\n```\n\n::: {.cell-output .cell-output-display execution_count=102}\n```\ntensor(0.7419, grad_fn=<MeanBackward0>)\n```\n:::\n:::\n\n\nNow we can calculate the gradients:\n\n::: {#fe72aa69 .cell execution_count=103}\n``` {.python .cell-code}\nloss.backward()\nweights.grad.shape,weights.grad.mean(),bias.grad\n```\n\n::: {.cell-output .cell-output-display execution_count=103}\n```\n(torch.Size([784, 1]), tensor(-0.0061), tensor([-0.0420]))\n```\n:::\n:::\n\n\nLet's put that all in a function:\n\n::: {#8782ddad .cell execution_count=104}\n``` {.python .cell-code}\ndef calc_grad(xb, yb, model):\n    preds = model(xb)\n    loss = mnist_loss(preds, yb)\n    loss.backward()\n```\n:::\n\n\nand test it:\n\n::: {#ce964234 .cell execution_count=105}\n``` {.python .cell-code}\ncalc_grad(batch, train_y[:4], linear1)\nweights.grad.mean(),bias.grad\n```\n\n::: {.cell-output .cell-output-display execution_count=105}\n```\n(tensor(-0.0121), tensor([-0.0840]))\n```\n:::\n:::\n\n\nBut look what happens if we call it twice:\n\n::: {#3060a3fc .cell execution_count=106}\n``` {.python .cell-code}\ncalc_grad(batch, train_y[:4], linear1)\nweights.grad.mean(),bias.grad\n```\n\n::: {.cell-output .cell-output-display execution_count=106}\n```\n(tensor(-0.0182), tensor([-0.1260]))\n```\n:::\n:::\n\n\nThe gradients have changed! The reason for this is that `loss.backward` actually *adds* the gradients of `loss` to any gradients that are currently stored. So, we have to set the current gradients to 0 first:\n\n::: {#ae41e6aa .cell execution_count=107}\n``` {.python .cell-code}\nweights.grad.zero_()\nbias.grad.zero_();\n```\n:::\n\n\n> note: Inplace Operations: Methods in PyTorch whose names end in an underscore modify their objects _in place_. For instance, `bias.zero_()` sets all elements of the tensor `bias` to 0.\n\nOur only remaining step is to update the weights and biases based on the gradient and learning rate. When we do so, we have to tell PyTorch not to take the gradient of this step too—otherwise things will get very confusing when we try to compute the derivative at the next batch! If we assign to the `data` attribute of a tensor then PyTorch will not take the gradient of that step. Here's our basic training loop for an epoch:\n\n::: {#c84884cf .cell execution_count=108}\n``` {.python .cell-code}\ndef train_epoch(model, lr, params):\n    for xb,yb in dl:\n        calc_grad(xb, yb, model)\n        for p in params:\n            p.data -= p.grad*lr\n            p.grad.zero_()\n```\n:::\n\n\nWe also want to check how we're doing, by looking at the accuracy of the validation set. To decide if an output represents a 3 or a 7, we can just check whether it's greater than 0. So our accuracy for each item can be calculated (using broadcasting, so no loops!) with:\n\n::: {#55c24faf .cell execution_count=109}\n``` {.python .cell-code}\n(preds>0.0).float() == train_y[:4]\n```\n\n::: {.cell-output .cell-output-display execution_count=109}\n```\ntensor([[False],\n        [False],\n        [ True],\n        [False]])\n```\n:::\n:::\n\n\nThat gives us this function to calculate our validation accuracy:\n\n::: {#e0c6ed0b .cell execution_count=110}\n``` {.python .cell-code}\ndef batch_accuracy(xb, yb):\n    preds = xb.sigmoid()\n    correct = (preds>0.5) == yb\n    return correct.float().mean()\n```\n:::\n\n\nWe can check it works:\n\n::: {#3c75ac11 .cell execution_count=111}\n``` {.python .cell-code}\nbatch_accuracy(linear1(batch), train_y[:4])\n```\n\n::: {.cell-output .cell-output-display execution_count=111}\n```\ntensor(0.2500)\n```\n:::\n:::\n\n\nand then put the batches together:\n\n::: {#5c81e845 .cell execution_count=112}\n``` {.python .cell-code}\ndef validate_epoch(model):\n    accs = [batch_accuracy(model(xb), yb) for xb,yb in valid_dl]\n    return round(torch.stack(accs).mean().item(), 4)\n```\n:::\n\n\n::: {#99a240a7 .cell execution_count=113}\n``` {.python .cell-code}\nvalidate_epoch(linear1)\n```\n\n::: {.cell-output .cell-output-display execution_count=113}\n```\n0.5262\n```\n:::\n:::\n\n\nThat's our starting point. Let's train for one epoch, and see if the accuracy improves:\n\n::: {#502820d2 .cell execution_count=114}\n``` {.python .cell-code}\nlr = 1.\nparams = weights,bias\ntrain_epoch(linear1, lr, params)\nvalidate_epoch(linear1)\n```\n\n::: {.cell-output .cell-output-display execution_count=114}\n```\n0.6664\n```\n:::\n:::\n\n\nThen do a few more:\n\n::: {#e77dad3a .cell execution_count=115}\n``` {.python .cell-code}\nfor i in range(20):\n    train_epoch(linear1, lr, params)\n    print(validate_epoch(linear1), end=' ')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.8265 0.89 0.9183 0.9276 0.9398 0.9467 0.9506 0.9525 0.956 0.9579 0.9599 0.9608 0.9613 0.9618 0.9633 0.9638 0.9647 0.9657 0.9672 0.9677 \n```\n:::\n:::\n\n\nLooking good! We're already about at the same accuracy as our \"pixel similarity\" approach, and we've created a general-purpose foundation we can build on. Our next step will be to create an object that will handle the SGD step for us. In PyTorch, it's called an *optimizer*.\n\n### Creating an Optimizer\n\nBecause this is such a general foundation, PyTorch provides some useful classes to make it easier to implement. The first thing we can do is replace our `linear1` function with PyTorch's `nn.Linear` module. A *module* is an object of a class that inherits from the PyTorch `nn.Module` class. Objects of this class behave identically to standard Python functions, in that you can call them using parentheses and they will return the activations of a model.\n\n`nn.Linear` does the same thing as our `init_params` and `linear` together. It contains both the *weights* and *biases* in a single class. Here's how we replicate our model from the previous section:\n\n::: {#9574e9fd .cell execution_count=116}\n``` {.python .cell-code}\nlinear_model = nn.Linear(28*28,1)\n```\n:::\n\n\nEvery PyTorch module knows what parameters it has that can be trained; they are available through the `parameters` method:\n\n::: {#a57f9668 .cell execution_count=117}\n``` {.python .cell-code}\nw,b = linear_model.parameters()\nw.shape,b.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=117}\n```\n(torch.Size([1, 784]), torch.Size([1]))\n```\n:::\n:::\n\n\nWe can use this information to create an optimizer:\n\n::: {#7f11d43c .cell execution_count=118}\n``` {.python .cell-code}\nclass BasicOptim:\n    def __init__(self,params,lr): self.params,self.lr = list(params),lr\n\n    def step(self, *args, **kwargs):\n        for p in self.params: p.data -= p.grad.data * self.lr\n\n    def zero_grad(self, *args, **kwargs):\n        for p in self.params: p.grad = None\n```\n:::\n\n\nWe can create our optimizer by passing in the model's parameters:\n\n::: {#b4c30871 .cell execution_count=119}\n``` {.python .cell-code}\nopt = BasicOptim(linear_model.parameters(), lr)\n```\n:::\n\n\nOur training loop can now be simplified to:\n\n::: {#204d53b1 .cell execution_count=120}\n``` {.python .cell-code}\ndef train_epoch(model):\n    for xb,yb in dl:\n        calc_grad(xb, yb, model)\n        opt.step()\n        opt.zero_grad()\n```\n:::\n\n\nOur validation function doesn't need to change at all:\n\n::: {#c4b378fb .cell execution_count=121}\n``` {.python .cell-code}\nvalidate_epoch(linear_model)\n```\n\n::: {.cell-output .cell-output-display execution_count=121}\n```\n0.4608\n```\n:::\n:::\n\n\nLet's put our little training loop in a function, to make things simpler:\n\n::: {#27e91f2a .cell execution_count=122}\n``` {.python .cell-code}\ndef train_model(model, epochs):\n    for i in range(epochs):\n        train_epoch(model)\n        print(validate_epoch(model), end=' ')\n```\n:::\n\n\nThe results are the same as in the previous section:\n\n::: {#bb94bdc4 .cell execution_count=123}\n``` {.python .cell-code}\ntrain_model(linear_model, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.4932 0.7685 0.8554 0.9135 0.9345 0.9482 0.957 0.9633 0.9658 0.9677 0.9697 0.9716 0.9736 0.9746 0.976 0.977 0.9775 0.9775 0.978 0.9785 \n```\n:::\n:::\n\n\nfastai provides the `SGD` class which, by default, does the same thing as our `BasicOptim`:\n\n::: {#28ec3d37 .cell execution_count=124}\n``` {.python .cell-code}\nlinear_model = nn.Linear(28*28,1)\nopt = SGD(linear_model.parameters(), lr)\ntrain_model(linear_model, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n0.4932 0.8179 0.8496 0.914 0.9345 0.9482 0.957 0.9619 0.9658 0.9672 0.9692 0.9712 0.9741 0.9751 0.976 0.9775 0.9775 0.978 0.9785 0.979 \n```\n:::\n:::\n\n\nfastai also provides `Learner.fit`, which we can use instead of `train_model`. To create a `Learner` we first need to create a `DataLoaders`, by passing in our training and validation `DataLoader`s:\n\n::: {#ce983629 .cell execution_count=125}\n``` {.python .cell-code}\ndls = DataLoaders(dl, valid_dl)\n```\n:::\n\n\nTo create a `Learner` without using an application (such as `cnn_learner`) we need to pass in all the elements that we've created in this chapter: the `DataLoaders`, the model, the optimization function (which will be passed the parameters), the loss function, and optionally any metrics to print:\n\n::: {#74c46e04 .cell execution_count=126}\n``` {.python .cell-code}\nlearn = Learner(dls, nn.Linear(28*28,1), opt_func=SGD,\n                loss_func=mnist_loss, metrics=batch_accuracy)\n```\n:::\n\n\nNow we can call `fit`:\n\n::: {#afb2d335 .cell execution_count=127}\n``` {.python .cell-code}\nlearn.fit(10, lr=lr)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n\n<style>\n    /* Turns off some styling */\n    progress {\n        /* gets rid of default border in Firefox and Opera. */\n        border: none;\n        /* Needs to be in here for Safari polyfill so background images work as expected. */\n        background-size: auto;\n    }\n    progress:not([value]), progress:not([value])::-webkit-progress-bar {\n        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);\n    }\n    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {\n        background: #F44336;\n    }\n</style>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: left;\">\n      <th>epoch</th>\n      <th>train_loss</th>\n      <th>valid_loss</th>\n      <th>batch_accuracy</th>\n      <th>time</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0</td>\n      <td>0.636709</td>\n      <td>0.503144</td>\n      <td>0.495584</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>1</td>\n      <td>0.429828</td>\n      <td>0.248517</td>\n      <td>0.777233</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>2</td>\n      <td>0.161680</td>\n      <td>0.155361</td>\n      <td>0.861629</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>3</td>\n      <td>0.072948</td>\n      <td>0.097722</td>\n      <td>0.917566</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>4</td>\n      <td>0.040128</td>\n      <td>0.073205</td>\n      <td>0.936212</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>5</td>\n      <td>0.027210</td>\n      <td>0.059466</td>\n      <td>0.950442</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>6</td>\n      <td>0.021837</td>\n      <td>0.050799</td>\n      <td>0.957802</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>7</td>\n      <td>0.019398</td>\n      <td>0.044980</td>\n      <td>0.964181</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>8</td>\n      <td>0.018122</td>\n      <td>0.040853</td>\n      <td>0.966143</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>9</td>\n      <td>0.017330</td>\n      <td>0.037788</td>\n      <td>0.968106</td>\n      <td>00:00</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nAs you can see, there's nothing magic about the PyTorch and fastai classes. They are just convenient pre-packaged pieces that make your life a bit easier! (They also provide a lot of extra functionality we'll be using in future chapters.)\n\nWith these classes, we can now replace our linear model with a neural network.\n\n## Adding a Nonlinearity\n\nSo far we have a general procedure for optimizing the parameters of a function, and we have tried it out on a very boring function: a simple linear classifier. A linear classifier is very constrained in terms of what it can do. To make it a bit more complex (and able to handle more tasks), we need to add something nonlinear between two linear classifiers—this is what gives us a neural network.\n\nHere is the entire definition of a basic neural network:\n\n::: {#b7f0b9c5 .cell execution_count=128}\n``` {.python .cell-code}\ndef simple_net(xb): \n    res = xb@w1 + b1\n    res = res.max(tensor(0.0))\n    res = res@w2 + b2\n    return res\n```\n:::\n\n\nThat's it! All we have in `simple_net` is two linear classifiers with a `max` function between them.\n\nHere, `w1` and `w2` are weight tensors, and `b1` and `b2` are bias tensors; that is, parameters that are initially randomly initialized, just like we did in the previous section:\n\n::: {#a5598eaf .cell execution_count=129}\n``` {.python .cell-code}\nw1 = init_params((28*28,30))\nb1 = init_params(30)\nw2 = init_params((30,1))\nb2 = init_params(1)\n```\n:::\n\n\nThe key point about this is that `w1` has 30 output activations (which means that `w2` must have 30 input activations, so they match). That means that the first layer can construct 30 different features, each representing some different mix of pixels. You can change that `30` to anything you like, to make the model more or less complex.\n\nThat little function `res.max(tensor(0.0))` is called a *rectified linear unit*, also known as *ReLU*. We think we can all agree that *rectified linear unit* sounds pretty fancy and complicated... But actually, there's nothing more to it than `res.max(tensor(0.0))`—in other words, replace every negative number with a zero. This tiny function is also available in PyTorch as `F.relu`:\n\n::: {#7cf04993 .cell execution_count=130}\n``` {.python .cell-code}\nplot_function(F.relu)\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-131-output-1.png){width=511 height=340}\n:::\n:::\n\n\n> J: There is an enormous amount of jargon in deep learning, including terms like _rectified linear unit_. The vast vast majority of this jargon is no more complicated than can be implemented in a short line of code, as we saw in this example. The reality is that for academics to get their papers published they need to make them sound as impressive and sophisticated as possible. One of the ways that they do that is to introduce jargon. Unfortunately, this has the result that the field ends up becoming far more intimidating and difficult to get into than it should be. You do have to learn the jargon, because otherwise papers and tutorials are not going to mean much to you. But that doesn't mean you have to find the jargon intimidating. Just remember, when you come across a word or phrase that you haven't seen before, it will almost certainly turn to be referring to a very simple concept.\n\nThe basic idea is that by using more linear layers, we can have our model do more computation, and therefore model more complex functions. But there's no point just putting one linear layout directly after another one, because when we multiply things together and then add them up multiple times, that could be replaced by multiplying different things together and adding them up just once! That is to say, a series of any number of linear layers in a row can be replaced with a single linear layer with a different set of parameters.\n\nBut if we put a nonlinear function between them, such as `max`, then this is no longer true. Now each linear layer is actually somewhat decoupled from the other ones, and can do its own useful work. The `max` function is particularly interesting, because it operates as a simple `if` statement.\n\n> S: Mathematically, we say the composition of two linear functions is another linear function. So, we can stack as many linear classifiers as we want on top of each other, and without nonlinear functions between them, it will just be the same as one linear classifier.\n\nAmazingly enough, it can be mathematically proven that this little function can solve any computable problem to an arbitrarily high level of accuracy, if you can find the right parameters for `w1` and `w2` and if you make these matrices big enough. For any arbitrarily wiggly function, we can approximate it as a bunch of lines joined together; to make it closer to the wiggly function, we just have to use shorter lines. This is known as the *universal approximation theorem*. The three lines of code that we have here are known as *layers*. The first and third are known as *linear layers*, and the second line of code is known variously as a *nonlinearity*, or *activation function*.\n\nJust like in the previous section, we can replace this code with something a bit simpler, by taking advantage of PyTorch:\n\n::: {#576fbd91 .cell execution_count=131}\n``` {.python .cell-code}\nsimple_net = nn.Sequential(\n    nn.Linear(28*28,30),\n    nn.ReLU(),\n    nn.Linear(30,1)\n)\n```\n:::\n\n\n`nn.Sequential` creates a module that will call each of the listed layers or functions in turn.\n\n`nn.ReLU` is a PyTorch module that does exactly the same thing as the `F.relu` function. Most functions that can appear in a model also have identical forms that are modules. Generally, it's just a case of replacing `F` with `nn` and changing the capitalization. When using `nn.Sequential`, PyTorch requires us to use the module version. Since modules are classes, we have to instantiate them, which is why you see `nn.ReLU()` in this example. \n\nBecause `nn.Sequential` is a module, we can get its parameters, which will return a list of all the parameters of all the modules it contains. Let's try it out! As this is a deeper model, we'll use a lower learning rate and a few more epochs.\n\n::: {#29b9ea33 .cell execution_count=132}\n``` {.python .cell-code}\nlearn = Learner(dls, simple_net, opt_func=SGD,\n                loss_func=mnist_loss, metrics=batch_accuracy)\n```\n:::\n\n\n::: {#333fa8b3 .cell execution_count=133}\n``` {.python .cell-code}\n#hide_output\nlearn.fit(40, 0.1)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n\n<style>\n    /* Turns off some styling */\n    progress {\n        /* gets rid of default border in Firefox and Opera. */\n        border: none;\n        /* Needs to be in here for Safari polyfill so background images work as expected. */\n        background-size: auto;\n    }\n    progress:not([value]), progress:not([value])::-webkit-progress-bar {\n        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);\n    }\n    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {\n        background: #F44336;\n    }\n</style>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: left;\">\n      <th>epoch</th>\n      <th>train_loss</th>\n      <th>valid_loss</th>\n      <th>batch_accuracy</th>\n      <th>time</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0</td>\n      <td>0.333021</td>\n      <td>0.396112</td>\n      <td>0.512267</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>1</td>\n      <td>0.152461</td>\n      <td>0.235238</td>\n      <td>0.797350</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>2</td>\n      <td>0.083573</td>\n      <td>0.117471</td>\n      <td>0.911678</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>3</td>\n      <td>0.054309</td>\n      <td>0.078720</td>\n      <td>0.940628</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>4</td>\n      <td>0.040829</td>\n      <td>0.061228</td>\n      <td>0.956330</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>5</td>\n      <td>0.034006</td>\n      <td>0.051490</td>\n      <td>0.963690</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>6</td>\n      <td>0.030123</td>\n      <td>0.045381</td>\n      <td>0.966634</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>7</td>\n      <td>0.027619</td>\n      <td>0.041218</td>\n      <td>0.968106</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>8</td>\n      <td>0.025825</td>\n      <td>0.038200</td>\n      <td>0.969087</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>9</td>\n      <td>0.024441</td>\n      <td>0.035901</td>\n      <td>0.969578</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>10</td>\n      <td>0.023321</td>\n      <td>0.034082</td>\n      <td>0.971541</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>11</td>\n      <td>0.022387</td>\n      <td>0.032598</td>\n      <td>0.972031</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>12</td>\n      <td>0.021592</td>\n      <td>0.031353</td>\n      <td>0.974485</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>13</td>\n      <td>0.020904</td>\n      <td>0.030284</td>\n      <td>0.975466</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>14</td>\n      <td>0.020300</td>\n      <td>0.029352</td>\n      <td>0.975466</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>15</td>\n      <td>0.019766</td>\n      <td>0.028526</td>\n      <td>0.975466</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>16</td>\n      <td>0.019288</td>\n      <td>0.027788</td>\n      <td>0.976448</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>17</td>\n      <td>0.018857</td>\n      <td>0.027124</td>\n      <td>0.977429</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>18</td>\n      <td>0.018465</td>\n      <td>0.026523</td>\n      <td>0.978410</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>19</td>\n      <td>0.018107</td>\n      <td>0.025977</td>\n      <td>0.978901</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>20</td>\n      <td>0.017777</td>\n      <td>0.025479</td>\n      <td>0.978901</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>21</td>\n      <td>0.017473</td>\n      <td>0.025022</td>\n      <td>0.979392</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>22</td>\n      <td>0.017191</td>\n      <td>0.024601</td>\n      <td>0.980373</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>23</td>\n      <td>0.016927</td>\n      <td>0.024213</td>\n      <td>0.980373</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>24</td>\n      <td>0.016680</td>\n      <td>0.023855</td>\n      <td>0.981354</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>25</td>\n      <td>0.016449</td>\n      <td>0.023521</td>\n      <td>0.981354</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>26</td>\n      <td>0.016230</td>\n      <td>0.023211</td>\n      <td>0.981354</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>27</td>\n      <td>0.016023</td>\n      <td>0.022922</td>\n      <td>0.981354</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>28</td>\n      <td>0.015827</td>\n      <td>0.022653</td>\n      <td>0.981845</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>29</td>\n      <td>0.015641</td>\n      <td>0.022401</td>\n      <td>0.981845</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>30</td>\n      <td>0.015463</td>\n      <td>0.022165</td>\n      <td>0.981845</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>31</td>\n      <td>0.015294</td>\n      <td>0.021944</td>\n      <td>0.983317</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>32</td>\n      <td>0.015132</td>\n      <td>0.021736</td>\n      <td>0.982826</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>33</td>\n      <td>0.014977</td>\n      <td>0.021541</td>\n      <td>0.982826</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>34</td>\n      <td>0.014828</td>\n      <td>0.021357</td>\n      <td>0.982336</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>35</td>\n      <td>0.014686</td>\n      <td>0.021184</td>\n      <td>0.982336</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>36</td>\n      <td>0.014549</td>\n      <td>0.021019</td>\n      <td>0.982336</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>37</td>\n      <td>0.014417</td>\n      <td>0.020864</td>\n      <td>0.982336</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>38</td>\n      <td>0.014290</td>\n      <td>0.020716</td>\n      <td>0.982336</td>\n      <td>00:00</td>\n    </tr>\n    <tr>\n      <td>39</td>\n      <td>0.014168</td>\n      <td>0.020576</td>\n      <td>0.982336</td>\n      <td>00:00</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nWe're not showing the 40 lines of output here to save room; the training process is recorded in `learn.recorder`, with the table of output stored in the `values` attribute, so we can plot the accuracy over training as:\n\n::: {#55983272 .cell execution_count=134}\n``` {.python .cell-code}\nplt.plot(L(learn.recorder.values).itemgot(2));\n```\n\n::: {.cell-output .cell-output-display}\n![](04_mnist_basics_files/figure-html/cell-135-output-1.png){width=575 height=415}\n:::\n:::\n\n\nAnd we can view the final accuracy:\n\n::: {#c3000de6 .cell execution_count=135}\n``` {.python .cell-code}\nlearn.recorder.values[-1][2]\n```\n\n::: {.cell-output .cell-output-display execution_count=135}\n```\n0.98233562707901\n```\n:::\n:::\n\n\nAt this point we have something that is rather magical:\n\n1. A function that can solve any problem to any level of accuracy (the neural network) given the correct set of parameters\n1. A way to find the best set of parameters for any function (stochastic gradient descent)\n\nThis is why deep learning can do things which seem rather magical such fantastic things. Believing that this combination of simple techniques can really solve any problem is one of the biggest steps that we find many students have to take. It seems too good to be true—surely things should be more difficult and complicated than this? Our recommendation: try it out! We just tried it on the MNIST dataset and you have seen the results. And since we are doing everything from scratch ourselves (except for calculating the gradients) you know that there is no special magic hiding behind the scenes.\n\n### Going Deeper\n\nThere is no need to stop at just two linear layers. We can add as many as we want, as long as we add a nonlinearity between each pair of linear layers. As you will learn, however, the deeper the model gets, the harder it is to optimize the parameters in practice. Later in this book you will learn about some simple but brilliantly effective techniques for training deeper models.\n\nWe already know that a single nonlinearity with two linear layers is enough to approximate any function. So why would we use deeper models? The reason is performance. With a deeper model (that is, one with more layers) we do not need to use as many parameters; it turns out that we can use smaller matrices with more layers, and get better results than we would get with larger matrices, and few layers.\n\nThat means that we can train the model more quickly, and it will take up less memory. In the 1990s researchers were so focused on the universal approximation theorem that very few were experimenting with more than one nonlinearity. This theoretical but not practical foundation held back the field for years. Some researchers, however, did experiment with deep models, and eventually were able to show that these models could perform much better in practice. Eventually, theoretical results were developed which showed why this happens. Today, it is extremely unusual to find anybody using a neural network with just one nonlinearity.\n\nHere what happens when we train an 18-layer model using the same approach we saw in <<chapter_intro>>:\n\n::: {#82977701 .cell execution_count=136}\n``` {.python .cell-code}\ndls = ImageDataLoaders.from_folder(path)\nlearn = cnn_learner(dls, resnet18, pretrained=False,\n                    loss_func=F.cross_entropy, metrics=accuracy)\nlearn.fit_one_cycle(1, 0.1)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/home/oren/work/blog/.venv/lib/python3.10/site-packages/fastai/vision/learner.py:303: UserWarning:\n\n`cnn_learner` has been renamed to `vision_learner` -- please update your code\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n\n<style>\n    /* Turns off some styling */\n    progress {\n        /* gets rid of default border in Firefox and Opera. */\n        border: none;\n        /* Needs to be in here for Safari polyfill so background images work as expected. */\n        background-size: auto;\n    }\n    progress:not([value]), progress:not([value])::-webkit-progress-bar {\n        background: repeating-linear-gradient(45deg, #7e7e7e, #7e7e7e 10px, #5c5c5c 10px, #5c5c5c 20px);\n    }\n    .progress-bar-interrupted, .progress-bar-interrupted::-webkit-progress-bar {\n        background: #F44336;\n    }\n</style>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: left;\">\n      <th>epoch</th>\n      <th>train_loss</th>\n      <th>valid_loss</th>\n      <th>accuracy</th>\n      <th>time</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>0</td>\n      <td>0.068768</td>\n      <td>0.011310</td>\n      <td>0.996565</td>\n      <td>00:05</td>\n    </tr>\n  </tbody>\n</table>\n```\n:::\n:::\n\n\nNearly 100% accuracy! That's a big difference compared to our simple neural net. But as you'll learn in the remainder of this book, there are just a few little tricks you need to use to get such great results from scratch yourself. You already know the key foundational pieces. (Of course, even once you know all the tricks, you'll nearly always want to work with the pre-built classes provided by PyTorch and fastai, because they save you having to think about all the little details yourself.)\n\n## Jargon Recap\n\nCongratulations: you now know how to create and train a deep neural network from scratch! We've gone through quite a few steps to get to this point, but you might be surprised at how simple it really is.\n\nNow that we are at this point, it is a good opportunity to define, and review, some jargon and key concepts.\n\nA neural network contains a lot of numbers, but they are only of two types: numbers that are calculated, and the parameters that these numbers are calculated from. This gives us the two most important pieces of jargon to learn:\n\n- Activations:: Numbers that are calculated (both by linear and nonlinear layers)\n- Parameters:: Numbers that are randomly initialized, and optimized (that is, the numbers that define the model)\n\nWe will often talk in this book about activations and parameters. Remember that they have very specific meanings. They are numbers. They are not abstract concepts, but they are actual specific numbers that are in your model. Part of becoming a good deep learning practitioner is getting used to the idea of actually looking at your activations and parameters, and plotting them and testing whether they are behaving correctly.\n\nOur activations and parameters are all contained in *tensors*. These are simply regularly shaped arrays—for example, a matrix. Matrices have rows and columns; we call these the *axes* or *dimensions*. The number of dimensions of a tensor is its *rank*. There are some special tensors:\n\n- Rank zero: scalar\n- Rank one: vector\n- Rank two: matrix\n\nA neural network contains a number of layers. Each layer is either *linear* or *nonlinear*. We generally alternate between these two kinds of layers in a neural network. Sometimes people refer to both a linear layer and its subsequent nonlinearity together as a single layer. Yes, this is confusing. Sometimes a nonlinearity is referred to as an *activation function*.\n\n<<dljargon1>> summarizes the key concepts related to SGD.\n\n```asciidoc\n[[dljargon1]]\n.Deep learning vocabulary\n[options=\"header\"]\n|=====\n| Term | Meaning\n|ReLU | Function that returns 0 for negative numbers and doesn't change positive numbers.\n|Mini-batch | A small group of inputs and labels gathered together in two arrays. A gradient descent step is updated on this batch (rather than a whole epoch).\n|Forward pass | Applying the model to some input and computing the predictions.\n|Loss | A value that represents how well (or badly) our model is doing.\n|Gradient | The derivative of the loss with respect to some parameter of the model.\n|Backward pass | Computing the gradients of the loss with respect to all model parameters.\n|Gradient descent | Taking a step in the directions opposite to the gradients to make the model parameters a little bit better.\n|Learning rate | The size of the step we take when applying SGD to update the parameters of the model.\n|=====\n```\n\n> note: _Choose Your Own Adventure_ Reminder: Did you choose to skip over chapters 2 & 3, in your excitement to peek under the hood? Well, here's your reminder to head back to chapter 2 now, because you'll be needing to know that stuff very soon!\n\n## Questionnaire\n\n1. How is a grayscale image represented on a computer? How about a color image?\n1. How are the files and folders in the `MNIST_SAMPLE` dataset structured? Why?\n1. Explain how the \"pixel similarity\" approach to classifying digits works.\n1. What is a list comprehension? Create one now that selects odd numbers from a list and doubles them.\n1. What is a \"rank-3 tensor\"?\n1. What is the difference between tensor rank and shape? How do you get the rank from the shape?\n1. What are RMSE and L1 norm?\n1. How can you apply a calculation on thousands of numbers at once, many thousands of times faster than a Python loop?\n1. Create a 3×3 tensor or array containing the numbers from 1 to 9. Double it. Select the bottom-right four numbers.\n1. What is broadcasting?\n1. Are metrics generally calculated using the training set, or the validation set? Why?\n1. What is SGD?\n1. Why does SGD use mini-batches?\n1. What are the seven steps in SGD for machine learning?\n1. How do we initialize the weights in a model?\n1. What is \"loss\"?\n1. Why can't we always use a high learning rate?\n1. What is a \"gradient\"?\n1. Do you need to know how to calculate gradients yourself?\n1. Why can't we use accuracy as a loss function?\n1. Draw the sigmoid function. What is special about its shape?\n1. What is the difference between a loss function and a metric?\n1. What is the function to calculate new weights using a learning rate?\n1. What does the `DataLoader` class do?\n1. Write pseudocode showing the basic steps taken in each epoch for SGD.\n1. Create a function that, if passed two arguments `[1,2,3,4]` and `'abcd'`, returns `[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]`. What is special about that output data structure?\n1. What does `view` do in PyTorch?\n1. What are the \"bias\" parameters in a neural network? Why do we need them?\n1. What does the `@` operator do in Python?\n1. What does the `backward` method do?\n1. Why do we have to zero the gradients?\n1. What information do we have to pass to `Learner`?\n1. Show Python or pseudocode for the basic steps of a training loop.\n1. What is \"ReLU\"? Draw a plot of it for values from `-2` to `+2`.\n1. What is an \"activation function\"?\n1. What's the difference between `F.relu` and `nn.ReLU`?\n1. The universal approximation theorem shows that any function can be approximated as closely as needed using just one nonlinearity. So why do we normally use more?\n\n### Further Research\n\n1. Create your own implementation of `Learner` from scratch, based on the training loop shown in this chapter.\n1. Complete all the steps in this chapter using the full MNIST datasets (that is, for all digits, not just 3s and 7s). This is a significant project and will take you quite a bit of time to complete! You'll need to do some of your own research to figure out how to overcome some obstacles you'll meet on the way.\n\n",
    "supporting": [
      "04_mnist_basics_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}