---
date: 2024-03-26
title: "braindump 03 2024"
draft: True
---

## Notes Helpers

-   code local Multi-document summary
-   use named entity recognition to markup entities.
-   check Wikidata for links
-   identify links
-   markup for examples
-   highlight import points.
-   ask to inset a place holder for a chart etc if such was mentioned.
-   ask for a section by section summary and do a check against the lesson transcript.

## AI Camp Meetup

-   [Meetup Event Page](https://www.meetup.com/azureisrael/events/299975482/)
-   [Reactor event page](https://developer.microsoft.com/en-us/reactor/events/21812/)
-   [Azure-Israel community/](https://globalai.community/communities/azure-israel/)
-   [Semantic Kernel documentation](https://learn.microsoft.com/en-us/semantic-kernel/)
-   [Semantic Kernel on GH](https://github.com/microsoft/semantic-kernel)
-   [GitHub Copilot Fundamentals - Understand the AI pair programmer](https://learn.microsoft.com/en-us/training/paths/copilot//?wt.mc_id=3reg_21959_webpage_reactor)

Notes: most of the event was introductory. However the demos were pretty amazing.

### Alon Fliess - Demos

-  [Alon Fliess MVP ^<i class="bi bi-linkedin"></i>^](https://www.linkedin.com/in/alon-fliess-36655/)

1.  showed semantic Kernel
2.  an app for lawyers to accessing trial evidence material using RAG and interact with it.

-   extraction of NE
-   summarize documents
-   where to locate pieces of evidence.
-   some of the access is via semantic kernel directly, e.g. witness list
-   some of questions are using LLM, e.g. which witness to question

3.  diagnostics of his windows computers. Each has an agent, the agent can parse logs, use any files using an agents.

### Aviel Blumenfeld

From Theory to Practice: RAG and LLM Integration on Azure by Aviel Blumenfeld

Demo using langchain and vector d-base solution to implement RAG in a Gradio interface.

1.  chatting with Joe Biden's commencement address
2.  chatting with a d-base using SQL - amazing on two levels.

-   Interaction with the SQL d-base
-   Generation of SQL using RAG
-   Quearying d-base using natural language with access to SQL in the background.

### Todo

-   Add the video?
-   slide are supposed to go up on the Meetup Event Page
-   add speakers to linkedin - both show impressive entrepreneurial mindset.

## RL second Course

-   [Katerina Fragkiadaki](https://katefvision.github.io/#resources)
-   [Katerina Fragkiadaki slides](https://katefvision.github.io/katefSlides/RECITATIONtrajectoryoptimization_katef.pdf)

## Coding Communities

-   [globalai](https://globalai.community/) AI portal !?
-   [codewars](www.codewars.com) - Challenges
-   [maakaf](https://maakaf.netlify.app/) Israeli FOSS

## Courses

-   [Google - ML foundational-courses](https://developers.google.com/machine-learning/foundational-courses)
-   [Google - advanced-courses](https://developers.google.com/machine-learning/advanced-courses)
-   [MIT OC - Artificial Intelligence](https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/resources/lecture-1-introduction-and-scope/)
-   [Edx Convex Optimization](https://learning.edx.org/course/course-v1:StanfordOnline+SOE-YCVX0001+1T2020/home)
-   [Rhetoric: The Art of Persuasive Writing and Public Speaking](https://courses.edx.org/courses/course-v1:HarvardX+AESTHINT15+3T2023/)
-   [Statistical Learning with Python](https://learning.edx.org/course/course-v1:StanfordOnline+SOHS-YSTATSLEARNINGP+1T2024/home)
-   [Apply prompt engineering with Azure OpenAI Service](https://learn.microsoft.com/en-us/training/modules/apply-prompt-engineering-azure-openai/?wt.mc_id=3reg_S-1295_webpage_reactor)
-   [Develop Generative AI solutions with Azure OpenAI Service](https://learn.microsoft.com/en-us/training/paths/develop-ai-solutions-azure-openai/?wt.mc_id=3reg_S-1295_webpage_reactor)
-   [GitHub Copilot Fundamentals - Understand the AI pair programmer](https://learn.microsoft.com/en-us/training/paths/copilot//?wt.mc_id=3reg_21959_webpage_reactor)
-   [deeplearning.ai](https://learn.deeplearning.ai/)


## Tools

-   [Downloading Coursera.org videos etc](https://github.com/raffaem/cs-dlp%5D)
-   [Gradio]() Coding quick ML demos in Python
-   [trame](https://kitware.github.io/trame/guide/)
-   [Semantic Kernel](https://github.com/microsoft/semantic-kernel) and [overview](https://learn.microsoft.com/en-us/semantic-kernel/overview/)
-   [CVXPY](https://www.cvxpy.org/) modeling language for convex optimization problems
    -   Is there a Semantic Kernel integration !?
-   [Nbdev]() - Literate Programming in Jupyter Notebooks.
-   [Paperlib](https://paperlib.app/en/download.html) organize academic papers
-   [Shinylive](https://github.com/quarto-ext/shinylive) pure python shiny
-   [Mesa GH]() [Mesa Examples GH](https://github.com/projectmesa/mesa-examples/tree/main) ABM framework [tutorial](https://mesa.readthedocs.io/en/main/tutorials/intro_tutorial.html)
-   [cocmd](https://cocmd.org/)
-   [pandas-ai](https://github.com/Sinaptik-AI/pandas-ai)
-   Musical
    -   [SuperCollider](https://supercollider.github.io/)
    -   [Sonic Pi](https://sonic-pi.net/)
    -   <https://overtone.github.io/>

## Losses & Regularization

-   Many problems can be solved by minimizing a loss functions. They arise in different domains under different names.
    -   Utility Function in Economics and Game Theory.
    -   Risk Functions in Decision theory and Economics
    -   Cost Function in many contexts
    -   Objective Function in optimization and ML
    -   Error Function in statistics and ML, specifically in regression problems.
    -   Fitness Function in genetic algorithms and evolutionary computing
    -   Penalty Function in constrained optimization,
    -   Criterion Function in econometrics and statistics
    -   Energy Function in physical Modeling c.f. [Hopfield network ^<i class="bi bi-wikipedia"></i>^](https://en.wikipedia.org/wiki/Hopfield_network), [Spin glass ^<i class="bi bi-wikipedia"></i>^](https://en.wikipedia.org/wiki/Spin_glass) ...
-   A loss function allows us to solve it as an optimization problem using certain tools like CVXPY, SGD and some RL algorithms.
-   More interesting though is that we can often combine loss function in both simple and creative ways to solve for a combined objective.
-   Sometimes we can also add a 'regularization term" which then constrains the problem further. Regularization terms one understood are generalization.
-   Forms of Loss functions and Regularization are a bit like basic physical laws in the sense that once we have framed our problem within this form we may inherit any insights for any other problems framed this way previously.
-   Some Losses
    -   One famous example in economics is the [Cobb–Douglas production function ^<i class="bi bi-wikipedia"></i>^](https://en.wikipedia.org/wiki/Cobb%E2%80%93Douglas_production_function) this is used creatively in the SugarScape ^[\[Citation\ Needed \]](#){.badge .bg-primary}^   simulation in a number of ways. I was impressed how the authors extending their initial model while maintaining the original functional form. The Wikipedia article linked above shows some interesting economical properties that arise from this form, other representations, and relation to CES and Translog production functions.
    -   Triplet loss
    -   Log Loss
-   In terms of modeling Loss function are often simple and therefore highly fertile in terms of reusable application and generalizations.

## Papers

-   [Social Influence as Intrinsic Motivation for Multi-Agent Deep Reinforcement Learning](https://arxiv.org/abs/1810.08647) Natasha Jaques, etc
-   [Measuring Compositionality in Representation Learning](https://openreview.net/forum?id=HJz05o0qK7) Jacob Andreas
-   [EXPRESSIVITY OF EMERGENT LANGUAGES IS A TRADE-OFF BETWEEN CONTEXTUAL COMPLEXITY AND UNPREDICTABILITY](https://arxiv.org/pdf/2106.03982.pdf)
-   [Foundation Policies with Hilbert Representations](https://seohong.me/projects/hilp/) seems to be an applicable to RL gradient methods.
-   [LEWIS’S SIGNALING GAME AS BETA-VAE FOR NATURAL WORD LENGTHS AND SEGMENTS](https://openreview.net/pdf?id=HC0msxE3sf)
-   [data2vec 2.0](https://ai.meta.com/blog/ai-self-supervised-learning-data2vec/) 2022
-   [PIVOT: Iterative Visual Prompting Elicits Actionable Knowledge for VLMs](https://pivot-prompt.github.io/) by Soroush Nasiriany\* et all.
-   [DINO v2](https://ai.meta.com/blog/dino-v2-computer-vision-self-supervised-learning/)
-   [Zero-shot transfer across 93 languages: Open-sourcing enhanced LASER library](https://ai.meta.com/blog/laser-multilingual-sentence-embeddings/) sentence embeddings [LASER GH](https://github.com/facebookresearch/LASER)
-   [The Standing Ovation Problem](https://faculty.sites.iastate.edu/tesfatsi/archive/tesfatsi/StandingOvation.MillerPage.pdf)
-   [Extracting and composing robust features with denoising autoencoders](https://dl.acm.org/doi/abs/10.1145/1390156.1390294) 2008 OCR learning Robust Features

## Articles

-   [bp’s Causal Inference Symposium: Discussing the next frontier in AI](https://medium.com/bp-tech-blog/bps-causal-inference-symposium-discussing-the-next-frontier-in-ai-71ca2a7dbd2c) by [Fran Bell](https://www.linkedin.com/posts/franziska-bell-phd-00097992_causalai-aiapplications-activity-7077699140490547200-ToE8/)

## Bayesian Games

-   [Bayesian Games: Games with Incomplete Information](http://www.ma.huji.ac.il/~zamir/documents/BayesianGames_ShmuelZamir.pdf) by [SHMUEL ZAMIR](http://www.ma.huji.ac.il/~zamir/)

## Videos

-   [I Like Notebooks](https://www.youtube.com/watch?v=9Q6sLbz37gk) by **Jeremy Howard**

-   Live coding music [Sam Aaron YouTube channel](https://www.youtube.com/@SamAaron) and tutorials by Sam Aaron <https://www.twitch.tv/samaaron>

-   [Bayesian Causal inference: why you should be excited](https://www.youtube.com/watch?v=XpF07iHeWUQ)

## Books

-   [The GenAI Guidebook](https://ravinkumar.com/GenAiGuidebook/model_basics/SimpleLinRegFlax.html)
-   [Artificial Intelligence: A Modern Approach, 4th Global ed](https://aima.cs.berkeley.edu/global-index.html)


## CI

-   [Robert Ness]() [CI book](https://www.manning.com/books/causal-ai)
-   [r/CausalInference](https://www.reddit.com/r/CausalInference/)
-   [Resources for Learning Causal Inference](https://ccaballeroh.github.io/blog/causal%20inference/Causal-inference-resources.html)


## Miscelnia

