---
date: 2024-02-11
title: Phrasal Verbs
subtitle: Hungarian Grammar
description: A dictionary of Hungarian phrasal verbs
categories: ["hungarian", "phrasal verbs", "dictionary", "coverb","vocabulary"]
---

Back when I was staying in Budapest I took some Hungarian classes at the "Debreceni Nyári Egyetem". After a year I got through some of the basic levels. I a book store with some titles by their publisher's at greatly reduced prices so I bought "Igéző szotar", a dictionary of phrasal verbs. However I found a too advanced to be very useful at the time.

1.  It does not have any conjugation tables.
2.  It does describe the morphology of the phrasal verbs by examples
3.  It also provides many alternative forms (synonyms) that can avoid the phrasal verbs.
4.  It has a many exercises that can be used to practice the phrasal verbs.

It turns out most Hungarian verbs can take up to 20 prefixes to form a phrasal verb. Some of these are not always intuitive and can be very idiomatic. However there are only 20 prefixes and these prefixes are related to postpositive that attach to nouns as suffixes.

It seems to offer a quick windfall for expanding your vocabulary. The conjugation of Hungarian verb can easily take as many as 70 forms. Once we factor in the number of prefixes the number of forms quickly jumps to as many as 1400. This is a huge number of forms to learn. However the good news is that the conjugation of the main verb is the same for all the phrasal verbs that are formed with the same prefix. Even better news is once you mastered all the phrasal verbs for just two of three verb your eyes will be able to decipher any other phrasal verb that you come across.

Also the Hungarian lexicon is highly agglutinative. This means that you might encounter a word embedded within some other word. For example a computer is called a "szamitogep" which is a compound word made up of "szamit" which means to calculate and "gep" which means machine. Or to photograph which is "fenykepezik" which is made up of "feny" which means light and "kep" which means picture.

You might not know the exact meaning of the phrasal verb but you will be able to guess the meaning of the phrasal verb but you should be able to partition the verb into a prefix, the main verb and the conjugation suffix. You will have a rough idea of what each of these might mean and you might now also be better able to guess the meaning of the phrasal verb based on the context in which it is used. At least if you are able to make sense the words belonging to the phrasal verb slots.

Once you have mastered the conjugation of any of the main verb these phrasal verbs follow the same conjugation rules. This means that with little more work you are well on your way to mastering many semantically related phrasal verbs. The outcome is that the vocabulary of the language is highly regular and mostly predictable.

The challenge isn't the prefixes but what semantics slots become available when you add a prefix to a verb. This is where the idiomatic nature of the language comes into play. Because we are now talking about a new semantic space that part is not always predictable.

However this is a case where we can transfer the semantics of the verb from say english.

it has no English translation. However there is a smaller volume that goes along that is bilingual

It is It is a dictionary of verbs that are conjugated in various ways.

+-------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+
| A szótár az Igézőben előforduló igekötős igéket és szókapcsolatokat tartalmazza angol megfelelőikkel. | The dictionary contains conjugation verbs and word connections with their English equivalents. |
+-------------------------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------+

+----------------+-----------------+---------------------+-----------------------+
| [ad](#sec-ad)  | [áll](#sec-all) | [állít](#sec-állít) | [beszél](#sec-beszél) |
+----------------+-----------------+---------------------+-----------------------+
| bújik          | csap            | csíp                | csúszik               |
+----------------+-----------------+---------------------+-----------------------+
| dob            | dől             | enged               | esik                  |
+----------------+-----------------+---------------------+-----------------------+
| eszik          | ég              | él                  | épít                  |
+----------------+-----------------+---------------------+-----------------------+
| ér             | fekszik         | fér                 | fizet                 |
+----------------+-----------------+---------------------+-----------------------+
| fog            | folyik          | fordít              | fordul                |
+----------------+-----------------+---------------------+-----------------------+
| forgat         | fúj             | fut                 | gondol                |
+----------------+-----------------+---------------------+-----------------------+
| hagy           | hajt            | hív                 | hoz                   |
+----------------+-----------------+---------------------+-----------------------+
| húz            | ismer           | ír                  | jár                   |
+----------------+-----------------+---------------------+-----------------------+
| játszik        | jön             | jut                 | kap                   |
+----------------+-----------------+---------------------+-----------------------+
| kapcsol        | kel             | ken                 | kér                   |
+----------------+-----------------+---------------------+-----------------------+
| kerül          | köt             | lát                 | lép                   |
+----------------+-----------------+---------------------+-----------------------+
| lő             | marad           | megy                | mér                   |
+----------------+-----------------+---------------------+-----------------------+
| mond           | mos             | mutat               | néz                   |
+----------------+-----------------+---------------------+-----------------------+
| nyom           | nyújt           | olvas               | szt                   |
+----------------+-----------------+---------------------+-----------------------+
| pakol          | ragad           | rak                 | ráz                   |
+----------------+-----------------+---------------------+-----------------------+
| szakad         | száll           | szalad              | szárnít               |
+----------------+-----------------+---------------------+-----------------------+
| számol         | szed            | szorít              | szorul                |
+----------------+-----------------+---------------------+-----------------------+
| szól           | szúr            | talál               | tanul                 |
+----------------+-----------------+---------------------+-----------------------+
| tart           | tesz            | telik               | tér                   |
+----------------+-----------------+---------------------+-----------------------+
| tölt           | tör             | törik               | tűz                   |
+----------------+-----------------+---------------------+-----------------------+
| ugrik          | ül              | üt                  | vág                   |
+----------------+-----------------+---------------------+-----------------------+
| választ        | válik           | vált                | vesz                  |
+----------------+-----------------+---------------------+-----------------------+
| ver            | vet             | vezet               | visz                  |
+----------------+-----------------+---------------------+-----------------------+
| von            | vonul           | zár                 |                       |
+----------------+-----------------+---------------------+-----------------------+

: verbs

The prefixes

+-----------------------------------------------------------------------------+-----------------------------------------------------+
| Prefix                                                                      | Translation                                         |
+=============================================================================+=====================================================+
| ABBA-                                                                       |                                                     |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| AGYON-                                                                      | critical, exagerated, to death                      |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ALÁ-                                                                        | Under                                               |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ÁT-                                                                         | through                                             |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| BE-                                                                         | in, inside                                          |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| BELE-                                                                       | in, inside                                          |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| EGYBE-                                                                      | in one                                              |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| EL-                                                                         | away, off, wrong                                    |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ELLEN-                                                                      | counter-, anti-, against                            |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ELŐ                                                                         | fore-                                               |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ELŐRE                                                                       | fore-, in advance                                   |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| FEL-, FÖL-                                                                  | up                                                  |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| FÉLBE-                                                                      | in two, inter-, in half                             |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| FELÜL, -FÖLÜL-                                                              | super                                               |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| FENN-, FÖNN-                                                                | up                                                  |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| HÁTRA-                                                                      | backwards, over-                                    |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| HAZA-                                                                       | home                                                |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| HELYRE-                                                                     | to its place, right                                 |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| HOZZÁ-                                                                      | to him/her/it                                       |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| IDE-, ODA-                                                                  | here, there                                         |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| KERESZTÜL-                                                                  | through, across                                     |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| KETTÉ-                                                                      | in two, apart                                       |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| KI-                                                                         | out                                                 |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| KÖRÜL-                                                                      | around                                              |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| [KÖZRE-](https://en.wiktionary.org/wiki/k%C3%B6zre-#Hungarian "wiktionary") | surrounding, taking part in,releasing to the public |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| KÜLÖN                                                                       | apart                                               |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| LE-                                                                         | down                                                |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| MELLÉ                                                                       | mis-; by                                            |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| NEKI-                                                                       | to him/her/it                                       |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ÖSSZE-                                                                      | together                                            |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| RÁ-                                                                         | onto him/her/it                                     |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| RAJTA-                                                                      | on him/her/it                                       |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| SZEMBE-                                                                     | against                                             |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| SZERTE-                                                                     | everywhere, apart                                   |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| TELE-                                                                       | full                                                |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| TOVÁBB-                                                                     | on                                                  |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| TÖNKRE-                                                                     |                                                     |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| TÚL-                                                                        | over-                                               |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ÚJJÁ-                                                                       | re-; to become new                                  |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| ÚJRA                                                                        | re-, again                                          |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| UTÁNA-                                                                      |                                                     |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| VÉGBE-                                                                      | to the end                                          |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| VÉGHEZ-                                                                     | to the end                                          |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| VÉGIG-                                                                      | until the end                                       |
+-----------------------------------------------------------------------------+-----------------------------------------------------+
| VISSZA-                                                                     | back                                                |
+-----------------------------------------------------------------------------+-----------------------------------------------------+

: prefixes

this makes use of many abbreviations

## AD \| to Give {#sec-ad}

+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| verb                                        | phrase                                                              | english                                     |
+=============================================+=====================================================================+=============================================+
| ad                                          | ad                                                                  | give                                        |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| ad                                          | ad vmit                                                             | give sth                                    |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| ad                                          | ad vkinek vmit                                                      | give sth to sy                              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| [át](# "through across")+[ad](# "to give")  | [átad](# "hand over") [vkinek](# "someone") [vmit](# "something")   | hand over sth to sy                         |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| átad                                        | átadja a szot vkinek                                                | call upon sy to speak                       |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| átad                                        | átadja az üdvözletet vkinek                                         | convey sy's best wishes to sy, \            |
|                                             |                                                                     | say hello to sy for sy                      |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| átad                                        | átadja a helyét vkinek                                              | give up one's seat to sy                    |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| bead                                        | beadja a gyógyszert vkinek                                          | administer medicine to sy                   |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| bead                                        | beadja a kérvényt vhová                                             | submit / present a request; file a petition |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| bead                                        | beadja a felmondását                                                | hand in one' s notice                       |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| elad                                        | elad vmit vmennyiért                                                | sell sth for sth                            |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| előad                                       | előad vmit                                                          | perform, enact, recite etc. sth             |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| előad                                       | előad                                                               | lecture                                     |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| felad                                       | felad (pl. levelet, csomagot)                                       | post (e.g. a letter, a parcel)              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| felad                                       | feladja a kabátot vkire                                             | help sy on with their coat                  |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| felad                                       | feladja a leckét                                                    | assign homework                             |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| hozzáad                                     | hozzáad vmihez vmit                                                 | add sth to sth                              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| hozzáad                                     | hozzáad vkihez vkit                                                 | marry sy off                                |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| idead                                       | idead vmit                                                          | give sth to me                              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| kiad                                        | kiad egy könyvet                                                    | publish a book                              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| kiad                                        | kiad egy szobát / egy lakást                                        | rent a room / a house                       |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| kiad                                        | kiadja a munkát vkinek                                              | distribute work                             |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| kiad                                        | kiadja a mérgét / dühét                                             | vent one's rage                             |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| lead                                        | lead vmit vhol                                                      | leave sth swhere, hand sth in               |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| lead                                        | lead vmennyit                                                       | lose weight                                 |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| megad                                       | megadja az adósságát                                                | pay off one's debts                         |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| megad                                       | megadja az engedélyt                                                | give permission to sy                       |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| megad                                       | mindent megad vkinek                                                | let sy have evrything                       |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| összead                                     |                                                                     |                                             |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| összead                                     | összeadja a szamokat                                                | add up numbers                              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| összead                                     | összead vkiket                                                      | marry a couple                              |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| ráad                                        | ráadja vkire a kabátját                                             | help sy on with their coat                  |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| továbbad                                    | továbbad vmit vkinek                                                | pass sth on to sy                           |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja a tartozását                                             | pay back one's debt                         |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja szász forintot                                           | give back 100 forints change back           |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja a kölcsönt                                               | return a loan                               |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja a pénzt                                                  | give back the money                         |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja a választ                                                | give back the answer                        |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja a könyvet                                                | return a book                               |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+
| visszaad                                    | visszaadja a kulcsot                                                | return a key                                |
+---------------------------------------------+---------------------------------------------------------------------+---------------------------------------------+

**Frazeologizmusok**

+--------------------------------------+------------------------------------------+
| beadja a derekát                     | give in, accept sth                      |
+--------------------------------------+------------------------------------------+
| beadja apait-anyait                  | give sy a piece of one's mind            |
+--------------------------------------+------------------------------------------+
| beadja a szót                        | give sy the floor                        |
+--------------------------------------+------------------------------------------+
| eladja magát/ a lelkét/ a becsületét | sell oneself / one's soul / one's honour |
+--------------------------------------+------------------------------------------+
| eladja a lelkét az ördögnek          | sell one's soul to the devil             |
+--------------------------------------+------------------------------------------+
| feladja a harcot                     | give up the fight                        |
+--------------------------------------+------------------------------------------+
| feladja a leckét                     | assign a difficult task                  |
+--------------------------------------+------------------------------------------+
| kiadja a leckét                      | die / draw one's last breath             |
+--------------------------------------+------------------------------------------+
| megadja magát a sorsnak              | resign oneself to one's fate             |
+--------------------------------------+------------------------------------------+

## ÁLL {#sec-all}

|           |     |     |     |
|-----------|-----|-----|-----|
| átáll     |     |     |     |
| átáll     |     |     |     |
| átáll     |     |     |     |
| beáll     |     |     |     |
| beleáll   |     |     |     |
| eláll     |     |     |     |
| ellenáll  |     |     |     |
| feláll    |     |     |     |
| félreáll  |     |     |     |
| fennáll   |     |     |     |
| kiaáll    |     |     |     |
| körüáll   |     |     |     |
| leáll     |     |     |     |
| megáll    |     |     |     |
| rááll     |     |     |     |
| szemáll   |     |     |     |
| végigáll  |     |     |     |
| visszaáll |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |
|           |     |     |     |

## ÁLLÍT {#sec-állít}

|     |     |     |     |
|-----|-----|-----|-----|
|     |     |     |     |
|     |     |     |     |

## BESZÉL {#sec-beszél}

|     |     |     |     |
|-----|-----|-----|-----|
|     |     |     |     |
|     |     |     |     |

: [igezo-szotar](https://nyariegyetem.hu/tananyag/igezo-szotar-igekotos-igek-angol-megfelelokkel/)

It would seem that this looks very similar to a frame based approach to language modeling.

I wander if it can be used as a basis for template for generating a phrasal verb dictionary.

see also:

-   <https://www.hungarianpod101.com/blog/2020/10/05/hungarian-conjugations/>

    covers conjugation of Hungarian verbs

<!-- -->

-   <https://myhunlang.com/2010/04/01/phrasal-verbs-part-1/>

-   <https://myhunlang.com/2010/04/02/phrasal-verbs-part-2/>

    considers the strange case of meg-, el-, le- which add an aspect of completeness to a verb!? and when the prefix can replace the verb in a response.

-   <https://myhunlang.com/2010/04/02/phrasal-verbs-part-3/>

    explains when the verbal prefix can separate from and follow the verb

Here is some steps to automate construction of a hungarian phrasal lexicon I will call the prefix here a co-verb

1.  input verb, coverb

2.  estimate $\mathbb{E}(coverb), \mathbb{E}[verb] and \mathbb{E}(coverb,verb)$

3.  generate/lookup all conjugations for the verb

4.  add prefix all conjugations

5.  generates all conjugations for the verb

6.  count the $\mathbb{E}(coverb,verb,suffix)$ and infer from these the $\mathbb{E}(coverb,verb)$

7.  count the $\mathbb{E}(coverb,verb,suffix)$ and infer from these the $\mathbb{E}(coverb,verb)$\
    note that we might prefer to do this inference using all possible coverbs including the null coverb.

8.  estimate if $\mathbb{E}[coverb|verb] > 0$

9.  estimate if $\mathbb{E}[coverb|verb] \approx  \mathbb{E}[coverb]\times \mathbb{E}[verb]$ i.e. are the two morphemes independent indicating they are likely just concatenated

    if we have an inequality we could be looking at a collocation.

10. Next we should look at the sentence and identify nouns with case endings

    i.e. $\mathbb{E}[case|coverb,verb]$

    e.g. give something

    and $\mathbb{E}[case|case,coverb,verb]$\
    e.g. give something to someone

11. we should also look for evidence of specific uses i.e. when the prefixes and coverb are linked to specific words rather than cases

    i.e. and $\mathbb{E}[case|case,coverb,verb]$

    e.g. sell your soul to the devil\
    these collocations could be idioms, cliches or phrases.

    but in Hungarian with rich morphological settings and with flexible word order these probablities would be much harder to estimate or infer.

12. Also in general one might need to also consider if there are other lexemes participating (i.e. particles etc other than nouns as well as coverbs in isolated form.)

The challenge of course would be to establish that the phenomena is within confidence levels. For any given corpus size combining enough features (i.e. conditioning, quickly leads to sparsity which means it would be hard to find a threshold for a confidence interval separating real constructs from noise.

In [@Pajzs2002ACB] the authors only considered a few common verbs to work with

the main advantage for this approach might be that one would also have frequencies, possibly by year and thus be able to prioritize language learning tasks.
