
## POMDP

In this settings one or multiple senders only a partial state. 

Again we consider a hypothetical case where the state describe predators and that it can be partitioned into disjoint parts like <type, proximity> or <type, proximity, number> or <type, proximity, number, direction>. This partioning is also at the basis of compositionality in signaling systems.
 
Skyryms first considers three different settings.

1. **observation one of mutually exclusive partition:** the case where each sender views one part of the partitioned state.
2. **observation of all  mutually exclusive partition** the case where senders see all the parts of the state but don't have a mechanism in place to coordinate who sends which part of the state.
3. **observations of all mutually exclusive partition with coordination** the case where one sender see all the parts of the state but lacks symbols to send the full state and needs to send each part. He must send the parts one at a time resulting in a sequence of signals.

In the first settings the receiver somehow knows that he should first aggregate the signals using a logical and then decode the state.

In the first settings 


where the agent again observe the full state but don't have a a coordination mechanism for picking differnt parts of the message.


They send a partial signal to the receiver who must infer the state and take the appropriate action. The receiver must 

1. aggregate the messages
2. infer the state
3. take the appropriate action

note:


In the first case so long as each part of the state is a unique signal the state can be infered by the receiver using conjunction.
The second case if more problematic and shows us a new way that some signaling systems can be better then others. 

part the agent can't infer the state better then chance. However reinforcement of random partition the senders can learn to send  they both need to learn a decorelated partition for each state the state and send different parts of the state. The issues is if the semantics are composable.

- An issue here is that there is no guarantee that the senders will send the same part of the state at each turn. If the aggregation rules is conjunction, i.e. logical and, then the receiver will be able to decode the state so long as he gets all the pieces.

