
### The Bayesian view of the signaling systems

In this section let's consider a view of the Lewis signaling game in terms of a bayesian game theory. 
This is a perspective I used in a article on planning in the complex signaling game and helped me think more precisely about the 
how a signaling system might evolve in a formal setting.

The game has n states and n signals. Internality the a the agents will learn a permutation of the states and signals and its inversion. 
So there are n! signaling systems that can be learned. In the world of bayesian agents each such permutation characterizes an agent type.
THe game starts by nature picking a type for the agent. I say this this is because the agent needs to define a strategy which is a response for each state! Now the same is true for the receiver. The receiver's strategy is to pick an action for each signal. After that it can use bayesian updating to update it's belief about the type of the sender. These probabilities can guide it in the process of learning the signaling system. As the pair make progress, the receiver is able to update it's belief about the sender's type, discarding options that are inconsistent with the signals it has received! Once it has finds n-1 signals it can be certain about the sender's type and it will have an expected payoff of 1.