---
title: "Q1 2023 Tasks"
subtitle: "learning goals"
description: "Gabante learing challanges"
author: "Oren Bochman"
date: "2023-02-16T23:21:44.000-05:00"
draft: true
categories:
    - life long learning
    - python
    - git
    - making an effort
    - work ethic
    - deep work
---

# Python + Docker + Poetry

# ETLs 

# SQL Pandas parity

# Git

1. getting better at GIT 
    - a simulator ?
    - challanges ?
1. data generators
    - products category brands, season.
    - users + demand
    - events - 
    - competition.
1. time series
    1.1 go over 
        1.1.1 the data night material!
        1.2.2
    2. basics algs & and thier math
    3. make a small library for preprocessing and feature extraction
    4. make a baysian versions of the above models that model that does not care for missing or non uniform input
    5. fractal time suport.
2. spark/emr
3. s3 boto
4. snow flake etc
5. data version control
6. poetry
7. sagemaker
8. ec2 - jupyter in AWS on a spot
9. AWS programmatic
10. kubernetes & kubctl
11. use dev ops to orchestrate it all
12. step functions and lambadas
13. thinking in sql / pandas convertor
14. micro explorer
15. macro expolrer
16. multilevel in multiple environments
17. multilevel with complex data.
18. setting up python environments mac and linux
19. setting up python + cuda environmeints in docker.
1. reactive programming
1. obserble.js
1. manim 
1. animatoing mcmc algs
1. dashboards with python
1. snowflake/delta lake
