
---
title: logic puzzles
---


Solve this logic puzzle step by step:



A man was looking at a portrait. 
Someone asked him, 
"Whose picture are you looking at?" 
He replied: 
"Brothers and sisters have I none, but this man's father is my father's son."
Whose picture was the man looking at?


A man was looking at a portrait. Someone asked him, 
"Whose picture are you looking at?" 
He replied: 
"Brothers and sisters have I none, but this man's son is my father's son." 
Whose picture was the man looking at?

three dozen grey socks and 36 pink socks are lying in a drawer in a dark room. What is the minimum number of socks I must take out of the drawer which will guarantee that I have at least two socks of the same color?

A certain snail takes an hour and a half to crawl clockwise around a certain racetrack, yet when he crawls counter­ clockwise around that same racetrack it takes him only ninety minutes. Why this discrepancy?

If an airplane crashes right on the border of the United States and Canada, in which country would you bury the survivors?

A certain street contains 200 buildings. A sign-maker is called to number the houses from 7 to 207. He has to order numerals to do the job. Without using pencil and paper, can you figure out in your head how many 9' s he will need?
