---
date: 2024-00-24
title: "Sugarscape Ad Astra"
draft: true
---

I am realy enjoying reading Growing artifical societies.

As I process this amazing book, I want to
1. list some research questions.
2. make a draft outline of a hypothetical part 2.
3. add some coding ideas.

One of the most briliant aspect of the book is that reductionsit aproch the authors
used. Rules are kept as simple as possible. Hoever agent can use differnt rules and
they can be interactions.

However they interactions are not baked into the rules AFAIK - they are emergent?


## research questions

1. How can we make the Sugarscape avoid hard-coded rules? 
  1. Perhaps by formalizing the rules as games/MDPs with payoffs, any possible strategy pure or mixed could be assigned to the agents.
  2. the existing rule would become be specific strategy/policy  profile in its respective game.
  3. since policies are probabilistic mapping from states to actions, they be represented as square table whose rows are states and column are actions and the cells hold the probabilities, which should sum to 1 for each column.
    1. define a random strategy (assign same/different probability to all states)
    1. define simple mutations (reassign probability between transitions
    2. define a simple mitosis rule to 
    3. define a non robust variants
  1. RL agents might be initially assigned a random uniform strategy then optimize from it using a continuing task RL algorithm.
  1. Sugarscape is reductionist but typically three or more "rules" are described working in tandem.
     The serial nature of the rule's execution seems to mean that in each rule few choices are available. 
     - Movement lets you move one step. 
     - Harvesting is determined by location.
     - Metabolism is automatic.
     - Aging is automatic
     - Reproduction is automatic if conditions are right
     - Trade is also automatic - a once an agent picks a trader the alg will trade regardless of the other traders alternatives.
       If an agent is building rss for reproduction it will lose any resources it builds.
       What might help here is being able to switch utility.
     
    
  1. What if agents could also learn thier own rules for trade, combat, sex, communcation, bargaing, trade, government etc.
     This might be easier if rules become multi episode or contious games agent played and they could be assigned or aquire a strategy 
     [uniform-random,nash-equilibrium, ess, pareto-optimal, learned, a strategy] 
     this could also make them baysian players with the ability to respond to the **State of the World** (SOTW) and **Model of Other Agents** (MOA),
     1. what about games that are related.
          - we can compose games like move, harvest to get 
  1. Can we teach agents to evolve and communicate efficently.
     1. supoprt grammer 
     1. support injecting contexts?
     1. support for evolving error corection
  1. Can agents that learn from mistakes?
     Say by getting another life if it was very unlucky!? ^[but isn't bad luck the ugly face of natural selection!?]
     And how would that help. ^[e.g. start life with a better prior]
  1. How can we make agent explore/exploit thier action space. **Bandits**
  1. How can we make a differntiable utility/fitness/loss which we can differntitate to get intresting gradients
     
  
1. can we make SugarScape more realistic by adding additional rules. Like the original rules each should make a minimal change
1. can we make make the SugerScape grow increasingly more challanging over time?
  1. can we impose quantifiable selection pressure 
    1. can we make more commodeties and matching matabolism so that agents need to coordinate gathering and trades.
    1. can we make commodeties more scarce
    1. can we make agent need to specilize in roles to survive and thrive as a group.
  
  2. can we add predetors
  3. can we add calamaties like earthquakes, hurricanes, avalanches, sugar slides
  4. can we add differnt ecological regimes:
      1. make growback be based on a game of life ruleset. 
        1. Agents can overgraze and destroy thier habitat.
        1. Agriculture - Agents can learn to expand thier endowmant by seeding the nearby neighbourhood with glider like patterns that generate resource growth around them. This would allow them to follow the glider and harvest. This is perhaps a hybrid between agriculture and herding.
      1. agents can terraform thier habitat to increase the carying capaciry for thier species/culture metabolism and possibly hostile to thier enemies.
         with a risk that the world could also lose its carrying capacity. damaged ivable and couse extinction.
      1. polution requires cleanup work before one can harvest again.
      2. deforestation degrades food resuuply.
      3. polution leads to golbabl warming.
      3. polution leads to global cooling.that would disasters like global warming and green house effect that impact metabilism, deasease and resource growth
  5. can we make resource groth less predictable under 
1. can we force switching from regimes of cooperation, and competition.
1. can we make it a RL Gym and run different RL aglorithms. 
1. Culture seems to minimal. I see a culture rule that is a contrlller for other behavioral rules.
  1. 
1. More trading rules.
2. Expanding the economy by adding more commodeties. 
  a. some commodeties

can we add speciation:
  1. penealty on inbreeding - we add a recesive gene will reduce max age of the child
  2. success in sexual reproduction is proprtional to similarity of agents. (compatability)
  3. bigger map with different localities i.e. conditions for local genetic advantages to emrege.
  4. resistance to parasites and sickness through diversity. (they are transmittion and leathality are linked to genetic/cultural traits)
  
  - Consider representing traits with  sugar_metabolism_1 ... 5 if all are on you have a metabolism of 5
  - vision_1 ... 5 
  - foresight_1 ... 5
  
  - There are also immunity genes that give a permanent immunity, temporary immunity, partial_immunitry, carriar status, reduced risk.
  - each parasite and sickness can target genetic and or cultural traits. 
  - each trait is binary
  - same for culture
  - a second column makes the trait genetic/cultural
  - a third column makes the trait dominant or recessive,
  - parasites and sickness have a limited number or genes they can flip
    - parasites might turn on metabolism genes
    - sickness could be trnasmited on contact, proximity or during sex
    - blindness would eventually kill agents. 
  
changing prefernces:
  - change can be driven by sickness (e.g. loss of taste, smell, vison)
  - by scarcity 
  - by culture.
  

  
difffernet inheritance rules that are cultural/social in nature

give to the poorest
give to the poorest child
give to children but equaliznig thier waelth
give to a favourite (this can be arbitrary or can be via counter of proximity and or benefits in trade)


what if we change movement to 
1. bandit like explore explot
2. ad a prefernce towards better prices with respect to MRS - this can let agent with shor vision a hint of where goods are better distributed.




## Part 2

### Kinship rule
  - agent will be aware of relatedness of other agent. This will be a number 1,2,4,,8
  - 1 means they are identical twins, 2 means they are syblings, 4 for cousins, 8 for 
  - act more altuistically for closer genetic relatives

### Asexual reproduction comes to sugarscape.
  - agent with an asex_counter>0 can reproduce asxually - decremnting the counter, splitting resources and reducing thier age. 
    - splitting has a counter and the abilty is lost 
  - this can only be done a finite number of time. Thus if an agent with max age 100 can split 5 times. He can live till 5*50+50=300
  - at which point he will have 32 syblings all age 300 so he has lived 3600 year. In between he may have also reproduced sexually.
  - this makes all his progeny subject to inderitance rule.

### Haploid reproduction comes to sugarscape

  - kinship rules based on social insects are introduced here.
    - queens, sister-workers, warrior-males, etc
  - higher kinship should confer altruism in trade
  - higher kinshp should confer altruistic sharing of information.

### Specilization comes to Sugarscape.

  - each agent has either a probability of success or an output level associated with thier abilities.
  - agents who specilize can generate greater wealth and then trade for the missing commodeties.
  - agents can 

### Child rearing comes to Sugarscape

  - we start by adding progeny wealfare into an agents utility.
  - we could have an exponent payoffs for progeny that falls to a min on reaching puberty. 
  - we could add this to grandparents.
  - we could penalize ancestors whose children are out of vision.
  - ancestors can expand resources/time to nature their progeny/descendants.
    - 1. teaching them thier language by talking to them.
    - 2. bootstrap their priors by talking to them.
    - 3. bootstarp thier neural netwoks by transfering weights.
    - 4. agnet also impart thier culture to their progny as a side effect. (this couldis free)
      - This can be for free or at a costs to one of both sides
      
      
### Language comes to Sugarscape

  - agent can communicate
    - rss in their view
    - agent in their view
    - prices in their view
    - startegies
  - value of info = payoffs of action with info - payoffs of action without info
    - trading in information.
  - memory should have costs
  - 
  
  