---
title: "life hacks"
date: 2013-06-07
categories: [life, hacks, health, productivity]
---


Health and supplements:


1. taking care of the heart 
    1. exercise daily:
      1. at least walk 40 minutes a day ^[Ikigai - but try to get further each day in this time]. 
         This can help reduce visceral fat, which is the most dangerous fat.
      1. use a health tracker to monitor your daily steps and to prompt you to stand every hour you are awake for some minutes.^["sitting is the new smoking"]
      1. anything beyond 40 minutes should increase muscle mass, joint mobility or flexibility, idealy all three think TRX, yoga, pilates, or HIT with weight lifting, like certain les mills classes
      1. avoid risky activities that can set back your daily excessive routine. 
      1. HIT - make a habit to maximize the level of conditioning in the time alotted. 
      1. If you are sore from previous days workout, do a light workout for active recovery - pilates, streching or a walk.
      1. avoid high impact activities like running, jumping, punching, or kicking.
      1. try to activate the core muscles early in the day - it can save you from back pain and many other injuries.
      1. If you have cholesterol issues avoid hot saunas, hot tubs, and steam rooms - they cause arteries to expand and later to contract. Also cold water immersion can has a similar risk the colder the water.
      
    2. eat 1/2 cup of yogurt a day
    1. eat 5 walnuts a day
2. taking care of the kidneys
    1. drink 2 liters of water a day
    2. by reduce intake of sugar and carbs you can boost kidney capacity to clean up the blood.
    3. consume 10 cranberries a day
3. taking care of the digestive systems
    1. eat fiber rich cereal in the morning (fiber one) but at the recommended serving size (1/2 cup)
    1. eat 1/2 cup of yogurt a day
    1. try to drink fiber supplements once a day
    1. after consuming fiber take a probiotic supplement, these digest fiber so best to take them after fiber
4. taking care of your joints by controlling purene rich foods
    1. Activity
      1. avoid impact sports
      1. avoid jumping down from heights - this can damage your knees.
      1. don't rush down stairs
      1. alpine stick can help with balance and reduce the impact on the knees when walking outdoors in uneven 
         terrain.
      1. stretching and yoga can help with flexibility and joint mobility.
      1. certain body weight drills like:
        1. sitting on the stability ball
        2. walking up/down 3 flights of stairs
        3. horse stance 
        4. half moon pose etc can help fix specific joint issues.
      1. using a foam roller or a massage stick can help improve joint health.
      1. preventing injuries however is more salient than treating them.
        1. Yoga has many benefits but also many risks, these are rarely discussed.
          Many yoga benefits are experienced in the short term but the risks if incurred
          can be long term. For example:
           1. headstands can be high risk for the neck if done wrong.
           1. shoulder stands are fine if weight is on the shoulders by risky if 
             weight is put on the [neck](https://www.yogajournal.com/teach/protect-the-neck-in-shoulderstand/). 
             - Can you be sure you will never turn your head to the side?
             - Shoulder stands variations like hallasana, or plow pose, put more weight on the neck
             then the shoulder stand itself. Without good mobility in the entire spine,
             the weight of the body can easily damage the cartilage in the neck.
            Both have health benefits and can be done safely many times without injury.
            But it only takes one accident  to cause a long term injury to the neck.
            Also some damage to the neck may be cumulative and not felt until years later.
            As we age the cartilage in the neck becomes less elastic and more prone to damage.
            If the weight is put on the neck particularly in the headstand, where 
            the spinal column has a radius of 2 cm, the weight of the body can 
            easily damage the cartilage in the neck. Crush the nerves in the neck
            etc. My wisest yoga instructor put it succinctly "these asanas are the 
            bread and butter for chiropractors".
          There are many other risky asanas in yoga and it is wise to know these risks.
          In my experience with the other asanas knowing the risks alleviates 
          most of the danger.
      1. spinning classes are some of the worst activities for the knees.
      1. cycling on the other hand has many benefits including the knees, legs, and the glutes.
      1. although I recommend walking - lower impact alternatives like swimming, rowing, and cycling and 
      the elliptical machine are better. If you switch between these activities 
      on a weekly basis that would boost the benefits by avoiding overuse injuries as well as adapting of
      different muscle groups to the activity. Again the same rule - try to get more milage in the same time,
      rather than increasing the time. 
    2. Nutrition
      1. avoid red meat
      2. avoid red wine and beer and sugary drinks
      3. consider drinking sugar free cranberry juice.
      4. losing weight is a long term strategy to improve joint health.
        1. it reduces the load on the joints.
        2. it reduces the inflammation in the body.
        3. it reduces load on kidneys which can help clean up the blood better and avoid gout.
        4. and quick loss of fat can trigger gout attacks, kidney stones, and release any toxins stored in the fat.
           so it is much smarter to lose weight slowly. Also rapid weight loss means 50%+ muscle loss.
           This is not a smart strategy as rebuilding muscle is much harder than losing fat and creates a lot of
           stress on the joints.
           Idealy, you want to lose .5 kg a week, no more. That's tricky to track 
           because of the daily fluctuations in weight. Its better in many ways to
           try to perfect you dietry routines and let the weight loss happen naturally.
           You could monitor your weight daily but only take the weekly average as the real weight.
           Use this moving average for guidamce how effective your routine is working.
      5. joint supplement like glucosamine and chondroitin have not had any success for me
      

::: callout-tip
  
eating breakfast of:
  
- 1/2 cup of fiber one
- 1/2 cup of yogurt
- 5 walnuts
- 10 cranberries
- minimal pro-biotic yogurt drink (like Yakult)

isn't just a good way to stat the day but also helps take care of several goals at once.
    
:::


