---
title: Rhetoric Bibliography
bibliography: refrences.bib
citation-location: document
---

## Textbooks:

[@corbett1999classical], 
[@engell1999committed], 
[@torricelli2000in], 
[@lucas2002art],
[@farrell1993norms]

## Part I: The Nature of Rhetoric / A Long Struggle

- Nature and Purposes of Rhetoric; Original Five Canons; Three Kinds of Persuasive Discourse; Importance of Rhetoric Today [@CRMS p15-26]
- Isaac Backus, Speech to Massachusetts Constitutional Convention [from "Mr. President, I have said very little" to "any people upon earth."]
- Frederick Douglass, Fifth of July Oration
- Caleb Bingham, from The Columbian Orator
- David Blight, Editor’s Introduction to The Columbian Orator, “The Peculiar Dialogue Between Caleb Bingham and Frederick Douglass”
- James Engell, from The Committed Word: Literature and Public Values, ch. 1, “The Committed Word”
- Henry Clay on Slavery and Abolition
- Abraham Lincoln, “A House Divided”
- Douglas Wilson, from Honor's Voice, The Transformation of Abraham Lincoln
- W.E.B. DuBois on “The Battle for Humanity” [@IOOW p17-20]
- Thurgood Marshall, from Brown v. Board of Education [@IOOW p198-99]
- John Quincy Adams, from Lectures on Rhetoric and Oratory, Inaugural Oration; Lecture I, “General View of Rhetoric and Oratory”
- Martin Luther King, Jr., “Letter from Birmingham Jail” [@CRMS p301-14] with analysis of arrangements [@CRMS p315-19], and analysis of style by Richard P. Fulkerson [@CRMS p478-83]
- King, Call to End Segregation--“I have a dream...” [@IOOW p234-37]
- Thomas B. Farrell, An Ethically and Aesthetically Significant Art from Norms of Rhetorical Culture, hereafter "Norms." Optional but encouraged.
- Lyndon Johnson, Address to Congress, Voting Rights Act of 1965 [@IOOW p259-65]



## Part II: Thesis, Invention, Persuasion, Topics / Shaping the Republic

- The Thesis; Three Modes of Persuasion: logos, pathos, ethos [@CRMS p27-84; @APS p325-346, p142-159]
- “Looking for an Argument” [@CRMS p130-37; @APS p82-93]
- George Campbell, from The Philosophy of Rhetoric, 1, i, I, “Eloquence”
- Delivery of Speeches [@APS p67-71, p239-252]
- Patrick Henry, Speech in Virginia Convention of Delegates
- Thomas Paine, from Common Sense
- Bernard Bailyn, from The Ideological Origins of the American Revolution, ch. 1, “The Literature of Revolution”
- Alan Heimert, from Religion and the American Mind
- Declaration of Independence
- Pauline Maier, from American Scripture: Making the Declaration of Independence
- Aristotle, from Rhetoric
- Rhetoric as ethical practice [@APS p30-40; @Norms p61-83] Optional
- Alexander Hamilton, Federalist No. 1
- Madison, Federalist No. 10 [@CRMS p214-20] and analysis by Mark Ashin [220-30]
- James Madison, Federalist No. 37
- Henry, against the Constitution, Virginia Ratifying Convention
- Madison, for the Constitution, Virginia Ratifying Convention

## Part III Topics / Foreign Affairs

- Topics [@CRMS p84-120; also p209-14, Part V below]
- Special Topics [@CRMS p120-30]
- Woodrow Wilson Requests Declaration of War [@IOOW p37-39]
- F.D. Roosevelt on the “four freedoms” [@IOOW p120-23]
- - J.F. Kennedy, “Ich bin ein Berliner” [@IOOW p232-33]
- J.Q. Adams, from Lecture II, “Eloquence Considered”
- Shen Tong on Tiananmen Square [@IOOW p385-88]
- Elizabeth Linder and Connie Mack, Congressional Hearing [@Norms p304-08]
- Rhetoric as a particular practice of civic virtue [@Norms p93-100] Optional

## Part IV Designing Arguments / Justice, Social Choice

- Arrangement [Organization] and Parts [@CRMS p256-92, @APS p165-180, p185-203]
- Rose Schneiderman on Triangle Shirtwaist Fire [@IOOW p32-33]
- Al Smith Assails William Randolph Hearst [@IOOW p57-58]
- John L. Lewis on “Brutality and Oppression” of Big Business [@IOOW p112-14]
- Susan B. Anthony on Women’s Rights before a Congressional Committee
- Phyllis Schlafly Opposes Women’s Rights Movement [@IOOW p329-35]
- Hugh Blair, from Lectures on Rhetoric and Belles Lettres, Parts of a Discourse
- Margaret Sanger Promotes Birth Control [@IOOW p68-70]
- Sarah Weddington, from Roe v. Wade [@IOOW p302-04]
- Mario Cuomo on abortion, an analysis [@Norms p213-24]
- J.Q. Adams, from Lecture XI, “Deliberative Oratory”
- George Campbell, from 1, i, V, “Of Intuitive and Deductive Evidence”
- Clarence Darrow on sentencing of Leopold and Loeb [@IOOW p76-78]
- Sarah Brady on Gun Control [@IOOW p424-26]
- Charlton Heston on Second Amendment Rights [@IOOW p426-31]
- J. Robert Oppenheimer on Morality and Science [@IOOW p151-53]
- Rachel Carson on “Exceeding Beauty of the Earth” [@IOOW p202-05]
- Carson, “The Obligation to Endure” from Silent Spring [@CRMS p185-90] and topical analysis [@CRMS p190-95]

## Part V Style & Emphasis / Praise and Remembrance

- Style [@CRMS 337-69, 478-83; @APS 221-227]; review Delivery [@APS p67-71, p239-252]
- Jane Addams, Address to Union League Club on George Washington [@IOOW p8-11]
- Carl Sandburg, from Address to Congress on Abraham Lincoln [@IOOW p212-15]
- Martin Luther King, Jr., on Four Martyred Girls [@IOOW p237-39]
- J.Q. Adams, from Lecture XXVI, “Perspicuity”
- George Campbell, 1, ii, VI, “Of Perspicuity”
- The New Yorker Obituary for Katherine Sergeant White [@CRMS p209-11] and analysis of the topics in the obituary [@CRMS p211-14]
- Thomas Sheridan, from Elocution
- “Tragedy as Eulogy,” Edward Kennedy on John Kennedy [@Norms p118-34] Optional
- Jay Heinrichs, “How Harvard Destroyed Rhetoric” in Harvard Magazine

## Part VI Who speaks? / Political Debate, Controversy

- Benjamin Franklin, Speech at the Constitutional Convention
- George Washington, from Farewell Address
- J.Q. Adams, from Lecture XV, “Qualities of an Orator”
- Joseph McCarthy, from a speech to honor Lincoln [@IOOW p173-76]
- Margaret Chase Smith, against hate and fear as political tactics [@IOOW p176-79]
- “Rhetoric in the Army-McCarthy Hearings” [@Norms p39-47]
- Amy Gutmann, “The Lure & Dangers of Extremist Rhetoric”
- Dwight Eisenhower, from Farewell Address [@IOOW p219-21]
- Shirley Chisholm, on Government Spending [@IOOW p279-82]
- Barry Goldwater, accepting 1964 nomination [@IOOW p249-52]
- Barbara Jordan, 1973 Impeachment of Richard Nixon [@IOOW p312-16]
- Ronald Reagan, “Make America Great Again,” from speech accepting 1980 nomination [@IOOW p341-45]
- Mario Cuomo, from 1984 convention speech [@IOOW 354-59]
- Elie Wiesel to Reagan on planned visit to Bitburg Cemetery [@IOOW p363-66]
- The example of Bitburg, analysis [@Norms p291-93]

## Part VII Figures & Metaphor / The Poetic and Our Polity 

- Figures of Speech; the Value of Imitation, [@CRMS p377-448; @APS p227-232]
- Daniel Webster, from Eulogy on Adams and Jefferson, their Literary Character and Eloquence
- William Faulkner, Nobel Prize Acceptance Speech [@IOOW p179-80]
- John Kennedy, tribute to Robert Frost [@IOOW 242-44]
- Isaac Bashevis Singer, Nobel Prize Acceptance Speech [@IOOW 327-29]

## Part VIII A Brief History / Inaugurating Hope

- FDR, First Inaugural Address [@IOOW 99-102] and analysis [@Norms 83-93]
- JFK, Inaugural Address [@CRMS 459-61] and analysis [@CRMS 461-72]
- Lincoln, Second Inaugural Address
- David Zarefsky, “Approaching Lincoln’s Second Inaugural Address”
-“A Survey of Rhetoric” [@CRMS 489-543]

## Part IX Study & Commitment / Remarks at a Dedication

- Engell, from The Committed Word, ch. 9, “Lincoln's Language, and Ours,” and ch. 10, “Recommitment”
- Lincoln, Gettysburg Address
- William Barton, from Lincoln at Gettysburg

### References

::: {#refs}
:::