---
title: igezo-szotar
---

||||
|---|---|--|--|
|[ad](#sec-ad)|[áll](#sec-all)|[állít](#sec-állít) |[beszél](#sec-beszél)|
|bújik   |csap   |csíp   |csúszik|
|dob     |dől    |enged  |esik |
|eszik   |ég     |él     |épít
|ér      |fekszik|fér    |fizet|
|fog     |folyik |fordít |fordul |
|forgat  |fúj    |fut.   |gondol |
|hagy    |hajt   |hív    |hoz |
|húz     |ismer  |ír     |jár |
|játszik |jön    |jut.   |kap |
|kapcsol |kel    |ken    |kér |
|kerül   |köt    |lát    |lép |
|lő      |marad  |megy   |mér |
|mond    |mos    |mutat. |néz |
|nyom    |nyújt  |olvas  |szt |
|pakol   |ragad  |rak    |ráz |
|szakad  |száll  |szalad |szárnít|
|számol  |szed   |szorít |szorul|
|szól    |szúr   |talál  |tanul.|
|tart    |tesz   |telik  |tér   |
|tölt    |tör    |törik  |tűz   |
|ugrik   |ül     |üt.    |vág   |
|választ.| válik |vált   |vesz  |
|ver     |vet    |vezet  |visz  |
|von     |vonul  |zár    |



## AD {#sec-ad}

|   |      |     |   |
|---|------|-----|---|
|átad
|    |átad vkinek vmit            | hand over sth to sy|
|    |átadja a szot vkinek        | call upon sy to speak|
|    |átadja az üdvözletet vkinek | convey sy's be st wishes to sy, say hello to sy for sy|
|    |átadja a helyét vkinek      | give up one's seat to sy|
|bead|                           
|    |beadja a gyógyszert vkinek  | administer medicine to sy|
|    |beadja a kérvényt vhová     | submit / present a request; file a petition|
|    |beadja a felmondását        | hand in one' s notice |
|elad
|    |elad vmit vmennyiért        | sell sth for sth|
|előad
|    |előad vmit                  | perform, enact, recite etc. sth|
|    |előad                       | lecture|
|felad
|    |felad (pl. levelet, csomagot)|post (e.g. a letter, a parcel)|
|    |feladja a kabátot vkire     | help sy on with their coat|
|    |feladja a leckét            | assign homework|
|hozzáad
|    |hozzáad vmihez vmit         | add sth to sth|
|    |hozzáad vkihez vkit         | marry sy off|
|idead
|    |idead vmit                  | give sth to me|
|kiad
|    |kiad egy könyvet            | publish a book|
|    |kiad egy szobát / egy lakást| rent a room / a house|
|    |kiadja a munkát vkinek      | distribute work|
|    |kiadja a mérgét / dühét     | vent one's rage|
|lead
|    |lead vmit vhol              | leave sth swhere, hand sth in|
|    |lead vmennyit               | lose weight|
|megad
|    |megadja az adósságát        | pay off one's debts|
