---
title: Fantasy Bayesian Course Catalog
---

There are no additional courses in the specialization at this time!
However if I was asked what I wanted to learn next I would probably think of the following
Idealy finding an online video course on any of these topics would be great.

Also it would be of some interest to make my own quizzes based on R shiny and quizzez from non coursera sources, like books or examss.

1. We focused on old MCMC methods in this specialization. 
    - There are new methods like 
    - HMC: Hamiltonian Monte Carlo. - I have material on this ready
    - NUTS: No U-Turn Sampler. - I have material on this ready
    - SMC: Sequential Monte Carlo. 
    - Criss Fossenback videos 
1. GP: Gaussian Processes for Machine Learning.
    - [Ti John | Introduction to Gaussian processes](https://www.youtube.com/watch?v=aQrHZm-D6FA)
    - [Scalable Gaussian processes](https://www.youtube.com/watch?v=I9VZWIxSGUs)
    - [CS-E4895 - Gaussian Processes](https://mycourses.aalto.fi/course/view.php?id=36657) this is an actual course based on 
    - Rasmussen & Williams book 
        - [online](https://gaussianprocess.org/gpml/chapters)
        - [Chris Williams: Selected talks available online](https://homepages.inf.ed.ac.uk/ckiw/mypages/talks.html)
        - [Carl Rasmussen's lectures](https://videolectures.net/lecturer/6508/?sort=lectures_most_viewed)
    - [Machine learning - Introduction to Gaussian processes](https://www.youtube.com/watch?v=4vGiHC35j9s)
    - [ML Tutorial: Gaussian Processes (Richard Turner)](https://www.youtube.com/watch?v=92-98SYOdlY)
    - [Gaussian Process Summer School](https://www.youtube.com/@gaussianprocesssummerschoo7738)
    1. GP-LVM: Gaussian Process Latent Variable Model.
1. Causal Inference using Judea Pearl's Do-Calculus and Casual Graphs - 
    - Might be possible using PYMC or    
    - Theory is in McElreath's book
    - Missing data imputation using causal inference
    - https://matheusfacure.github.io/python-causality-handbook/landing-page.html
    - https://www.hsph.harvard.edu/miguel-hernan/causal-inference-book/ - potential outcomes framework
    - https://www.mostlyharmlesseconometrics.com/
    - python
        - causalinference
        - CausalPy
1. SMC: Sequential Monte Carlo Methods.
1. Markov Random Fields.
1. Normalizing Flows.
1. Variational Inference and Variational Autoencoders.
1. Bayesian Networks. 
1. Bayesian Neural Networks.
1. Bayesian Optimization.
1. Time Series Analysis for Vector data - covered in Prado's book.
1. Time Series Analysis for multiple resolution data (course and fine grained data) in a single model - covered in herbert lee's book.
1. Copulas
1. Anything not covered already in Bayesian Methods for Hackers,


although I cannot create another course to cover these additional topics, I can probably collect some good resources like papers or note books on each of these topics and drop them here.



