---
title: "RL, Metamorphosis and Memory"
date: 2025-03-31
draft: true
---

> "Of what a strange nature is knowledge! It clings to the mind, when it has once seized on it, like a lichen on the rock. I wished sometimes to shake off all thought and feeling; but I learned that there was but one means to overcome the sensation of pain, and that was death" 
>  --- Mary Shelley, *Frankenstein*


The idea of metamorphosis is that agents may undergo a transformation from one form into radically different forms throughout its life time. i.e. for different MDPs the agents mind and body undergo massive rearrangement. In nature it seems such a process does not work with blank slates as agents seem to retain some of their memories, possibly as priors for later inductive biases. Without considering the general case, an agent might gain benefit if it could retain a record of previous knowledge (e.g. states of the world) and the ability to coordinate and communicate with other agents it has spent considerable resources to develop a signaling system. This suggests one should investigate imbuing agents with inductive bias for a meta-protocol related to metamorphosis. E.g. One that allows to store knowledge, together with a lexicon etc to access knowledge from many generations ago. think ^[self-decompressing file of memory]
