---
date: 2024-02-22
title: "Text to IPA"
categories: [nlp, bash tip,IPA]
draft: true
---



One of the easiest ways to test NLP systens is to listen to its output.

Of course the platonic in me would like to imagine a perfect world in which the TTS component is 
mature and wont inject additional issues into the system.

IPA is the international phonetic alphabet. 

Why don't we use it more - we don't have quick and loop to convert text to IPA
and to fix any IPA annotation issues.

what is an IPA issue

the word **read** can be pronounced differently depending on the tense, these pronunciations are “rēd”, for the present tense and “rĕd” for the past tense and past participle form.

clearly the TTS system would need in this case to disambiguate between the two using the context a preprocessing step might annotate the words as `red`` `red`


1 read read VERB ??? Tense=Past
1 read read VERB ??? Tense=Past


anyhow the main point is that we convert text to IPA using espeak-ng

```{bash}
espeak-ng -v mb-en1 "Hello World Thanks you very much" --ipa
```

A second point is that we can also add user dictionary with entries for words with missing pronunciations.

Q1. can we preprocess the text to discover missing pronunciations
Q2. can we use an LLM or a web based tool to look up as many of these as possible
Q3. can we train a transducer type transformer to convert the rest!





