---
title: "Pricing Theory"
format: html
fig-cap-location: margin
reference-location: margin
footnote-location: margin
---

# Introduction to Pricing Theory

When it comes to pricing there are a number of pricing strategies ^[**pricing strategies**] that can be used. These include:

Yield management (YM) 
:   Proﬁt maximization ^[Proﬁt maximization strategy] and mean proﬁt management.

Revenue management (RM)
:   Revenue maximization ^[Revenue maximization strategy] and mean revenue management.

## Service Definitions

Nonstorability
:   Services are time dependent. Service providers cannot transfer unused capacity
from one service date to another. ^[sellers my try to avoid this e.g. Some charter ﬂights.]

Advance purchase/booking
:     Purchase date can be different from service delivery date. ^[capacity utilization level can increase profits]

  - Early booking without ability to cancel is a commitment by the consumer to use the service.

Cancellations
:     Consumers who book in advance may not show up and may even cancel their reservation. Service providers should be able to segment the market according to how much refund (if any) is given upon no-shows.

Service classes
:     The service can be provided in different quality classes. Market segmentation is proﬁtable whenever the difference in price between, say, ﬁrst and second class exceeds the difference in marginal costs.

Questions 

-  Why travelers sitting in the same economy class on the same ﬂight pay different airfares. Why people who stay at identical hotel room sizes end up paying different prices.
  - This is because passengers pay near their maximum willingness to pay and as long as
consumers are heterogeneous in this respect, use of price discrimination results in having people paying different prices for what appears to be an identical service. 
-  Why capacity underutilization is often observed, such as empty seats on an aircraft and vacant hotel rooms. ^[**Seller's commitment problem**]
  - This is due to service providers which by seeking to maximize proﬁt, will prefer to reserve some  capacity in case consumers with high willingness to pay show up at the last minute.
  - Last  minute sales hurts seller reputation and will lead to avoid making early commitments.


- Rule for sellers: Make an effort to set the price according to buyers’ value and not according to cost.
- Rule for buyers: Bargain, if you can, for prices closer to marginal cost.


We will generally assume that sellers know the consumers’ value and willingness to pay for the services and products they sell. 
By this I mean that sellers know the distribution of the willingness to pay among different consumer groups. 

If sellers lack this information, they can use market surveys^[Market surveys are less reliable]

If the seller is a **monopolist**, the seller can set the price according to the consumers’ willingness to pay.
Otherwise, the seller faces competition from other ﬁrms and the consumers may base their willingness to pay on the prices
charged by the competing ﬁrms, i.e. there may be a reference value for the product or service.


$$
\begin{aligned}
\text{Brand Value } &= \text{Reference value} \\ &+ \text{"Positive" differentiation values} \\&− \text{"Negative" differentiation values}
\end{aligned}
$$

Switching costs
: If the seller is an established ﬁrm with a large number of returning customers, the seller can add to the price the cost consumers would pay to switch to a competing brand. 
:  If the seller is a new entrant, the seller may want to reduce the price to subsidize consumer switching costs; ^[**penetration pricing strategy**].

Essential input
: Sellers can augment the price in cases in which the product/service serves as an essential input to goods and services produced by buyers. Some economists refer to this type of action as the “holdup problem.”

Location costs
: When reference prices are used, the cost of shipping or the location of the service should be reﬂected in the price, or shared by the parties.

## Overview of Pricing Techniques

Economic theory suggest that in economies of scale with perfect competition, prices should be equal to marginal costs. ^[cost based pricing strategy]. 
In practice, prices are usually not set according to costs. Sellers try to get different buyers to pay different prices for the same product or service.
