---
title: The Operational Transformation of Data Architecture
subtitle: The Language of AI 
date: 2026-04-28
keywords: [Data Architecture, AI Language, Symbolic Reasoning, Neural Computation]
categories: [odsc]
description:  A deep dive into Andy Petrella's talk on <br> the operational transformation of data architecture, <br> exploring the unification of symbolic reasoning and neural computation in a single language for AI.
---

## The Operational Transformation of Data Architecture {#sec-the-operational-transformation-of-data-architecture}

::: {.column-margin}
{{< video https://vimeo.com/1189303977 >}}
:::

- Andy Petrella
  - [LI](https://www.linkedin.com/in/andypetrella/)
  - [GitHub](https://github.com/andypetrella)
  - Book:
    - [Fundamentals of Data Observability](https://www.oreilly.com/library/view/fundamentals-of-data/9781098133283/)
  - NextLab SRL

::: {.callout-note collapse="false"}
### Notes

- [DataBricks](https://databricks.com/) - a unified data analytics platform that provides tools for data engineering, data science, and machine learning.
- [dc43](https://dc43.com/) - a data catalog and data governance platform built on top of the Model Context Protocol (MCP) to help organizations manage and govern their data assets in the age of AI.
    - Governance layer
    - Services layer
    - Integration layer
    - Execution layer
- [collibra](https://www.collibra.com/) - a data intelligence company that provides a cross-organizational data governance platform.
- [apache spark](https://spark.apache.org/) - an open-source unified analytics engine for large-scale data processing, with built-in modules for streaming, SQL, machine learning and graph processing.
- [databricks DLT](https://databricks.com/product/delta-lake) - a storage layer that brings reliability to data lakes. It provides ACID transactions, scalable metadata handling, and unifies streaming and batch data processing.
:::

