---
title: Analytics Checklist
date: 2015-02-07
catagories: ["analytics","checklists"]
---

# Design 

- [ ] Desktop Design 
- [ ] Laptop Design 
- [ ] Tablet Design 
- [ ] Mobile Design 
- [ ] Mobile Opened Menu 
- [ ] Exit Popup Design 
- [ ] Validation Error Design 

# Input:

- [ ] Text 
- [ ] Thank you message 
- [ ] SVG Icons 
- [ ] Favicon 
- [ ] Technology 
- [ ] Hosting 
- [ ] SSL 
- [ ] CRM Integration 
- [ ] 3rd Party Integration 
- [ ] API Integration 
- [ ] Meta Tags 
- [ ] Scripts & Pixels 
- [ ] Validation Rules 
- [ ] Mobile Click to Call 
- [ ] Lead Generation 
- [ ] Lead Backup 
- [ ] Thank you message Showoff 
- [ ] Page load time 
- [ ] Optimization 
- [ ] Brading Logo 
- [ ] Privacy Policy 
- [ ] Disclaimer 
- [ ] Meta Tags 
- [ ] Title 
- [ ] Description 
- [ ] Keywords  
- [ ] Favicon 
- [ ] Form 
- [ ] Input 
- [ ] Input Hebrew Placeholder  
- [ ] Required  
- [ ] Validation  

# Special Integration 

- [ ] 3rd Party Integration  
- [ ] Comments 
- [ ] Scripts & Pixels 
- [ ] Google Tag Manager 
- [ ] Google Analytics 
- [ ] Google Remarketing 
- [ ] Google Conversion 
- [ ] Facebook Remarketing 
- [ ] Facebook Conversion 
- [ ] Facebook Registration 
- [ ] Dbm Remarketing (pageview) 
- [ ] Dbm Conversion 
- [ ] Dbm Registration 
- [ ] Outbrain Remarketing (pageview) 
- [ ] Outbrain Conversion 
- [ ] Outbrain Registration 
- [ ] Taboola Remarketing (pageview) 
- [ ] Taboola Conversion 
- [ ] Taboola Registration 