---
title: "Generating Movies"
date: 2026-01-09
---

First I'd like to consider a conceptual framework for a REPL (read eval print loop) for generating videos and or animations via generative AI.

Two motivating observations to get us started.

1. Knitting Advice 

   If you ask for knitting advice from an LLM it is likely to give you very poor advice as reading about knitting is very different from experiencing knitting. Absent a mechanism to ground the LLM in experience it is very unlikely prefer giving out useful advice.

2. Cooking with Novel Recipes

   Similarly cooking is a very experiential activity. LLMs have seen thousands of cookbooks but have never cooked or tasted a meal. Real cooks know that getting a dish right requires many minutiae that are not captured in a recipe book. These range from knowledge of techniques, sourcing ingredients, timing, understanding and accounting for idiosyncrasies of the cooking environment etc. The LLM might know much about any one of these but lacks the ability to integrate them in a useful way and also the designers tend to have a cavalier attitude to accuracy and truthfulness in recipes.

   While one can envision a LL or a recsys to generate novel recipes it is hard to see what data it could use for what doen't work, isn't sanitary, nutrsious, healthy, or tastes bad. If we had a chef robout that could cook and taste food and its texture etc getting feed back or immitating human chefs might be a way to ground the LLM in experience. However barring this it is hard to see how a LLM could learn to be realy useful for giving cooking knitting advice.

Thus we understand that in many domains LLMs are likely to be of limited use unless one can come up with a good way to ground them in experience. For simple tasks where judment is common sense this may not be a big issue. However as domains get more complex and nuanced that we are not in a simple classification regression settings we are more and more likely to run into problems. These range from out of distribution errors, to inability to capture or manupulate stucture or hierarchies.

With large models such abilities might emerge to some degree. However this likely requries that the structure is readily observable and that the model has seen enough examples to learn both the structure and how to manupulate it. 

4. Universal Function Approximators - We learn the Deep neural networks are universal function approximators. However being able to approximate any function is not the same as such a function emerging just by seeing many examples of random inputs and outputs. Techniques like dropout force Deep networks to learn more robust representations. However they are notorious for finding the simplest path to minimizing training error rather than approximate a the function for "general purpose reasoing". Just like wikipedia is greats at quickly fixing an error once it is pointed out, Supervised learning is great at acing new tests once these are provided and there are lots of people working on new datasets that can be used to get further train a model. However it is not very likely that a model that is pretty good at solving chess problems will also be good are chess openings (though there might be some transfer) Its even less likely that it can generalize to backgammon, go or poker. Even if it can play games can it code or solve math olympiads problems. Anyhow I don't think that these wont give us more and more general purpose reasoning abilities but rather that many areas will never get enough high level data for the models to learn to generalize well unless one goes out of ones way to provide data and training regimes that force the model to learn the desired structures.

By forcing the model to learn the structure of the 

4. Story Generation - In the case of stories LLMs may be trained on millions of books. However while they can quickly learn how to put words into grammatically correct sentences and paragraphs, it is less likely that they can infer the deeper structure of stories, character development, plot arcs, world construction etc.

For each million words of texts the model may only see a few stories and it does not get a data set for organzine these into acts, scenes, sequences, character arcs etc. If we also give it a few dozen books on story writing it will easly learn to displense advice on story writing but is 

5. Video Generation - Generating videos is even more complex. In many ways a movie is not much more complicated than it screenplay. Sure there is expertise in cinematography, lighting, sound design, acting editing etc. One might assume these are about as complex as story writing. However in terms of data a movie is much bigger than if one would write all these instructions given to the cast and crew for a movie. I.e. we might give each of them a small note book to augment the screenplay with instructions on how to do their job. 

The movie itself captures the real world. It possible that certain algorithms might learn to capture physics of the real world to some degree. However recovering the screenplay from a video is the kind 
of inverse problem that is is likely to be very ill posed. Clip models tend to describe images and videos in great precision but they tend to be very different from how viewers describe them. Compressed sensing might allow computers to recover some of the structure of the real world from videos but the big problems is that high level structure are sparse you get one per videos or book and they are very much like snow flakes - each one is more different than similar to any other one.

Story structure is not all that complicated but it tends to come in a multilevel hierarchy that requires something like EM to learn  - i.e. we need to cluster the right constituents at one level to learn the next level structures. Even if you learn about mythic structure it might not be very useful for a kung fu movie or a rom com.





Paradigms of generative AI


1. REPL 
   - similar to coding in a notebook
   - user provides high level instructions or specs
   - gen ai agent generates a video or animation
   - user reviews and provides feedback
   - gen ai agent refines the video based on feedback
   - loop continues until user is satisfied with the result
1. **Hybrid Networks**
   - RL\Supervised ML\Adversarial networks\Bayesian Models\CLIPS\Diffusion models\Transformers\LLMs
   - LLM type models are froze after training - fe
   ed back is a means to exploring paths though latent space that approximate user desires. can be fine if the model is trained on suitable data. Otherwise may fail, or be very fustrating to use. (We are navingring using an auto pilot but our trael guide is 20 years out of date)
   - CLIP lets us ground the LLM like models in images and videos - this is very helpful for guiding the generation process. One images though adding additional grounding using new modalities like (ControlNets, MasterShots, Functions etc. )
   - RL agents facillite a more dynamic interaction - they can learn from user feedback and adapt over time however they often require a lot of training data and time to learn effectively particularly when under the hood is something approximating a LLM. (e.g. a large feed forward net with attention layers etc or a RNN/Transformer ) Here CLIP like priors with specific knowledge would be very helpful.
      - RL models tend to have lower capacity than LLMs
   - Underlaying models should be defined as non-parametric models and these learned via supervised learning from large datasets. These can be used with updating or as starting points for the more powerful ML techniques to power the RL agents.
  
   - Idealy the LLM would work as a prior for the RL agent but feed back 
1. **SpecGen Copilot paradigm** 

   - We want to have a model that can do guess what we want based on a large body of work that it has seen. However we also want to be able to provide it with hints and feedback to let it know what we want incrementally. The model should also be able to handle complex structured detailed specs that are built hierarchically. This happens because it either seen many such specs in its training data or because it can break down the spec into smaller more manageable chunks that again are familiar from training.
   - Spec\Gen - the ability to specify thing precisely using a structured spec or to provide a high level spec.
      - Spec is high level and structured - e.g. a story outline, a shot list, a scene list, a character list etc.
      - Low level like bits, detailed animation might be curated rather than specified in detail
   - Copilot and have gen AI agent step in and fill in the details and then provide it with hints and feedback to get to the desired result.
1. **Garden of intersecting paths** - the story can be generated using a MDP (Markov decision process) grounded in the hero's journey + genere conventions (within a spec) 

   - create an mdp for the hero's journey
   - adjust the transition probabilities based on genre conventions
   - generate a story outline
   - the state space might be broken into sub-states <three act structure, hero's journey, sequence spine, scene, master shot, bit >
   - these might be independent or not.
   - transitions and dependence should be learned from a dataset constucted using gen ai as a judge c.f. Content Curator
1. **Dark Tower** - One cental idea is to find a high level form to specify the content of the video. e.g.

    - generate a basic text instruction
    - improve to a detailed prompt
    - generate character and matte painting
    - composite into generate low res stills, 
    - then higher res stills,
    - use as key frames and tweens to short videos and
    - stich into longer videos.
1. **CopyCat** - A Control Network that learns to mimic motion by imitation learning from videos + access to a physics engine and guided by specs for

   1.  start
   2.  end states.
   3. prompts on style,
   4. schematics like paths for camera motion, character motion, lightning, changes in the enviroment (say weather or explosions etc.)
   - Some key challenges to address for the CopyCat paradigm
      - learn motion e.g. walk cycles (etc) by capturing motion from videos (humans animals etc) 
      - rl agents have learned eigen-motions etc by imitation datasets and videos.
      - one thinks this could be extended to capture motion of ensambles of objects and characters.
      - these might then form the basis of a high level of control language for generating videos.
      - i.e. these can be used to interpolate between key frames in action sequences like chases, fight scenes, warfare, dance, etc.
      where the animation or choreography is not clearly apparent from stills and texts prompts alone.
      - this should also facilitate specs for character and ensemble motions in a structred form.
3. Creating datasets to fit the models
   - To generate stories via Garden of intersecting paths and the Dark Tower paradigms requires learning some sort of non-parametric model from data, even if we can handcraft a simple prior to outline our views and delineate the schema we want to use.
   - However creating any substantial dataset of this form will require more human effort than is feasible for this project. Thus one option is to use generative AI or ML to create such a dataset.


Video will always take a long time to generate. So would prefer to always get good results and to be able to iterate quickly - i.e. to keep improving the 
video.

Using repl paradigm together with specs, and low rank inputs.

1. generate test video very quickly and then refine it (adding frames, resolution quality details.)
1. request corrections early on.
1. Address continuity and other errors.

Some ideas

1. use text and a chart to create control script guide the video generation.
1. generate a story board with keyframes using 2d or 3d Cambioso style "cardboard" manequins.
1. augment via interpolation to a flip book style animation. (Bayesian optimization might be helpful here to find the best keyframes to generate.))
1. control over camera angles, lightning, etc.


The brainstorm for mini-projects

- walk REPL - animate a 2d or 3d figure using an svg chart the chart could be a stick figure with a line.
- physics priors i.e  a prior for motion in 3d space capturing Tennebum's intutive physics. also might use a physics engine or physics inspired transformer network.



  