---
title: "Prediction Bibliography"
reference-location: margin
citation-location: document
categories: ["model thinking","book list"]
draft: True
---

Now that I finished model thinking It's time to dive deeper:

| Domain    | Citation                   | Title                                                               | Notes /Models  |
|-----------------|-----------------|-----------------|---------------------|
| ML        | [@vanderplas2022python]    | Python Data Science Handbook: Essential Tools for Working with Data |                |
| ML        | [@mckinney2022python]      | Python for Data Analysis                                            |                |
| ML        | [@geron2019hands]          | Hands-On ML with Scikit-Learn, Keras, and TensorFlow                | The ML bible   |
| CI        | [@pearl2009]               | Causality                                                           | Technical Book |
| CI        | [@pearl2018book]           | The book of why                                                     | Popular book   |
| ABM       | [@epstein1996growing]      | Growing Artificial Societies: Social Science from the Bottom up     | SugarScape     |
| ABM       | [@resnick1994turtles]      | Turtles, Termites, and Traffic Jams                                 | Traffic        |
| RL        | [@sutton2018reinforcement] | Reinforcement Learning: An Introduction                             | Misc RL        |
| RL        | [@lattimore2020bandit]     |                                                                     | Bandits        |
| RL        |                            |                                                                     |                |
| NLP       |                            |                                                                     |                |
| DeepL     |                            |                                                                     |                |
| Graphical |                            | Probabilistic Graphical Models                                      |                |

-   Statistical & Statistical Learning
    -   [@downey2011think] - Think Stats
    -   [@downey2021think] - Think Bayes
    -   [@efron2016computer] - Computer Age Statistical Inference
    -   [@huyen2022designing] - Designing Machine Learning Systems by Huyen, Chip
-   Hierarchical Models:
      BDA
      Statistical Rethinking      
-   Graphical Models
    -   Probabilistic Graphical Models: Principles and Techniques By Nir Friedman, Daphne Koller
-   Political Science Prediction
    -   [@tetlock2015superforecasting] - Superforecasting: The Art and Science of Prediction.
    -   [@de2009predictioneer] - The Predictioneer’s Game: Using the Logic of Brazen Self-Interest to See and Shape the Future
    -   [@silver2012signal] - The Signal and the Noise: Why so Many Predictions Fail-but Some Don’t.
-   Economics
    -   [@taleb2009black] - The Black Swan
    -   Behavioral Economics
        -   [@kahneman2011thinking] - Thinking fast, thinking slow
        -   [@kahneman2021noise] - Noise: A Flaw in Human Judgment
        -   [@levitt2009super] - Super Freakonomics
        -   [@levitt2004freakonomics] - Freakonomics
-   Social Science
    -   [@schelling1978micromotives] -
    -   [@bishop2009big] The Big Sort: Why the Clustering of Like-Minded America Is Tearing Us Apart
    -   [@christakis2009connected] Connected: The Surprising Power of Our Social Networks and How They Shape Our Lives.
-   Other
    -   [@epstein2019range] Range: How Generalists Triumph in a Specialized World
    -   [@duke2018thinking] Thinking in Bets: Making Smarter Decisions When You Don’t Have All the Facts
    -   [@harford2021data] The Data Detective: Ten Easy Rules to Make Sense of Statistics.
    -   [@duke2020decide] How to Decide: Simple Tools for Making Better Choices
    -   [@moore2020perfectly] Perfectly Confident: How to Calibrate Your Decisions
    -   [@grant2021think] Think Again: The Power of Knowing What You Don’t Know
-   Game Theory
-   Signals: Evolution, Learning & Information - Brian Skyrms
-   The Stag Hunt and the Evolution of Social Structure- Brian Skyrms
-   Mechanism Design
-   SNA
-   Automata
-   Chaos Theory

### References

::: {#refs}
:::
