---
data: 2025-03-17
title: Today In Politics
categories: [politics, rhetoric]
---


Today I read a friends note on Canadian's reactions to president Trumps threats of annexing Canada. 

I made the following points:

Perhaps the greatest point paradox Donald Trump is that he is both a great communicator and a terrible communicator. He is a great communicator in that he is able to get his message across when he wants to. He has lots of on air the expedite and background in sales. 

On the other hand he is also a notoriously bad communicator. Most often he is criticied as having a lack of experience in politics that leads him to make many mistakes any seasond politician would avoid.
For a long time I agreed with this view. I no longer subscribe to this view. 

Trump is vague and unclear. He almost always likes to makes inconsistent and contradictory statements. These are terrible faults for a politician to deal with. Yet when we had a debate with Harris an experienced politician on trial attorney she was not able to destroy him despite his long litany of outrageously ridiculous statements.

In the presidential campaigns he proved that he was much more effective than any career politician than the republicans could bring. Did they lie less than Donald Trump? I doubt it but even if I concede the point it doesn't matter since he beat them all. The only contender was Biden but we still got a second term of Trump. 
 
After I read the biography of "The Power Broker: Robert Moses and the Fall of New York is a 1974 biography of Robert Moses" by Robert Caro two things struck with me. The first based on the common view about Robert Moses is that even the basic truth of history are subject to populist interpretation further down the line. The second is that Moses who was known by his coleagues as a just and precise and idealistic communicator writer underwent radical changes when he learned about politics. When they sent him corrections to his memos etc he answered them that of course they were right but that the way he wrote it was the way he needed to get the outcomes he wanted, and the facts be damned.

I never met an idealistic version of Donald Trump and doubt that such a person ever existed. But I do think that these inconsistencies and contradictions are in no small part a strategy to keep people off balance. These are a lightning rod for the media and the public that often operate as great distractions for what is really going on. The media is so full of people who are making careers off reporting all of his inconsistencies and contradictions. His detractors are even more busy then his supporters in resonating his messages to wider and wider circles. This is a great strategy for a salesman, called there is no such thing as bad publicity and this is another reasons how Donald Trumps his opponents.

There are also supporters that ignore these outrageous statements.  Big mistake. The lies and contradictions in Trump's rhetoric are like markers in a students book indicating what point he feels should  be embellished or disguised with lies. 

Now about some of the things that people worry about and some alternative views.

I don't think he is a clown or a fool more like a two bit horse salesman. I know deeper down though that his is a great salesman and that even this image is a stragem he has developed to get one over on his opponents.

## Merging Canada and USA is

Merging Canada and USA is a great idea. It would be economic and might also bring some sanity to US politics. Once Canda got into the union they would be more senators, and representatives and the US is likely to have a more balanced political system. I don't see any big reasons why US should try to force this issue. We there is one -- Gloal warming and climate change. Trump is in his 80s and doesn't deal with global warming like a younder man would. He also doesn't see this as something the US should deal with while China and the glocal south get a pass to contiune polluting. The biggest and immediate threat of climate change is that US and other Global grannaries would dry up. Other places might get more rain but they are unlikely to be ready to take over the US's role as the world's bread basket at least not in the short term. One answer to this is to increase the US's territory. with some regions that are likely to get more rain. Canada is a good candidate for this, Greenland may be another. Mexico might follow later, but Mexico is closer to the equator and more likely to get drier not wetter. So the states of Cannada and greenland would allow the US to continue to be the world's bread basket -- good news for China and other importers of grain. Recall that the main reason for the recent Arab spring was the rise in the price of bread globally.

## EU betrayal

Getting EU members to start taking care of their defence and bolster their military is both sound and also essential. 

Most EU countries have a long history of being invaded and occupied by their neighbors. However they conviently negelected thier arrmies, munitions and defence budgets. Real defence has always taxed countries to the limit. Running a welfare state is so much easier if you can rely on the US to defend you. I reality though the US is too far away and too slow to moblize. EU countries need to make an invasion chance of success too slim to be worth the risk. Russia is a big weapons manufatuirer and subsidises much of the military hardware it sells to its allies. This is an economy of scale for russian. The US and it allies could undermine it but they need to be willing to spend the money on defence budget and grow thier armies and munitions. They might sell surpluss to russia's natural clients and thus undermine the russian ability to develop and sell new military hardware. If Russia only made weapons for its own use it would not be so attractive to rebuild its empire.


EU needs to rely first and foremost on their own armies and defences. 

## Ukraine

I'm not a proponent of nuclear arms proliferation but is seems to mee that ukraine wars and the annexation of crimea would never have been possible if they refused to give up their nukes back in the 90s. 

There is a good chance though that Ukraine was a dress rehearsal for Russia and China. Russia with Iran and North Korea and a few other failed states are more then likely to use thier military might to take territory from defenseless neighbors. When they make their moves the US and others may stand in opposition. But they may also follow suit. 

China's Army is large but also corrupt. But if it get a mission to take Taiwan it may do so. The US and others may stand in opposition but this may be a quick move and they may be too slow to stop it.

## Panama

The panama canal will continue to dry up and I think the us or china might be able to fix it with Israeli tech. It needs to get a lot of water from the pacific and the atlantic up to the lake that feeds the canal.

 I doubt panama is up to the task. I think China belt and road initiative would lead to them owning Paname. So an agressive stance might be needed to make a concession and let american investors in to
 fix the canal.

## Gaza

 I also believe the Gaza Palestinians would gladly relocate to the us or china or . China has vacant cities to house them. Many Europe countries might house them in existing real estate. So all these ideas are sound on paper. I think that trump doesn't have a clue how to actually realize them all.

No one wants the Gazan trouble maker. Certainly not neighbors with sizable no of Palestinian refugees. Jews had the same woes 100 years back. It clear that these supportive neighbors will "look after the palestinians's" best interests. Particularly if that helps ensure no more palestinians refugees come to destabilize thier countries. 
Egypt's selectorate also gets the king share of the Quatrian and Itanina funds used in smuggling to keep the status quo by rearming the palestinians. 

## The UN

Yuval Harari in his book Sapiens makes a good case that the UN has been a force for good in being able to resolve many small conflicts. 
We might also ascribe this to the salubrious effects of McDonalds and Coca Cola. 

However, in the real world the UN is also increasingly subject to manipulations by Russia, Iran, China, arab states and others. As the number of tin pot dictators, failed states, spin dictators, and other bad faith actors increases the UN can be seen to have transitioned from a force for good to being dominated by bad faith actors and their interests.

Recent levels of this manipulation leads me to envision the day when the UN will go the way of the League of Nations. I doubt that when the good faith actors pull out thier funding and military support that the UN will be able to continue to function on the financial support and direction of the bad faith actors.

The US and other countries will need to be ready to take over the UN's role in resolving conflicts. Other more focused organs may better take over UN's roles in other areas such as aid, disaster relief, health, etc.

Perhaps a future organization will be setup. If it is to be effective it will require a radical new way of thinking. The security council with its veto power become irrelevant once two or more of its members enter into conflict. The general assembly is subject to manipulation by countries that face no consequences for their actions. It seems that the UN is no longer a organ for peace and stability but a tool for manipulation for destabilization of potential enemies in different theaters.

## Conclusion

I Don't know if Donald Trump will be able to sell any of his ideas to the public or to expedite them. I doubt he will resort to using military force but using a stick and a carrot means makeing what seem to be creadible threats.

I also think that more than anything trump needs to sell his ideas. Not sure he has the wrong people for that. I'm pretty sure his administration will be very fluid. 

Being unpredictable isn't just his nature it is also an excellent strategy in most competitive games. So I don't like Trump or Putin but their replacement will almost certainly pursue most of these radical plans. Biden certainly did to a large extent follow through on many of trump's policies.

I give trump 3:2 odds of not surviving his full term. I'm more worried about J.D. Vance.


