---
date: 2017-07-05
last-modified: 2023-01-19
title: Deep Neural Networks - Notes for lecture 1d
subtitle: For the course by Geoffrey Hinton on Coursera
description: Notes for Deep learning focusing on a simple example of learning learning?
categories: [deep learning, neural networks, notes, coursera] 
title-block-banner: banner_deep.jpg
---

```{=html}
<style>
.a4paper {margin: 0; aspect-ratio: 1 / 1.41;}
.letterpaper  {margin: 0; aspect-ratio: 22 / 17;}
.ppSlide {margin: 0; aspect-ratio: 22 / 13;}
</style>
```

{{< pdf lec1.pdf width="100%" class="ppSlide" >}}

# Lecture 1d: A simple example of learning

{{< video https://www.youtube.com/watch?v=iryPlswgRSA
    class=column-margin
    title="Lecture 1c: Some simple models of neurons" 
    width="1024" 
    height="720" >}}


## Visualization of neural networks is one of the few methods to get some insights into what is going on inside the black box. 

- Consider a neural network with two layers of neurons.
  - neurons in the top layer represent known shapes.
  - neurons in the bottom layer represent pixel intensities.
- A pixel gets to vote if it has ink on it.
  - Each inked pixel can vote for several different shapes.
- The shape that gets the most votes wins. 


### How to display the weights 

Give each output unit its own “map” of the input image and display the weight coming from each pixel in the location of that pixel in the map.

Use a black or white blob with the area representing the magnitude of the weight and the color representing the sign. 

### How to learn the weights

Show the network an image and increment the weights from active pixels to the correct class.

Then decrement the weights from active pixels to whatever class the network guesses

### The learned weights 

The details of the learning algorithm will be explained in future lectures. 

### Why the simple learning algorithm is insufficient

- A two layer network with a single winner in the top layer is equivalent to having a rigid template for each shape.
- The winner is the template that has the biggest overlap with the ink.
- The ways in which hand-written digits vary are much too complicated to be captured by simple template matches of
whole shapes.
- To capture all the allowable variations of a digit we need to learn the features that it is composed of.
