---
title: "the war"
date: 2024-06-06
description: "notes on the Ukrain war, Swords of Iron, and the cost of war"
categories: [war, economics, politics]
draft: true
---


In discussion I had last afternoon with a friend, we discussed the ongoing war.

I made mention of few points I'd like to make note of here.

1. Drones attacks are likely to become a fact of life in this part of the world
   going foreward. Our enemeis have been investing in rockets and missiles for 
   several decades now with a rather small investment in tanks and aeroplanes
   which cost orders of magnitude more. 
   Drones are cheaper than most missiles and rockets and now that the is lost of
   knowledge of how to build them, they are accessible to orgeanizations that
   do not have the resources to build or even buy rockets and missiles.
2. Prolonged wars for a small and isolated country are a bad idea. While I could 
   go into detail about the reasons why, I think it would be much better to come
   up with a formal model represnting what I mean in this context.
3. The war in Ukraine likely had economical reasons as well as the official 
   resitance to Nato's continuing incursion into the former Soviet Union. 
   Putin and his advisers had tried and succeeded in the past to make territorial
   gains in the former Soviet Union and at practically no cost. This made them
   bold and they miscaculated the likelyhood of a quick victory in Ukraine.
4. The war in the Ukraine like many recent wars featured large costs to civilians
   population. This strategy of targeting civilians is against the Geneva convention
   and likely to be a war crime. However a player like Putin isn't likely to be
   deterred by the threat of being tried for war crimes as he can litteraly veto
   any such action in the UN security council.
   However there is a munition economy in any war and destroying civilian
   infrastructure when they could be used to support the war effort suggests that for    Russia the notion of the battlefield is not limited to the front lines. 
   It seems that they view this more as a total war where the entire country is the
   battlefield.
   Perhaps even as assymetric warfare where thier enemy is the military of Ukraine
   which is embedded in the civilian population.
5. Many conflicts by an attacker against a defender follow the Colonel Blotto game
   where the attacker can divide his forces between several fronts and thereby gain
   and advantage over a stronge defender.
6. The real reason why Israel refused to give the iron dome technology to Ukraine:
    - not that they are the technology would be reverse engineed
    - not that they are afraid that on that battlefield the russians and thier
    allies would be able to learn to counter the iron dome system
    - not to avoid angering Russia which has a large Jewish population and a 
    significant military presence in Syria.
    - not because they are afraid of the technology falling into the hands of
    the wrong people.
    
    - I think that these all seem to be valid concerns and were raised by differnt people in the media. The real reason is unspoken and has emerged during the 
  "Swords of Iron" operation in Gaza.
  - The real concerns are related to its muinition economy. 
  - The iron dome is a very expensive system to operate and the cost of operating 
    it is likely to be higher than the cost of the rockets it is intercepting. 
    This is a munition economy that is not sustainable in a prolonged war. 
    Most if not all the munitions used by the iron dome are made in the US and 
    the US is likely to be the one paying for the operation of the iron dome in
    Ukraine. Once iron dome was needed in Israel, the US would be have to make a
    choice between supporting Israel or supporting Ukraine.
    By not giving the iron dome to Ukraine the US was spared from having to make 
    this choice. This is a euphemism for the Israeli descision being a practical 
    one - they did not want to create scarcity in the munition comming from the US
    and would rather make exclisive use of it than share it with Ukraine. In the 
    longrun, this might signinificantly reduce the costs of munitions due to a
    economy of scale.
    However it is just as likely that in the long term the battle field will 
    change and the iron dome will be rendered obsolete and be supplanted by a 
    more econmicaly viable system.
7. There seems to be a rule of thumb that in assymetrical warfare the stronger side
   would prefer to attack just the insurgents and not the civilian population. 
   However both sides will try to maximze the effect if their resources. In this 
   case these are weopons and soldiers. The insurgents are embedded in the civilian
   population and if they force the stronger side to attack then it is the civilian
   population that will suffer the most. The rule I was thinking of is both military
   and economic. The costs to the civilian population are likely to in proportion to
   the budget of the stronger side. The are likely to inversly proportional to the
   proportion of the insuregents to the population in which they are embedded.
   
$$
\text{costs to civilians} \propto \text{budget of the stronger side} \times \text{insurgents \ population}
$$
  
  
## a simple model of the cost of war

1. Contemporary wars have four forces.
  - a military objective which is the goal of the war.
  - a costs to human lives, 
  - an economic costs which human lives are also a part of.
    - munitions costs
    - infrastructure costs
    - losses in productivity due to the war
    - losses due to sanctions, embargos and boycotts
    - losses due to payment of reparations if the war is lost.
  - a cost in public opinion.

$$
\begin{align*} 
\text{cost of war} = \text{munitions costs} + \text{infrastructure costs}
\end{align*}
$$

One of the problems is however that many of these costs are not borne by the
the decision makers. 

Some costs of the war are borne by the population of the countries that is at war.
Others are borne by their allies and enemies. 

In the war in Gaza, the cost of the war was borne by:
- The IDF and the population of Israel and their allies (The US)
- The Hamas embeded in the population of Gaza and their allies (Quatar, Iran and their proxies,






   
1. The cost of war is the sum of the costs of the munitions used in the war and the
   costs of the infrastructure destroyed in the war.
   