---
title: "New Year Resolutions for 2026"
subtitle: "Review and Study Guide"
date: 2026-01-04
---

1. **Courses**: I will take more courses in 2026, both online and in person. I will focus on courses that are relevant to my research interests and that will help me develop new skills. I will also try to find courses that are taught by experts in the field and that have good reviews from students.
1. **Reading**: I will read more papers and books in 2026. I will focus on papers that are relevant to my research interests and that are published in reputable journals. I will also try to read papers that are written by experts in the field and that have good reviews from other researchers.
1. **Coding**: I will do an android project, and agentic AI project.
1. **Modeling**: I want to get good with hierarchical models, BNPs, Pyro including implementing Normalizing flows and variational inference and Probabilistic programming in general. 
1. I want to put a few models in the cloud using AWS environment 
1. Create a small serverless fullback project this should be SAS web app.
1. Code web components in React, Svelte, and Vue.
1. Code quarto skin with Lit web components and extensions.
1. Code shinylive live with ai and chat integration.
1. Code some more RL models.


