---
title: ad hoc complex signaling systems
categories: [signaling games, complex signaling systems, compositionality, communication protocols,emergent languages] 
---

Rather them consider how complex signaling systems evolve from a lewis signaling game plus some modifications it might be worth while to better understand some complex signaling systems.

Essentially One would equip the agents with a set of complex signals and see if they can acquire more powerful signaling system to communicate more effectively.

This should allow us to quantify:

1. the expressivity of different features of complex signaling systems.
2. the complexities of learning
3. the complexities of avoiding deception...




::: {.callout-note}
### What is compositionality in signaling systems?

1. Given a rudimentary signaling system how can we use it to construct and learn a more complex signaling systems?
2. Once we have this two step process we can then consider the complex signaling system as a single unit and see if it can be learned directly ?
3. After we have done it a few times we can we generalize the process to signaling systems with desiderata similar to natural languages?
4. Can we specialize signaling systems to operate with specific RL tasks
5. Can we use signaling systems as a symbolic abstraction of the environment and thus transfer learning from one environment to another?

:::


## Logical Aggregation 

## operators 

## Learning to negate:

I suppose there are many ways to learn to negate. Let's consider two 

- in English. We use the word 'Not'. 
- in logic we use the symbol $\neg$.
- in python we use the keyword 'not'
- in hungarian we use the word 'nem' 

Not in all three cases a unitary operator that takes a single argument and returns the opposite of that argument.

We can use it to map the next signal to some other unique signal. This is how a unitary prefix operator works.
For us though not means something more than some other signal it means all the other options. Not red means all the other colors, not cat means all the other animals. So the semantics we would like to capture requires that there are categories of signals and that the negation operator maps to the rest of the category. This is a handful. Also note that the categories may be defined as partial pooling equilibria.

let's imagine that a group of Marmoset monkeys need to signal predators. The state space describes the predators are based on a product of the following features:

temporal :   imminent, near, medium, distant
type:        cat, snake, pirana, eagle
direction_theta: 0 1 2 3
position_phi:   0 1 2 3
number: 1, 2, 3, more


yes they use solid coordinates to describe to location of the predators.

this gives us 4^4 = 256 states.

that's a lot of signals. but a complex signaling system could be able to communicate about all of them.

If the monkeys use a template with 4 parts to communicate about the predators then they can use just four signals. 

also the 4 signals share common semantics of increasing values.
for the animals the threat level might be used to name them ...





- states $St_0:St_{2M}$
- lew_primitives = $Sig_0:Sig_{2N}$ indicating 0...n and nor 0 ... not n.
- neg_primitives = $NOT, sig_0:sig_{N}$ 
- prefix coding negation = <NOT, neg_primitives> = Sig_{n+N} 
- suffix coding negation = <neg_primitives, NOT>
- prefix protocol


- In this case we don't have a clear benefit of suffix and prefix. but later we will see how prefix coding is a fit for the desiderata of complex signaling systems.

- let's consider a 2 state with negation. 
- in the lewis game we have 2 signals 0 and 1.
- in the negation_system,
- The semantics of negation (its meaning) can be defined as we are use to i.e. no 1 mean 0 and no 0 means 1. But in this case we don't get any benefit from the negation, we just get a system with longer signals.
 we can interpret it as a trick we learn to double the number of symbols we can use.

now consider a 4 symbol system with negation.


- A conjunctive signaling system
- A disjunctive signaling system
- A signaling system with conjunctions and disjunctions
- Signaling with Run-length encoding
- Signaling with Prefix-codes

## Morphology

- A signaling system with a morphological template

## Synatax

- A signaling system with a syntactic template
- Signaling system with a multiple templates
- Signaling system with a multiple templates


## Sequence Aggregation


- A Sequential signaling system with n signals
- A matrix signaling system
- Template signaling system



