---
date: 2024-05-01
title: "Discarded Bibliographical Items"
subtitle: "learing language games"
keywords: [game theory, signaling games, partial pooling, evolution, reinforcement learning, signaling systems, evolution of language]
draft: True
---

## Discarded Bibliographical Items

The following are not interesting 

-   Alon, U. (2006) An Introduction to Systems Biology: Design Principles and Biological Circuits. Chapman and Hall.
  - biology
-   Alon, U. (2007) “**Network Motifs**: Theory and Experimental Approaches.” Nature 8: 450–461. Anderson, C. and N. R. Franks (2001) “Teams in Animal Societies.” Behavioral Ecology 12: 534–540.
  - network theory
-   Bauer, W. D. and U. Mathesius (2004) “Plant Responses to Bacterial Quorum-Sensing Signals.” Current Opinion in Plant Biology 7: 429–433.
  - animal
-   ~~Barnes, J. (2001) Early Greek Philosophy. 2nd edn. London: Penguin.~~
  - classics
-   ~~Barnes, J. (1982) The Presocratic Philosophers. London: Routledge.~~
  - classics
-   Chomsky, N. (1957) Syntactic Structures. The Hague: Mouton.
    -   general linguistics
-   ~~Dante The Divine Comedy of Dante Alighieri. Trans. H. F. Cary, ed. Jim Manis. PSU Electronic Classics, .~~
    -   classics
-   ~~De Morgan, A. (1838) An Essay on Probabilities and their Application to Life Contingencies and Insurance Offices. London: Longman.~~
    -   general probability
-   Green, E. and T. Maegner (1998) “Red Squirrels, Tamiasciurus hudsonicus, Produce Predator-Class Specific Alarm Calls.” Animal Behavior 55: 511–518.
-   Kaiser, D. (2004) “Signaling in Myxobacteria.”Annual Review of Microbiology 58: 75–98.
  - animal
-   Kant, I. (1965) \[1785\] Fundamental Principles of the Metaphysics of Morals. Trans. Thomas Kingsmill Abbott Project Gutenberg. 10 edn. London: Longmans Green.
  -   general philosophy
-   Kirchhof, J. and K. Hammerschmidt (2007) “Functionally Referential Alarm Calls in Tamarins (Saguinis fusicollis and Saguinis mystax.)—Evidence from Playback Experiments.” Ethology 112: 346–354.
  -   animal
-   Manser, M., R. M. Seyfarth, and D. Cheney (2002) “Suricate Alarm Calls Signal Predator Class and Urgency.” Trends in Cognitive Science 6: 55–57.
  -   animal
-   Marler, P. (1999) “On Innateness: Are Sparrow Songs ‘Learned’ or ‘Innate.’” In The Design of Animal Communication, ed. Marc Hauser and Mark Konishi. Cambridge, MA: MIT Press.  
  - animal
-   ~~Lloyd, J. E. (1965) “Aggressive Mimicry in Photuris: Firefly Femmes Fatales.” Science 149: 653–654.~~
  - animal
-   ~~Lloyd, J. E. (1975) “Aggressive Mimicry in Fireflies: Signal Repertoires of Femmes Fatales.” Science 187: 452–453.~~
  - animal  
-   Malinowski, B. (1920) “Kula: The Circulating Exchange of Valuables in the Archipelagoes of Eastern New Guinea.” MAN 20: 97–105.
    -   anthropological
-   Malinowski, B. (1922) Argonauts of the Western Pacific. New York: Dutton.
    -   anthropological
-   Pitman, J. (1995) “Exchangeable and Partially Exchangeable Random Partitions.” Probability Theory and Related Fields 102: 145–158. Proclus. (2007) On Plato Cratylus. Trans. Brian Duvick. London: Duckworth.
    -   classics
-   Savage-Rumbaugh, S., K. McDonald, R. A. Sevkic, W. D., Hopkins, and E. Rupert (1986) “Spontaneous Symbol Acquisition and Communicative Use by Pygmy-Chimpanzees (Pan Paniscus)” Journal of Experimental Psychology: General 114: 211–235.
    -   animal
-   Savage-Rumbaugh, S. and R. Lewin (1994) Kanzi: An Ape at the Brink of the Human Mind. New York: Wiley.
    -   animal
-   Schauder, S. and B. Bassler (2001) “The Languages of Bacteria.” Genes and Development 15: 1468–1480.
    -   animal
-   Sedley, D. (1998) Lucretius and the Transformation of Greek Wisdom. Cambridge: Cambridge University Press.
    -   classics
-   Sedley, D. (2003a) Plato’s Cratylus. Cambridge: Cambridge University Press.
    -   classics
-   Sedley, D. (2003b) “Lucretius and the New Empedocles.” Leeds International Classical Studies 2.4: 1–12.
    -   classics
-   Vencl, F., B. J. Blasko, and A. D. Carlson (1994) “Flash Behavior of Female Photuris Versicolor Fireflies in Simulated Courtship and Predatory Dialogues.” Journal of Insect Behavior 7: 843–858.
    -   animal
-   Verlinsky, A. (2005) “Epicurus and his Predecessors on the Origin of Language.” In Frede and Inwood 56–100.
    -   classics
-   von Frisch, K. (1967) The Dance Language and Orientation of the Bees. Cambridge, MA: Harvard University Press.
    -   animal
-   ~~Vitruvius (1960) The Ten Books of Architecture Bk. 2 Ch. 1. Tr. Morris Hicky Morgan New York: Dover.~~
    -   classical motivation
-   Wolf, D. M. and A. P. Arkin (2003) “Motifs, Modules and Games in Bacteria.” Current Opinion in Microbiology 6: 125–134.
    -   animal
-   Ziegler, R. (2007) The Kula Ring of Bronislaw Malinowski: A Simulation Model of the Co-Evolution of an Economic and Ceremonial Exchange System. Munich: C. H. Beck Verlag.
    -   anthropological
-   Zeigler, R. (2008) “What Makes the Kula Go Round?” Social Networks 30: 107–126.
    -   anthropological
-   Zuberbu¨hler, K. (2000) “Referential Labeling in Diana Monkeys.” Animal Behavior 59: 917–927.
    -   animal
-   Zuberbu¨hler, K. (2001) “Predator-Specific Alarm Calls in Campbell’s Monkeys, Cercopithecus Campbelli.” Behavioral Ecology and Sociobiology 50: 414–422.
    -   animal
-   Zuberbu¨hler, K. (2002) “A Syntactic Rule in Forest Monkey Communication.” Animal Behavior 63: 293–299.
    -   animal
