---
title: primitive action
categories:
    - NLP
    - NLU
    - KR
    - Ontology
bibliography: cai.bib
date: 2021-04-12


---

in @Schank1977 the authors defined eleven primitive actions which they considered sufficient to represent arbitrary sentences.

Conceptual dependency - here are the Ontology of primitive actions from Conceptual Dependency in conceptual AI:

1. `ASSERT` - to assert a proposition as true
1. `RETRACT` - to retract a previously asserted proposition
1. `QUERY` - to ask a question and obtain a response
1. `SEQUENCE` - to establish a temporal sequence of events or actions
1. `GROUP` - to group concepts together based on a shared attribute or relationship
1. `SORT` - to order concepts based on a criterion or attribute
1. `COMPARE` - to compare two or more concepts based on a shared attribute or relationship
1. `SELECT` - to choose a concept or set of concepts based on a criterion or attribute
1. `MODIFY` - to change the attributes or relationships of a concept
1. `CREATE` - to create a new concept based on existing concepts or relationships
1. `DESTROY` - to remove a concept or relationship from the conceptual system
1. `TRANSFER` - to move a concept from one location to another
1. `MOVE` - to physically move an object or entity in the world
1. `COMMUNICATE` - to send or receive a message or signal.
These primitive actions are used to build more complex actions and form a conceptual hierarchy that represents the knowledge and actions of an AI system based on Conceptual Dependency theory.

## Pros & Cons

We are reducing all actions to 12 basic actions so we are reducing dimensionality of natural language. In terms of understanding we are down to a small sets. As is done later we can refine the primitive actions using frames by converting them into compound verbs - which can refine meaning without straing very far from the top level ontology. 

We lose the resolution of the natural langauge. 
