---
date: 2024-05-01
title: "Skyrms Signals Summary Bibliography"
subtitle: "Bibliography of Signals by Skyrms"
keywords: [game theory, signaling games, partial pooling, evolution, reinforcement learning, signaling systems, evolution of language]
bibliography: ./bibliography.bib
draft: true
---

So this one is not going to become an article - post but is a summary of the bibliography of the book Signals by Skyrms.

Ideally, 
1. I will extract bibliographical entries into a bibliography file for citations of appropriate material.
2. I will reviews some relevant papers etc for my own work.
3. Try to figure out what the material is about.
4. Note that NotebookLM can probably help with breif summary for each source. 
5. There are actually some review articles as well that may have more recent material!

- Skyrms brilliant mind kept all these tidbits of information in his head but many were not as important for exploring what seemed to be the main thrust of the book which was a game theoretical motivated account of the emergence of language 
  and the mechanisms of language learning.
    - this is a mathematical task which Skyrms here tackles primarily as a philosopher. 
    - Many useful and interesting facts and inferences are not made because he does not develop the mathematical 
      in a particularly rigorous way, rather preferring to referencing a multitude of sources.
    - Coding some of these model led to a number of deeper observations and some I found mentioned off hand in the book
      others in some of the papers cited.
  The book had other agendas and the work had been aimed more at philosophical circles. However the growing interest seems to
  be in ML and specially in Multi-agent reinforcement Learning (MARL).  
- Reading the book repeatedly in many places, I began to feel that the book had two types of material 
    - the brilliant presentation of interweaving ideas.
    - lots of filler that had grown out of extended literature reviews on subjects touching on lewis games. 
        - Much of these tended to digress from the main research questions.
        - Almost all of these were not very interesting
        - But a few are very interesting indeed 
        - A select few merit deeper coverage and required deeper dives to clarify many point that the author had not full digested.
- At the time of writing some of the more interesting work on composability and evolution of grammar had either not been done
  

- I eventually decided to go over the bibliography and extract the different items that seemed more relevant.
- This took more time than I could spare. 
    - Some items I need to cover were book sized or chapter sized
    - Others quickly led to event more useful publication that were not part of the books bibliography. Several by Skyrms.
- There are a few variants of the lewis games now using different
- I ended up classifying the least and most relevant items. 

Going through the bibliography many times 

and annotating the interesting and less interesting entries.

# Signals Bibliography - some annotations



The following bibliographical entries are on

- General and Evolutionary Game Theory:

-   [@vonneumann1947] - The first book on game theory.
-   [@Weibull1997] - A book on evolutionary game theory.
-   [@hofbauer1998evolutionary] - Covers the mathematical theory of evolutionary games focusing on the Lokta Volterra model and the replicator dynamics.
-   [@Samuelson1998Evolutionary] - Covers on evolutionary game theory in extensive forms.
-   [@Nowak2006Evolutionary] - A book on evolutionary dynamics.
-   **Aumann, R. (1987) "Subjectivity and Correlation in Randomized Strategies." Journal of Mathematical Economics 1: 67–96.**
-   **Aumann, R. (1987) "Correlated Equilibrium as an Expression of Bayesian Rationality." Econometrica 55: 1–18.**


- The following are on The basic RL methods described 
  
  - Bush Mosteller RL 
    -   Bush, R. and F. Mosteller (1955) Stochastic Models of Learning. John Wiley & Sons: New York.
  - Roth Erev RL
    -   Erev, I. and E. Haruvy (2005) “On the Potential Uses and Current Limitations of Data-Driven Learning Models.” Journal of Mathematical Psychology 49: 357–371.
    -   Erev, I. and A. Roth (1998) “Predicting How People Play Games: Reinforcement Learning in Experimental Games with Unique Mixed-Strategy Equilibria.” American Economic Review 88: 848–881.
    -   Roth, A. and I. Erev (1995) “Learning in Extensive Form Games: Experimental Data and Simple Dynamical Models in the Intermediate Term.” Games and Economic Behavior 8: 164–212.
  - Herrnstein RL
    -   Herrnstein, R. J. (1961) “Relative and Absolute Strength of Response as a Function of Frequency of Reinforcement.” Journal of Experimental Analysis of Behavior 4: 267–272.
    -   Herrnstein, R. J. (1970) “On the Law of Effect.” Journal of the Experimental Analysis of Behavior 13: 243–266.
  - Others 
    -   Argiento, R., R. Pemantle, B. Skyrms, and S. Volkov (2009) “Learning to Signal: Analysis of a Micro-Level **Reinforcement Model**.” Stochastic Processes and their Applications 119: 373–390.
- The following are part of Luc Steel's Program  on Modelling language using games
  -   [@steels1997synthetic]
  -   [@steels1998origins]
  -   [@steels2001LanguageGames]
  - Wikipedia list many others.

-   [@Smith1973LogicAnimalConflict] ~~Maynard Smith, J. and G. R. Price (1973) “The Logic of Animal Conflict.” Nature 246: 15–18.~~
-   Maynard Smith, J. and G. A. Parker (1976) “The Logic of Asymmetric Contests.” Animal Behaviour 24: 159–175.
-   Maynard Smith, J. (1982) Evolution and the Theory of Games. Cambridge: Cambridge University Press.
-   Maynard Smith, J. (2000) "The Concept of Information in Biology." Philosophy of Science 67: 177–194.
-   Maynard Smith, J. and D. Harper (2003) Animal Signals. Oxford: Oxford University Press.


- The following categories are of no interest for my current investigations
  - Anthropology
    -   Malinowski, B. (1920) “Kula: The Circulating Exchange of Valuables in the Archipelagoes of Eastern New Guinea.” MAN 20: 97–105.
    -   Malinowski, B. (1922) Argonauts of the Western Pacific. New York: Dutton.
    -   Ziegler, R. (2007) The Kula Ring of Bronislaw Malinowski: A Simulation Model of the Co-Evolution of an Economic and Ceremonial Exchange System. Munich: C. H. Beck Verlag.
    -   Zeigler, R. (2008) “What Makes the Kula Go Round?” Social Networks 30: 107–126.
  - Animal signaling  
    -   Bauer, W. D. and U. Mathesius (2004) “Plant Responses to Bacterial Quorum-Sensing Signals.” Current Opinion in Plant Biology 7: 429–433.
    -   Green, E. and T. Maegner (1998) “Red Squirrels, Tamiasciurus hudsonicus, Produce Predator-Class Specific Alarm Calls.” Animal Behavior 55: 511–518.
    -   Kaiser, D. (2004) “Signaling in Myxobacteria.”Annual Review of Microbiology 58: 75–98.
    -   Manser, M., R. M. Seyfarth, and D. Cheney (2002) “Suricate Alarm Calls Signal Predator Class and Urgency.” Trends in Cognitive Science 6: 55–57.
    -   Marler, P. (1999) “On Innateness: Are Sparrow Songs ‘Learned’ or ‘Innate.’” 
        In The Design of Animal Communication, ed. Marc Hauser and Mark Konishi. Cambridge, MA: MIT Press.  
    -   Kirchhof, J. and K. Hammerschmidt (2007) “Functionally Referential Alarm Calls in Tamarins (Saguinis fusicollis and Saguinis mystax.)—Evidence from Playback Experiments.”
        Ethology 112: 346–354.  
    -   Lloyd, J. E. (1965) “Aggressive Mimicry in Photuris: Firefly Femmes Fatales.” Science 149: 653–654.
    -   Lloyd, J. E. (1975) “Aggressive Mimicry in Fireflies: Signal Repertoires of Femmes Fatales.” Science 187: 452–453.
    -   Savage-Rumbaugh, S., K. McDonald, R. A. Sevkic, W. D., Hopkins, and E. Rupert (1986) “Spontaneous Symbol Acquisition and Communicative Use by Pygmy-Chimpanzees (Pan Paniscus)”
        Journal of Experimental Psychology: General 114: 211–235.  
    -   Savage-Rumbaugh, S. and R. Lewin (1994) Kanzi: An Ape at the Brink of the Human Mind. New York: Wiley.  
    -   Schauder, S. and B. Bassler (2001) “The Languages of Bacteria.” Genes and Development 15: 1468–1480.
    -   Tempelton, C., E. Greene and K. Davis (2005) “Allometry of Alarm Calls: Black-Capped Chickadees Encode Information about Predator Size.” Science 308: 1934–1937.
    -   Vencl, F., B. J. Blasko, and A. D. Carlson (1994) “Flash Behavior of Female Photuris Versicolor Fireflies in Simulated Courtship and Predatory Dialogues.” 
        Journal of Insect Behavior 7: 843–858.
    -   von Frisch, K. (1967) The Dance Language and Orientation of the Bees. Cambridge, MA: Harvard University Press.  
    -   Wolf, D. M. and A. P. Arkin (2003) “Motifs, Modules and Games in Bacteria.” Current Opinion in Microbiology 6: 125–134.
    -   Zuberbu¨hler, K. (2000) “Referential Labeling in Diana Monkeys.” Animal Behavior 59: 917–927.
    -   Zuberbu¨hler, K. (2001) “Predator-Specific Alarm Calls in Campbell’s Monkeys, Cercopithecus Campbelli.” Behavioral Ecology and Sociobiology 50: 414–422.  
    -   Zuberbu¨hler, K. (2002) “A Syntactic Rule in Forest Monkey Communication.” Animal Behavior 63: 293–299.
  - Classics
    -   Barnes, J. (2001) Early Greek Philosophy. 2nd edn. London: Penguin.
    -   Barnes, J. (1982) The Presocratic Philosophers. London: Routledge.
    -   Dante The Divine Comedy of Dante Alighieri. Trans. H. F. Cary, ed. Jim Manis. PSU Electronic Classics, .
    -   Sedley, D. (1998) Lucretius and the Transformation of Greek Wisdom. Cambridge: Cambridge University Press.
    -   Sedley, D. (2003a) Plato’s Cratylus. Cambridge: Cambridge University Press.
    -   Sedley, D. (2003b) “Lucretius and the New Empedocles.” Leeds International Classical Studies 2.4: 1–12.
    -   Verlinsky, A. (2005) “Epicurus and his Predecessors on the Origin of Language.” In Frede and Inwood 56–100.
    -   Vitruvius (1960) The Ten Books of Architecture Bk. 2 Ch. 1. Tr. Morris Hicky Morgan New York: Dover.
  - Linguistics
    -   Chomsky, N. (1957) Syntactic Structures. The Hague: Mouton.
    -   Pinker, S., and R. Jackendoff (2005) “The Faculty of Language: What’s Special About It?” Cognition 95: 201–236.
  - Philosophy
    -   Aristotle Historia Animalium Book IX. Aristotle Physics Book II.
    -   Kant, I. (1965) \[1785\] Fundamental Principles of the Metaphysics of Morals. Trans. Thomas Kingsmill Abbott Project Gutenberg. 10 edn. London: Longmans Green.
    -   Pitman, J. (1995) “Exchangeable and Partially Exchangeable Random Partitions.” Probability Theory and Related Fields 102: 145–158. Proclus. (2007) 
        On Plato Cratylus. Trans. Brian Duvick. London: Duckworth.
  - Probability & Statistics
    -   De Morgan, A. (1838) An Essay on Probabilities and their Application to Life Contingencies and Insurance Offices. London: Longman.
    -   Aldous, D. (1985) “Exchangeability and Related Topics.” In L’E´cole d’e´te´ de probabilite´s de Saint-Flour, XIII–1983 1–198. Berlin: Springer.
  - Network theory
    -   Alon, U. (2006) An Introduction to Systems Biology: Design Principles and Biological Circuits. Chapman and Hall.
    -   Alon, U. (2007) “**Network Motifs**: Theory and Experimental Approaches.” Nature 8: 450–461. Anderson, C. and N. R. Franks (2001) “Teams in Animal Societies.” 
        Behavioral Ecology 12: 534–540.
    -   Galeotti, A., S. Goyal, and J. Kamphorst (2006) “Network Formation with Heterogeneous Players.” Games and Economic Behavior 54: 353–372.



The bibliography

-   Asher, N., I. Sher and M. Williams (2001) “Game Theoretical Foundations for Gricean Constraints.” In Proceedings of the Thirteenth Amsterdam Colloquium. Amsterdam: IILC.
-   Bala, V. and S. Goya (2000) “A Noncooperative Model of Network Formation.” Econometrica 68: 1181–1231.
-   [@Barrett2006Numerical] ~~Barrett, J. A. (2006) “Numerical Simulations of the Lewis Signaling Game: Learning Strategies, Pooling Equilibria, and the Evolution of Grammar.” Working Paper MBS06–09. University of California, Irvine.~~
-   [@Barrett2009Evolution] ~~Barrett, J. A. (2007a) “The Evolution of Coding in Signaling Games.” Theory and Decision. DOI: 10.1007/s11238–007–9064–0.~~
-   [@Barrett2007Dynamic] ~~Barrett, J. A. (2007b) “Dynamic Partitioning and the Conventionality of Kinds.” Philosophy of Science 74: 527–546.~~
-   [@barrett2009role] ~~The Role of Forgetting in the Evolution and Learning of Language.” preprint.~~
-   [@batali1998] ~~Batali, J. (1998) “Computational Simulations of the Evolution of Grammar.” In Approaches to the Evolution of Language: Social and Cognitive Bases, ed. J. R. Hurford et al. Cambridge: Cambridge University Press.~~
-   Beggs, A. (2005) “On the Convergence of **Reinforcement Learning**.” Journal of Economic Theory 122: 1–36.
-   Benaim, M. (1999) “Dynamics of Stochastic Approximation Algorithms.” In Seminaire de Probabilites 33. Berlin: Springer Verlag.
-   Benaim, M., S. J. Shreiber, and P. Tarres (2004) “Generalized Urn Models of Evolutionary Processes.” Annals of Applied Probability 14: 1455–1478.
-   [@Bereby1998Loser] ~~“On Learning How to be a Successful Loser: A Comparison of Alternative Abstractions of Learning Processes in the Loss Domain.”~~ 
-   Berg, R. M. van den (2008) Proclus’ Commentary on the Cratylus in Context. Leiden: Brill.
-   Bergstrom, T. (2002) “Evolution of Social Behavior: Individual and Group Selection Models.” Journal of Economic Perspectives 16: 231–238.
-   Bergstrom, C. T. and M. Lachmann (1998) “Signaling Among Relatives III. Talk is Cheap.” Proceedings of the National Academy of Sciences USA 95: 5200–5105.
-   Berleman, J. E., J. Scott, T. Chumley, and J. R. Kirby (2008) “Predataxis Behavior in Myxococcus Xanthus.” Proceedings of the National Academy of Sciences USA 105: 17127–17132.
-   Berninghaus, S., K.-M. Ehrhart, M. Ott, and B. Vogt (2007) “Evolution of Networks–an Experimental Analysis.” Journal of Evolutionary Economics 17: 317–347.
-   Bickerton, D. (1990) Language and Species. Chicago: University of Chicago Press.
-   Bjornerstedt, J. and J. Weibull (1995) “Nash Equilibrium and Evolution by Imitation.” In K. Arrow et al. (eds.), 155–71, The Rational Foundations of Economic Behavior. New York: Macmillan.
-   Bloch, F. and M. Jackson (2007) “The Formation of Networks with Transfers among Players.” Journal of Economic Theory 133: 83–110.
-   Bloch, F. and B. Dutta (2009) “Communication Networks with Endogenous Link Strength.” Games and Economic Behavior 66: 39–56.
-   Blume, A. (2000) “Coordination and Learning with a Partial Language.” Journal of Economic Theory 95: 1–36.
-   Blume, A., D. DeJong, Y.-G. Kim, and G. B. Sprinkle (1998) “Experimental Evidence on the Evolution of the Meaning of Messages in Sender-Receiver Games.” American Economic Review 88: 1323–1340.
-   Blume, A., D. DeJong, Y.-G. Kim, and G. B. Sprinkle (2001) “Evolution of Communication with Partial Common Interest.” Games and Economic Behavior 37: 79–120.
-   [@Blume2002] ~~Blume, A., D. DeJong, G. Neumann, N. E. Savin (2002) “Learning and Communication in Sender-Receiver Games: An Econometric Investigation.” Journal of Applied Econometrics 17: 225–247.~~
-   Borgers, T. and R. Sarin (1997) “**Learning through Reinforcement and the Replicator Dynamics**.” Journal of Economic Theory 74: 235–265.
-   Borgers, T. and R. Sarin (2000) “Naive Reinforcement Learning with Endogenous Aspirations.” International Economic Review 41: 921–950.
-   Brandman, O. and T. Meyer (2008) “Feedback Loops Shape Cellular Signals in Space and Time.” Science 322: 390–395. Brentano, F. (1874) Psychology from an Empirical Standpoint. London: Routledge.
-   Brown, G. W. (1951) “Iterative Solutions of Games by Fictitious Play.” In Activity Analysis of Production and Allocation, ed. T. C. Koopmans. New York: Wiley.
-   Bshary, R., A. Hohner, K. Ait-el-Djoudi, and H. Fricke (2006) “Interspecific Communicative and Coordinated Hunting between Groupers and Giant Moray Eels in the Red Sea.” PLoS Biology 4:2393–2398 4:e431, DOI:10:1371/journal.pbio.0040431.
-   Callander, S. and C. R. Plott (2005) “Principles of Network Development and Evolution: An Experimental Study.” Journal of Public Economics 89: 1469–1495.
-   Camerer, C. and T-H. Ho (1999) “Experience Weighted Attraction Learning in Normal Form Games.” Econometrica 67: 827–874.
-   Campbell, G. (2003) Lucretius on Creation and Evolution. Oxford: Oxford University Press.
-   Charrier, I. and C. B. Sturdy (2005) “Call-Based Species Recognition in the Black-Capped Chickadees.” Behavioural Processes 70: 271–281.
-   Cheney, D. and R. Seyfarth (1990) How Monkeys See the World: Inside the Mind of Another Species. Chicago: University of Chicago Press.
-   Cross, J. G. (1973) “A Stochastic Learning Model of Economic Behavior.” Quarterly Journal of Economics 87: 239–266.
-   Crawford, V. and J. Sobel (1982) “Strategic Information Transmission.” Econometrica 50: 1431–1451.
-   Cubitt, R. and R. Sugden (2003) “Common Knowledge, Salience and Convention: A Philosophical Reconstruction of David Lewis’ Game Theory.” Economics and Philosophy 19:175–210.
-   Donaldson, M. C., M. Lachmann, and C. T. Bergstrom (2007) “The Evolution of Functionally Referential Meaning in a Structured World.” Journal of Theoretical Biology 246: 225–233.
-   Dretske, F. (1981) Knowledge and the Flow of Information. Cambridge: MIT Press.
-   Dugatkin, L. A. (1997) Cooperation Among Animals: An Evolutionary Perspective. Oxford: Oxford University Press.
-   Dyer, F. C. and T. D. Seeley (1991) “Dance Dialects and Foraging Range in three Asian Honey Bee Species.” Behavioral Ecology and Sociobiology 28: 227–233.
-   Edwards, W. (1961) “Probability Learning in 1000 Trials.” Journal of Experimental Psychology 62: 385–394.
-   Estes, W. K. (1950) “Toward a Statistical Theory of Learning.” Psychological Review 57: 94–107.
-   Evans, C. S., C. L. Evans and P. Marler (1994) “On the Meaning of Alarm Calls: Functional Reference in an Avian Vocal System.” Animal Behavior 73: 23–38.
-   Falk, A. and M. Kosfeld (2003) “It’s All About Connections: Evidence on Network Formation.” IEW Working Paper 146. University of Zurich.
-   Feltovich, N. (2000) “Reinforcement-Based vs. Belief-Based Learning Models in Experimental Asymmetric-Information Games.” Econometrica 68: 605–641.
-   Flache, A. and M. Macy (2002) “Stochastic Collusion and the Power Law of Learning.” Journal of Conflict Resolution 46: 629–653.
-   Floridi, L. (1997) “Skepticism, Animal Rationality, and the Fortune of Chrysippus’ Dog.” Archiv fu¨r Geschichte der Philosophie 79: 27–57.
-   Frede, D. and B. Inwood (2005) Language and Learning: Philosophy of Language in the Hellenistic Age. Cambridge: Cambridge University Press. Fudenberg,
-   D. and D. Levine (1998) A Theory of Learning in Games. Cambridge, MA: MIT Press.
-   Galeotti, A. and S. Goyal (2008) “The Law of the Few.” Working paper, University of Essex.

-   Gazda, S., R. C. Connor, R. K. Edgar, and F. Cox (2005) “A Division of Labour with Role Specialization in Group-hunting Bottlenose Dolphins (Tursiops truncatus) off Cedar Key, Florida.” Proceedings of the Royal Society B 272: 135–140.
-   Gentner, T. Q., K. M. Fenn, D. Margoliash, and H. C. Nusbaum (2006) “Recursive Syntactic Pattern Learning by Songbirds.” Nature 440: 1204–1207.
-   Gettier, E. (1963) “Is Justified True Belief Knowledge?” Analysis 23:121–123.
-   Godfrey-Smith, P. (1989) “Misinformation.” Canadian Journal of Philosophy 19: 522–550.
-   Godfrey-Smith, P. (2000a) “On the Theoretical Role of Genetic Coding.” Philosophy of Science 67: 26–44.
-   Godfrey-Smith, P. (2000b) “Information, Arbitrariness and Selection: Comments on Maynard-Smith.” Philosophy of Science 67: 202–207.
-   Good, I. J. (1950) Probability and the Weighing of Evidence. London: Charles Griffin.
-   Good, I. J. (1983) Good Thinking: The Foundations of Probability and its Applications. Minneapolis: University of Minnesota Press.
-   Gould, J. L. (1975) “Honey Bee Recruitment: the Dance Language Controversy.” Science 189: 685–693.
-   Gould S. J., and N. Eldredge (1977) “Punctuated Equilibria: The Tempo and Mode of Evolution reconsidered.” Paleobiology 3: 115–151.
-   Goryachev, A. B., D. J. Toh, and T. Lee (2006) “Systems Analysis of a Quorum Sensing Network: Design Constraints Imposed by the Functional Requirements, Network Topology and Kinetic Constants.” BioSystems 83: 178–187.
-   Goyal, S. (2007) Connections: An Introduction to the Economics of Networks. Princeton: Princeton University Press.
-   Grice, H. P. (1957) “Meaning.” Philosophical Review 66: 377–388.
-   Grice, H. P. (1975) “Logic and Conversation.” In Syntax and Semantics, vol. 3, ed. P. Cole and J. L. Morgan, 41–58. New York: Academic Press.
-   Grice, H. P. (1989) Studies in the Way of Words. Cambridge, MA: Harvard University Press.
-   Griffiths, P. E. (2001) “Genetic Information: A Metaphor in Search of a Theory.” Philosophy of Science 68: 394–412.
-   Grim, P., P. St. Denis, and T. Kokalis (2002) “Learning to Communicate: The Emergence of Signaling in Spatialized Arrays of Neural Nets.” Adaptive Behavior 10: 45–70.
-   Grim, P., T. Kokalis, A. Alai-Tafti, A., and N. Kilb (2000) “Evolution of Communication in Perfect and Imperfect Worlds.” World Futures: The Journal of General Evolution 56: 179–197.
-   Grim, P., T. Kokalis, A. Alai-Tafti, N. Kilb, and P. St. Denis (2004) “Making Meaning Happen.” Journal of Experimental and Theoretical Artificial Intelligence 16: 209–243.
-   Gyger, M., P. Marler, and R. Pickert (1987) “Semantics of an Avian Alarm Call System: The Male Domestic Fowl,
-   Gallus Domesticus.” Behavior 102: 15–20. 184
-   Hadeler, K. P. (1981) “Stable Polymorphisms in a Selection Model with Mutation.” SIAM Journal of Applied Mathematics 41: 1–7.
-   Hailman, J., M. Ficken, and R. Ficken (1985) “The ‘Chick-a-dee’ calls of Parus atricapillus.” Semiotica 56: 191–224.
-   Hamilton, W. D. (1963) “The Evolution of Altruistic Behavior.” American Naturalist 97: 354–356.
-   Hamilton, W. D. (1964) “The Genetical Evolution of Social Behavior I and II.” Journal of Theoretical Biology 7: 1–52.
-   Hamilton, W. D. (1967) “Extraordinary Sex Ratios.” Science 156: 477–488.
-   Hamilton, W. D. (1971) “Selection of Selfish and Altruistic Behavior in Some Extreme Models.” In Man and Beast, ed. J. F. Eisenberg and W. S. Dillon, 59–91. Washington, D.C.: Smithsonian Institution Press.
-   Hamilton, W. D. (1995) Narrow Roads of Gene Land. vol. 1: Evolution of Social Behavior. New York: W. H. Freeman.
-   Harley, C. B. (1981) “Learning the **Evolutionarily Stable Strategy**.” Journal of Theoretical Biology 89: 611–633.
-   Harms, W. F. (2004) Information and Meaning in Evolutionary Processes. Cambridge: Cambridge University Press.
-   Hauert, C., S. De Monte, J. Hofbauer, and K. Sigmund (2002) “Volunteering as Red Queen Mechanism for Cooperation in Public Goods Games.” Science 296, 1129–1132.
-   Hauser, M. D. (1988) “How Infant Vervet Monkeys Learn to Recognize Starling Alarm Calls: The Role of Experience.” Behavior 105: 187–201.
-   Hauser, M. D. (1997) The Evolution of Communication. Cambridge, MA: MIT Press.
-   Hauser, M. D., N. Chomsky, and W. T. Fitch (2002) “The Faculty of Language: What is it, Who has it, and How did it Evolve.” Science 298: 1569–1579.
-   Hebb, D. (1949) The Organization of Behavior. New York: Wiley.
-   Herman, L. M., D. G. Richards, and J. P. Wolz (1984) “Comprehension of Sentences by Bottle-Nosed Dolphins.” Cognition 16: 129–219.
-   Ho, T. H., X. Wang, and C. Camerer (2008) “Individual differences in EWA Learning with Partial Payoff Information.” The Economic Journal 118: 37–59.
-   Hofbauer, J. (1985) “The Selection-Mutation Equation.” Journal of Mathematical Biology. 23: 41–53.
-   Hofbauer, J. and S. Huttegger (2008) “Feasibility of Communication in Binary Signaling Games.” Journal of Theoretical Biology 254: 843–849.
-   Hojman, D. A. and A. Szeidl (2008) “Core and Periphery in Networks.” Journal of Economic Theory. 139: 295–309.
-   Holland, J. (1975) Natural and Artificial Systems. Ann Arbor, Michigan: University of Michigan Press.
-   Holldobler, B. and E. O. Wilson (1990) The Ants. Cambridge, MA:
-   Belknap. Hoppe, F. M. (1984) “Polya-like Urns and the Ewens Sampling Formula.” Journal of Mathematical Biology 20: 91–94.
-   Hopkins, E. (2002) “Two Competing Models about How People Learn in Games.” Econometrica 70, 2141–2166.
-   Hopkins, E. and M. Posch (2005) “Attainability of Boundary Points under Reinforcement Learning.” Games and Economic Behavior 53: 110–125. Hume, D. (1739) A Treatise of Human Nature. London: John Noon.
-   Hurford, J. (1989) “Biological Evolution of the Saussurean Sign as a Component of the Language Acquisition Device.” Lingua 77: 187–222.
-   Huttegger, S. (2007a) “Evolution and the Explanation of Meaning.” Philosophy of Science 74: 1–27.
-   Huttegger, S. (2007b) “Evolutionary Explanations of Indicatives and Imperatives.” Erkenntnis 66: 409–436.
-   Huttegger, S. (2007c) “Robustness in Signaling Games.” Philosophy of Science 74: 839–847.
-   Huttegger, S. and B. Skyrms (2008) “Emergence of Information Transfer by Inductive Learning.” Studia Logica 89: 237–256.
-   Huttegger, S., B. Skyrms, R. Smead, and K. Zollman (2009) “Evolutionary Dynamics of Lewis Signaling Games: Signaling Systems vs. Partial Pooling.” Synthese. DOI: 10.1007/s11229–009–9477–0
-   Izquierdo, L., D. Izquierdo, N. Gotts, and J. G. Polhill (2007) “Transient and Asymptotic Dynamics of Reinforcement Learning in Games.” Games and Economic Behavior 61: 259–276. 186 SIGNALS: EVOLUTION, LEARNING, AND INFORMATION
-   Jackendoff, R. (2002) Foundations of Language. Oxford: Oxford University Press.
-   Jackson, M. (2008) Social and Economic Networks. Princeton: Princeton University Press.
-   Jackson, M. and A. Watts (2002) “On the Formation of Interaction Networks in Social Coordination Games.” Games and Economic Behavior 41: 265–291.
-   Kavanaugh, M. (1980) “Invasion of the Forest by an African Savannah Monkey: Behavioral Adaptations.” Behavior 73: 239–60. Kirby, S. (2000) “Syntax without Natural Selection: How Compositionality Emerges from Vocabulary in a Population of Learners.” In The Evolutionary Emergence of Language, ed. C. Knight, 303–323. Cambridge: Cambridge University Press.
-   Kirby, S. (2007) “The Evolution of Meaning-Space Structure through Iterated Learning.” In Emergence of Communication and Language, ed. C. Lyon et al., 253–268. Berlin: Springer Verlag.
-   Kirkup, B. C. and M. A. Riley (2004) “Antibiotic-Mediated Antagonism Leads to a Bacterial Game of Rock-Paper-Scissors in vivo.” Nature 428: 412–414.
-   Komarova, N. and P. Niyogi (2004) “Optimizing the Mutual Intelligibility of Linguistic Agents in a Shared World.” Artificial Intelligence 154: 1–42.
-   **Komarova, N., P. Niyogi, and M. Nowak (2001) “The Evolutionary Dynamics of Grammar Acquisition.” Journal of Theoretical Biology 209: 43–59.**
-   Kosfeld, M. (2004) “Economic Networks in the Laboratory.” Review of Network Economics 3: 20–41.
-   Kullback, S. and R. A. Leibler (1951) “On Information and Sufficiency.” Annals of Mathematical Statistics 22: 79–86.
-   Kullback, S. (1959) Information Theory and Statistics. New York: John Wiley.
-   Levi-Strauss, C. (1969) The Elementary Structures of Kinship. Boston: Beacon Press.
-   Lewis, D. K. (1969) Convention. Cambridge, MA: Harvard University Press.
-   Liggett, T. M. and S. Rolles (2004) “An Infinite Stochastic Model of Social Network Formation.” Stochastic Processes and their Applications 113: 65–80.
-   Lindley, D. (1956) “On a Measure of the Information Provided by an Experiment.” The Annals of Mathematical Statistics 27: 986–1005.
-   Luce, R. D. (1959) Individual Choice Behavior. John Wiley & Sons: New York.
-   Macedonia, J. M. (1990) “What is Communicated in the Antipredator Calls of Lemurs: Evidence from Antipredator Call Playbacks to Ringtailed and Ruffed Lemurs.” Ethology 86: 177–190.
-   McKinnon, S. (1991) From a Shattered Sun. Madison: University of Wisconsin Press.
-   Macy, M. (1991) “Learning to Cooperate: Stochastic and Tacit Collusion in Financial Exchange.” American Journal of Sociology 97: 808–843.
-   Macy, M. and A. Flache (2002) “Learning Dynamics in Social Dilemmas.” Proceedings of the National Academy of Sciences of the USA 99: 7229– 7236.
-   Marden, J. P., H. P. Young, G. Arslan, and J. S. Shamma (2009) “Payoffbased dynamics for Multiplayer Weakly Acyclic Games.” SIAM Journal on Control and Optimization 48: 373–396. 188
-   Mayor, J. (1898) “King James I On the Reasoning Faculty in Dogs.” The Classical Review 12: 93–96.
-   McGregor, P. (2005) Animal Communication Networks. Cambridge University Press: Cambridge.
-   Merin, A. (1999) “Information, Relevance, and Social Decisionmaking: Some Principles and Results of Decision-Theoretic Semantics.” In L. Moss, J. Ginzburg, M. de Rijke (eds.), 179–221, Logic, Language, and Computation, vol. 2. Stanford: CSLI.
-   Miller, M. B. and B. Bassler (2001) “Quorum Sensing In Bacteria.” Annual Review of Microbiology 55: 165–199.
-   Millikan, R. G. (1984) Language, Thought and Other Biological Categories. Cambridge, MA: MIT Press.
-   Milo, R., S. Shen-Orr, S. Itzkovitz, N. Kashtan, D. Chklovskii, and U. Alon (2002) “Network Motifs: Simple Building Blocks of Complex Networks.” Science 298: 824–827.
-   [@doi:10.1073/pnas.96.14.8028] ~~**Nowak, M. A. and D. Krakauer (1999) “The Evolution of Language.” Proceedings of the National Academy of Sciences of the USA 96: 8028–8033.**~~
-   Nowak, M., J. Plotkin, and D. Krakauer (1999) “The Evolutionary Language Game.” Journal of Theoretical Biology 200: 147–162.
-   Nowak, M. and K. Sigmund (1993) “A Strategy of Win-stay, Lose-shift that Outperforms Tit-for-tat in the Prisoner’s Dilemma Game.” Nature 364: 56–58.
-   Oliphant, M. (1994) “The Dilemma of Saussurean Communication.” Biosystems 37: 31–38.
-   Othmer, H. G. and A. Stevens (1997) “Aggregation, Blow Up and Collapse: The ABC’s of Taxis in Reinforced Random Walks.” SIAM Journal on Applied Mathematics 57: 1044–1081.
-   Papineau, D. (1984) “Representation and Explanation.” Philosophy of Science 51: 550–72.
-   Papineau, D. (1987) Reality and Representation. Oxford: Blackwell.
-   Parikh, P. (2001) The Use of Language. Stanford: CSLI.
-   Pawlowitsch, C. (2008) “Why Evolution Does Not Always Lead to an Optimal Signaling System.” Games and Economic Behavior 63: 203–226.
-   Pemantle, R. (1990) “Nonconvergence to Unstable Points in Urn Models and Stochastic Approximations.” Annals of Probability 18: 698–712.
-   Pemantle, R. (2007) “A Survey of Random Processes with Reinforcement.” Probability Surveys 4: 1–79.
-   Pemantle, R. and B. Skyrms (2004a) “Network Formation by Reinforcement Learning: The Long and the Medium Run.” Mathematical Social Sciences 48: 315–327.
-   Pemantle, R. and B. Skyrms (2004b) “Time to Absorption in Discounted Reinforcement Models” Stochastic Processes and Their Applications 109: 1–12.

-   Quine, W. V. O. (1936) “Truth by Convention.” In Philosophical Essays for A. N. Whitehead, ed. O. H. Lee. 90–124.
-   Quine, W. V. O. (1969) “Epistemology Naturalized.” In Ontological Relativity and Other Essays. New York: Columbia University Press.
-   Rainey, H. J., K. Zuberbu¨hler, and P. J. B. Slater (2004) “Hornbills Can Distinguish between Primate Alarm Calls.” Proceedings of the Royal Society of London B 271: 755–759.
-   J. Riley, R. U. Greggers, A. D. Smith, D. R. Reynolds, and R. Menzel (2005) “The Flight Paths of Honeybees Recruited by the Waggle Dance.” Nature 435: 205–207.
-   Robbins, H. (1952) “Some Aspects of the Sequential Design of Experiments.” Bulletin of the American Mathematical Society 58: 527–535. 190
-   van Rooy, Robert. (2003) “Questioning to Resolve Decision Problems.” Linguistics and Philosophy 26:727–763.

-   Russell, B. (1921) The Analysis of Mind. (Lecture X) London: George Allen and Unwin.

-   Russell, B. (1948) Human Knowledge, Its Scope and Limits. New York: Simon and Schuster.

-   Salmon, T. C. (2001) “An Evaluation of Econometric Models of Adaptive Learning.” Econometrica 1597–1628.

-   Schlag, K. (1998) “Why Imitate and If So, How? A Bounded Rational Approach to Many Armed Bandits.” Journal of Economic Theory 78, 130–156.

-   Schreiber, Sebastian J. (2001) “Urn Models, Replicator Processes, and Random Genetic Drift”, SIAM Journal on Applied Mathematics, 61.6: 2148–2167.

-   Schultz, W. (2004) “Neural Coding of Basic Reward Terms of Animal Learning Theory, Game Theory, Microeconomics and Behavioural Ecology.” Current Opinion in Neurobiology 14:139–147.

-   Searcy, W. A. and S. Nowicki (2005) The Evolution of Animal Communication: Reliability and Deception in Signaling Systems. Princeton: Princeton University Press.

-   **Selten, R. and W. Massimo (2007) “The Emergence of Simple Languages in an Experimental Coordination Game.” Proceedings of the National Academy of Sciences of the USA 104: 7361–7366.**

-   Seyfarth, R. M. and D. L. Cheney (1990) “The Assessment by Vervet Monkeys of Their Own and Other Species’ Alarm Calls.” Animal Behavior 40: 754–764.

-   **Shannon, C. (1948) “A Mathematical Theory of Communication.” The Bell System Mathematical Journal 27: 379–423, 623–656.**

-   **Shannon, C. and W. Weaver (1949) The Mathematical Theory of Communication. Urbana: University of Illinois Press.**

-   Shreiber, S. (2001) “Urn Models, Replicator Processes and Random Genetic Drift.” SIAM Journal on Applied Mathematics 61: 2148–2167.

-   Sinervo, B. and C. M. Lively (1996) “The Rock-Paper-Scissors Game and the Evolution of Alternative Male Strategies.” Nature 380: 240–243.

-   Skyrms, B. (1996) Evolution of the Social Contract. Cambridge: Cambridge University Press. Skyrms, B. (1998) “Salience and Symmetry-Breaking in the Evolution of Convention.” Law and Philosophy 17: 411–418.

-   Skyrms, B. (1999) “Stability and Explanatory Significance of Some Simple Evolutionary Models.” Philosophy of Science 67: 94–113.

-   Skyrms, B. (2000) “Evolution of Inference.” In Dynamics of Human and Primate Societies, ed. Tim Kohler and George Gumerman, 77–88. New York: Oxford University Press.

-   Skyrms, B. (2004) The Stag Hunt and the Evolution of Social Structure. Cambridge: Cambridge University Press.

-   Skyrms, B. (2005) “Dynamics of Conformist Bias.” Monist 88: 260–269.

-   Skyrms, B. (2007) “Dynamic Networks and the Stag Hunt: Some Robustness Considerations.” Biological Theory 2: 7–9.

-   Skyrms, B. (2009) “Evolution of Signaling Systems with Multiple Senders and Receivers.” Philosophical Transactions of the Royal Society B doi:10.1098/rstb.2008.0258, 364: 771–779.

-   Skyrms, B. (2009) “Presidential Address: Signals.” Philosophy of Science 75:489–500.

-   Skyrms, B. and R. Pemantle (2000) “A Dynamic Model of Social Network Formation.” Proceedings of the National Academy of Sciences of the USA. 97: 9340–9346 192

-   Skyrms, B. and S. L. Zabell (forthcoming) “Inventing New Signals.”

-   Slobodchikoff, C. N., J. Kiriazis, C. Fischer, and E. Creef (1991) “Semantic Information Distinguishing Individual Predators in the Alarm Calls of Gunnison’s Prairie Dogs.” Animal Behaviour 42: 713–719.

-   Smith, A. (1983) \[1761\] Considerations Concerning the First Formation of Languages. Reprinted in Lectures on Rhetoric and Belles Lettres, ed. J. C. Bryce. Oxford: Oxford University Press.

-   Snowdon, C. T. (1990) “Language Capacities of Nonhuman Animals.” Yearbook of Physical Anthropology 33: 215–243.

-   Sorabji, R. (1993) Animal Minds and Human Morals: The Origins of the Western Debate. Ithaca: Cornell University Press.

-   Stander, P. E. (1990s) “Cooperative Hunting in Lions: The Role of the Individual.” Behavioral Ecology and Sociobiology 29: 445–454.

-   Stanford, P. K. (2007) Exceeding Our Grasp. Oxford: Oxford University Press.


-   Sterelny, K. (2000) “The ‘Genetic Program’ Program: A Commentary on Maynard-Smith on Information in Biology.” Philosophy of Science 67: 195–201.

-   Sterelny, K. (2003) Thought in a Hostile World: The Evolution of Human Cognition. Oxford: Blackwell.

-   Struhsaker, T. T. (1967) “Auditory Communication among Vervet Monkeys Cercopithecus aethiops.” In Social Communication among Primates, ed. S.A. Altmann, 281–324. Chicago: University of Chicago Press.

-   Sugden, R. (2005) The Economics of Rights, Co-operation and Welfare (Basingstoke: Macmillan).

-   Suppes, P. and R. Atkinson (1960) Markov Learning Models for Multiperson Interactions. Palo Alto, CA: Stanford University Press.

-   Taga, M. E. and B. L. Bassler (2003) “Chemical Communication Among Bacteria.” Proceedings of the National Academy of Sciences of the USA 100 Suppl. 2, 14549–14554.

-   [@Taylor1978ESS]


-   Thorndike, E. L. (1911) Animal Intelligence. New York: Macmillan.

-   Thorndike, E. L. (1927) “The Law of Effect.” American Journal of Psychology 39: 212–222.

-   **Trapa, P. and M. Nowak (2000) “Nash Equilibria for an Evolutionary Language Game.” Journal of Mathematical Biology 41: 172–188.**

-   Vanderschraaf, P. (1998) “Knowledge, Equilibrium and Convention.” Erkenntnis 49: 337–369.

-   [@Wagner2013Costly]

-   **Wagner, E. (2009) “Communication and Structured Correlation.” Erkenntnis doi 10.1007/s10670–009–9157–y.**

-   Wa¨rneryd, K. (1993) “Cheap Talk, Coordination, and Evolutionary Stability.” Games and Economic Behavior 5: 532–546.

-   Watts, A. (2001) “A Dynamic Model of Network Formation.” Games and Economic Behavior 34: 331–341.

-   Weber, R. and C. Camerer (2003) “Cultural Conflict and Merger Failure: An Experimental Approach.” Management Science 49: 400–415.

-   Wei, L. and S. Durham (1978) “The Randomized Play-the-winner Rule in Medical Trials.” Journal of the American Statistical Association 73: 840–843.

-   Young, H. P. (2009) “Learning by Trial and Error.” Games and Economic Behavior 65: 626–643. 194

-   Zabell, S. L. (1992) “Predicting the Unpredictable.” Synthese 90: 205–232.

-   Zabell, S. L. (2005) Symmetry and Its Discontents: Essays in the History of Inductive Probability. Cambridge: Cambridge University Press.

-   Zeeman, E. C. (1980) “Population Dynamics from Game Theory.” In Global Theory of Dynamical Systems, Springer Lecture Notes on Mathematics 819.

-   Zollman, K. (2005) “Talking to Neighbors: The Evolution of Regional Meaning.” Philosophy of Science 72: 69–85

-   Zuidema, W. (2003) “Optimal Communication in a Noisy and Heterogeneous Environment.” In Proceedings Lecture Notes on Artificial Intelligence v. 2801 Berlin: Springer 553–563.
