---
title: "OCR - Brain Dump"
date: 2024-02-25
draft: False
categories: [linkage,brain dump, OCR]
---

- I keep coming back to OCR.
- OCR is a "Solved problem" but you can never get a decent OCR of your page....
- Would be nice to have
  1. some pdf image extraction code block in python.
  1. some tools for generating text data in python - ideally with KL divergence to a corpus
  2. some [OCR building blocks](/posts/2022/28-02-2024-ocr/28-02-2024-ocr.html) in python
  3. font manifold blocks in python + CLIPS capabilities
    - make a manifold
    - condition it
    - a point at [font1-weight,font2-weight]
  4. the power of off policy RL for this issue

## Articles

-   Working of OCR articles by [**Susmith Reddy**](https://susmithreddyvedere.medium.com/?source=user_profile-------------------------------------)

    -   [Pre-Processing in OCR ^<i class="bi bi-medium"></i>^](https://towardsdatascience.com/pre-processing-in-ocr-fc231c6035a7) covers Binarization, Skew Correction, Noise Removal, Thinning and Skeletonization

    -   [Segmentation in OCR ^<i class="bi bi-medium"></i>^](https://towardsdatascience.com/segmentation-in-ocr-10de176cf373) - Histogram Projection Method

-   Document Scanner app - [Text Segmentation ^<i class="bi bi-medium"></i>^](https://arthurflor23.medium.com/text-segmentation-b32503ef2613) ^[bibliography]{.badge .rounded-pill .bg-success}^ [code ^<i class="bi bi-github"></i>^](https://github.com/arthurflor23/text-segmentation) by [Arthur Flor](https://arthurflor23.medium.com/) some interesting algorithm. 

- [Image Filters in Python ^<i class="bi bi-medium"></i>^](https://towardsdatascience.com/image-filters-in-python-26ee938e57d2) [code ^<i class="bi bi-github"></i>^](https://github.com/m4nv1r/medium_articles/blob/master/Image_Filters_in_Python.ipynb)

## PDF extraction

- [Extract text in a rectangle from pdf - Python ^<i class="bi bi-stack-overflow"></i>^](https://stackoverflow.com/questions/60202963/extract-text-in-a-rectangle-from-pdf-python)
- Pdftocairo [man page](https://linuxcommandlibrary.com/man/pdftocairo)
  
## Font Manifolds

- [Learning a Manifold of Fonts Supplemental Material](http://vecg.cs.ucl.ac.uk/Projects/projects_fonts/papers/siggraph14_learning_fonts_supp.pdf)


## Chat With AI:

- [Chat GPT](https://chat.openai.com/share/7bcaafc9-49bd-41f1-ac57-48539bde1c55)

