---
date: 2025-03-11
title: The roles of Partial pooling and mixed strategies in the Lewis signaling game
subtitle: a game theoretic perspective
categories: [emergent languages, lewis signaling game, game theory]
keywords: [signaling games, partial pooling, mixed strategies, Lewis signaling game]
bibliography: ./bibliography.bib
---

Today I posit a couple of questions on the Lewis signaling game. 

1. Are there useful^[for signaling agents] interpretation of some equilibria in the Lewis signaling game that are not fully separable equilibria?
1. Are some partial pooling equilibria more useful than others?
1. Might agents prefer to employ partial pooling strategies over fully separable equilibria?
1. Might agents want to employ mixed strategies?

## Partial Pooling

let's imagine we have this signaling system

```{python}
#| label: tbl-predators
#| tbl-cap: predators and their signals

from IPython.display import Markdown
from tabulate import tabulate

lexicon = {}

lexicon['falcon']  = '000 00'
lexicon['hawk']    = '000 01'
lexicon['eagle']   = '000 10'
lexicon['panther']     = '111 00'
lexicon['leopard'] = '111 01'
lexicon['jaguar'] =  '111 11'

# converting the lexicon to a table
table = [[k, v] for k, v in lexicon.items()]


Markdown(tabulate(
  table, 
  headers=["Pre-Linguistic- Object", "signal"]
))
```


A spider monkey, the response for a raptor might be dealt with by descending from the top of trees to the second or third level of the canopy. A cat might be dealt with by moving to the top of the tree.

Clearly though there is little time to waste. So the monkey should be moving with ataractic as soon as it hears either '000' or '111'. 

But '000' and '111' are not signals they are artifacts of the lexicon. Or are they?

```{python}
#| label: tbl-predators-categories
#| tbl-cap: predators categories and their signals 

lexicon = {}

lexicon['raptor']  = '000 '
lexicon['hawk']    = '000 '
lexicon['eagle']   = '000 '
lexicon['raptor']  = '000 '

lexicon['feline']  = '111'
lexicon['panther'] = '111'
lexicon['leopard'] = '111'
lexicon['jaguar']  = '111'

# converting the lexicon to a table
table = [[k, v] for k, v in lexicon.items()]

Markdown(tabulate(
  table, 
  headers=["Pre-Linguistic- Object", "signal"]
))
```

This is only a partial pooling equilibrium.
IT doesn't allow the monkeys to distinguish between the different types of raptors or felines.

We care about it because it can serve the monkeys as a starting point for more complex signaling systems like the one above that are compatible with the semantics captured in this one - that there are two groups with two urgent actions. The has an implicit prefix that is compatible with the semantics of the category. The prefix arises in part from choice of using prefix codes inspired by Huffman codes [@Huffman1952Method]


If all the monkeys care about is the up down response the partial pooling equilibrium is all they need to learn. If they have benefits at distinguishing between the different types of predators, when they are at a distance, they would need to learn a more complex signaling system.

But when threat is imminent, the partial pooling equilibrium is 
what they should be using both as sender and as receiver.

Also it is conceivable that a number of signaling systems compatible with #tbl-predators-categories might arrise by further spontaneous symmetry breaking once this equilibrium is established. with #tbl-predators being one such option.

Now in most research on simple signaling system we often emphsize how signaing systems can arise  via spontaneous symmetry breaking. Suppose the monkey learn the following signaling system.

```{python}
#| label: tbl-predators-incompatible
#| tbl-cap: predators and their signals 2

from IPython.display import Markdown
from tabulate import tabulate

lexicon = {}

lexicon['falcon']  = '000 00'
lexicon['panther']    = '000 01'
lexicon['eagle']   = '000 10'
lexicon['hawk'] = '111 00'
lexicon['leopard'] = '111 01'
lexicon['jaguar']  = '111 11'

# converting the lexicon to a table
table = [[k, v] for k, v in lexicon.items()]


Markdown(tabulate(
  table, 
  headers=["Pre-Linguistic- Object", "signal"]
))
```

Here hawk and panther have been swapped. This system lacks the structure of the partial pooling equilibrium. The prefix no longer maps to the category.

The spider monkeys in this case might exhibit reduced fitness as a group as they have to hear the full signal before they can respond. 

One way out is for them to use a mixed strategy. If they alternate between two systms they can get the benefits of both.

The problem here is that in game theory we generaly consider such a strategy as 10% of one and 80% of the other and some randomiser picking between the two. Here we want the choice to be
deterministic. Leaving aside the formal question we can see that 
on the path to learning a full signaling system agents may pass though many states in which they do not have a full signaling system and may be only equipped with partial pooling equilibria.

Another view might be as follows:


```{python}
#| label: tbl-predators-partial
#| tbl-cap: predators and their signals 3

from IPython.display import Markdown
from tabulate import tabulate

lexicon = {}

lexicon['falcon']  = '000 00'
lexicon['jaguar']    = '111 00'


# converting the lexicon to a table
table = [[k, v] for k, v in lexicon.items()]


Markdown(tabulate(
  table, 
  headers=["Pre-Linguistic- Object", "signal"]
))
```


This suggest a new insight into complex signaling systems. Hierarchies can learned early



## Quick Brain dump

as time is short here are a bunch of points for further exploration

1. the partial pooling equilibrium correspond to subsets of bayesian senders.
1. we show a category but we mean full hierarchies of categories. These are a preorder and thus imply a topological structure on the state space. This is  the Alexandrov Topology (Topology from a Preorder)
1. we can learn hierarchies of categories by learning an representative. But learning a representative for each category is also the basis of a clarifier. A classifier is also a type of decision we want to cary out on states to determine the action we should take. In this sense we are talking about a process for rough to fine specification of semantics.
1. Each hierarchy of categories represents a **semantic symmetry**. Members share a rough semantic meaning but differ in the fine details.
1. We might also repurpose this idea for other symmetries like morpgology and phonology.
1. If each category is imbued with a prefix we end up with many prefixes corresponding to atoms of discourse. If there are not too many we might build words from these prefixes.
1. as there is an increased fitness for languages with prefix and at least certain hierarchies of categories we can see that this may be a desiderata for the evolution of signaling systems. More so we might want an RL algorithm to step between a lattice of such partial pooling equilibria rather then learning by spontaneous symmetry breaking. 
1. This is planning of hierarchies of categories. However in reality we inherit the hierarchies from the state space of from the prelinguistic objects.
1. another form of using mixed strategies is code switching - where we switch between partial pooling equilibria - each learned for a specific sender. At certain points such a code swithing reciever might become promoted to a sender and use the inforamtion in the partial pooling equilibria to infer/plan a full langauge from the differnt langauges it ha learned. This is a form of transfer learning. The result might be a pidgin or a creole depending if the reciever uses a lexicon or a linear function approximat which is a generelization of a lexicon!
1. In my experience in NLP categories are not encoded as a prefix. In fact they are only encoded in a very limited fashion using a suffix like great, greater, greatest. Numbers do tend to have a base 10 encoding but not as clean as a prefix code. Langauges do have many hierarchies encoded into thesauri and wordnets. I think that at some level (e.g. semantic roles labeling) and phrase structure hierarchies can shape langauges evolution. 
1. Why is this type of hierarchies absent from the lexicon of natural Languages?
1. The quest for a perfectly regular interlingua might be shaped by an algorithm that learn to encode thesauri like hierarchies down into the phonetic stratum and via algorithms that jump between partial pooling equilibria. ^[A language with rich yet fully pooling morphology and a thesaurus-like-lexicon]
1. Another point I did not raise is that there are lots more partial equilibria than fully separating equilibria. This suggest that it should be easy for a language 'planner' to find nearly compatible partial pooling equilibria with an existing language.
By switching around the incompatibilities the language can then gain a new categorical prefix and be easier to learn as well as require less processing going forward. 