---
title: Using Competitive Analysis to Benchmark Your Marketing Efforts  Ariel Rosenstein - Similar Web
subtitle: All things data 2016
date: 2015-04-20
draft: true
categories:
    - conference
    - analytics
    - orgenizational behviour
---

Mr Jerbi's Background:  
     Come to web analytics from academia Industry and Management - Scheduling and QA.  
     Recalls that before it was bought by Google Urchin cost $30,000 
 
 
The talk Discusses tools to help integrate  analytics into organizational culture. 
 
 
Motivating Question: 
 
What's a better goal for your company: 
Doubling client acquisition 
Doubling client conversion 
 
Design to optimize 
What's a data driven organization? 
Every improvement starts with measurement? 
Segment and personalize 
Every improvement starts with measurement. 
Measurement frequently utilize 
 
 
split testing (also called A/B testing and Multi variants) 
 
 
voice of the customer (also called panel data) 
The two most common objections to becoming data driven are: 
 
 
 
Enterprise Data bureaucracy is slow to respond - IT\BI cycles are far in exces of  business unit attention span in web marketing contexts) 
Small to medium businesses look for immediate payoffs - most lean orgs do not see longer term ROI of being DD 
Top lessons for DD: 
Everyone has access to the data 
Well defined KPIs 
Every change that launches has usage reports 
The experiment a lot - more ideas see the light of day. 
They are curious and good storytellers 
 
Lesson learned in customer retention: e-commerce and retail clients focus on optimizing checkout pages.  A quick check reveals that most issues are concentrated further up the marketing funnel. 
 
Reverse engineering your customer 
Segments 
Behavioral 
Voice of customer 
Yad2 uses Stickers for off-line 
How does reduce sign-up steps Impact customer quality. 
 
 
Look at your data everyday - most of the insights that need immediate action. 
Give more ppl access to data 
Data stories 
How to prioritize? (Before shatests)  
 
Uplift. 
How many users. 
How easy to test. 
Recommended Resources: 
Click tel 
AnalyticsBytes.com 
Six digress of separation pod-cast 
Avinash Kaushik - www.kaushik.net/avinash/ 
DJ patil data scientist at linked in and now first chief data scientist of us government. 
 
 