---
title: "Composition and Interpretation of Games with the Lewis Signaling Game"
date: "2025-01-14"
categories: [compositionality, emergent languages, reinforcement learning, transfer learning, information theory, linguistics]
keywords: [compositionality, emergent languages, reinforcement learning, transfer learning]
bibliography: ./bibliography.bib
draft: true
---

Game theory is notorious when it comes for application. Here are four quotes from some of the very best practitioners of the field:

> "The problem with game theory is that it assumes that people are rational. But in real life, people are not always rational, and even if they are, they often don’t have the information required to make rational decisions." --- Robert Aumann (Nobel Laureate, 2005)

> "One thing a person cannot do, no matter how rigorous his analysis or heroic his imagination, is to draw up a list of things that would never occur to him."^[(On the unpredictability of strategic interactions beyond game-theoretic models.)] --- Thomas Schelling (Nobel Laureate, 2005)

> "The concept of rationality in game theory is much too narrow to be applied to evolutionary problems."^[Pointing out that biological evolution does not necessarily lead to rational strategic behavior in the game-theoretic sense.] -- John Maynard Smith (Pioneer of Evolutionary Game Theory)

> "Game theory is for proving theorems, not for playing games." ^[Highlighting the gap between theoretical models and their practical application.] --- Ariel Rubinstein (Game Theorist, Behavioral Critic)


The reason for this is that I am interested in understanding if we can in fact interpret how the equilibria of the Lewis game may 



The Lewis signaling game is a simple model of communication between two agents, a sender and a receiver.

One of the interesting aspects of this game is that it can be used by RL agents to learn a emergent language.

However RL agents often have an overriding objective to maximize some reward signal, and the need for an emergent language can be seen as a side effect of this objective.


In this post I will explore the idea of game composition, where the Lewis signaling game is used as a building block for more complex games.

There are a bunch of questions here:

1. Are some or all the equilibria of these extended games interpretable as signaling games?
1. Can we interpret some of the equilibria of the extended game as signaling and other as belonging to the framing game or do we get get equilibria are always a mix of both?
2. If a signaling system emerges will the ability to coordinate in the Lewis game make a difference to the players of The framing game game ? 
3. Can we interpret the equilibria of the extended game in terms of semantics for the emergent language?

My immediate motivation is if one can engineer a signaling game in which there are equilibria that are not necessarily present in the Lewis game. And perhaps more challenging, can we interpret the equilibria of the extended game in terms of semantics for the emergent language?

However in the long run I am interested in understanding if such a compositions can be interpreted as such, if we had a game of life, would we the emergent language be able to support universal semantics and would for any such game of life lead to the emergence of an equivalent language? 

Here are few explanation are in order. 

What is a game of life?

This is an idea that exists in Game Theory, where the idea is that life can be seen as a game between humans. In reality though one would not be able to model life as a single game. So we generally consider simpler games. In this case I have been considering creating simulacra of Low resource languages. There require extending the lewis game with complex states. 

For this setting though I consider a game with a state space with sufficient complexity that would lead to an emergent language that is more complex
It would seem that we may get a more complex

1. What is a universal/general semantics? 
1. What is an equivalent language?
