

### Optimal for Communication

Agents should achieve a high success rate in communication. To better understand signaling and complex signaling systems such as those that emerge out of MARL agent interaction it is necessitate to think in terms of a information-theoretic formulation of the problem. 
The Lewis signaling game is very simple and lacks any assistance in this regard. However 




Agents should be able to communicate with a high success rate. (This is a doorway to information theoretic formulations)

Emergent Communications should have an expected success rate of almost 1. 

Many systems with with expected success rate less then are acceptable however we can tend to see agents reach close to 1.

For optimal communication across a noisy channel we need to consider the following:



Prefix codes are optimal for communication. A prefix code is a type of code system (typically a variable-length code) distinguished by its possession of the "prefix property", which requires that there is no whole code word in the system that is a prefix (initial segment) of any other code word in the system. Adaptive ones like the [Vitter algorithm](https://en.wikipedia.org/wiki/Adaptive_Huffman_coding) appear to be candidates that play well with many of the other desiderata like:
    - brevity (prefix codes as source coding)
    - resilience to errors (channel coding) and adding error detection and correction codes to the message.
    - easy to decode (minimal decoding complexity)
    - able to adapt to new states and changes in the distribution of states.
    - distributional semantics.
    - compositionality.
    - zipfian distributions.


Another more powerful code is arithmatic coding, however this is not practical for a number of reasons.
