
## Resilience to Errors

### Overview

Signaling systems should be resilient to errors.
Errors can be introduced in a number of ways:
- Noise in the channel.
- Errors in the encoding or decoding process.
- Complete and Partial pooling of equilibria.

As we inject errors into the signaling system we should see a number of features from natural languages emerge.

### Insights from Natural Language

Natural language have a number of features that make them resilient to errors:

- Redundancy.
- Distributional semantics.
- Agreement.
- Vowel harmony.

An likely other I am not aware of.

IN [@nowak1999evolution] the authors suggests that the evolution of language is driven by the need to be able to communicate effectively in the presence of errors. They demonstrate that the number of vowels and consonants might increase to a goldilocks zone but beyond a certain threshold the the number of errors will increase making a larger phologoical inventory less likely to evolve.

### Metrics

This property may be measured by the number of errors that can be introduced into the signaling system before it expected success rate drops below a certain threshold.

### Resources

This is based on ...