
### 5. Salient wrt. the distribution of states

Salience means that some equilibria are better than others in terms of some practical concern that affect the fitness of the signaling agents.

e.g. a lognormal or exponential distribution or any distribution other than the uniform distribution of states will have a different optimal signaling system, particularly under (adaptive) prefix coding. 

e.g. is signals have differential costs this will create a parallel mechanism which I consider to be a form of salience. More specifically, if agents use a binary systems with high and low frequency signals. And the low frequency signals are harder for predators to detect then the agents should reduce the number of high frequency signals for predators signaling. On the other hand using a long sequence of low frequency signals will require longer signals and thus also increases the risk of being predation during the signaling process.

This suggest that out of the numerous signaling systems that can arise from the Lewis signaling game some will be more efficient and this may well translate directly into greater fitness for the agents.

However we might as well be clear that for larger state spaces the signals further down the long tail play a less important role in the fitness of agents and therefore one a signaling system or even a partial pooling equilibria is found that captures sufficient quantiles of the state distribution, may confer similar fitness benefits. 

And so it seems that while saliency places an order on all possible signaling equilibria it may have to compete with less salient equilibria that are much easier to learn and use. H

However I think that learnability demands much more on the structure of the state space in terms of prelinguistic objects while saliency is more about the distribution of states. So that if we try to disregard most pathological cases and consider state spaces resembling reality we might expect that the most salient signaling system will also be very learnable.


e.g. is syllables have energy/clarity costs or then the otherwise symmetrical equilibria will now have an order and there is a notion of the most salient signaling system.

Salience is not the same but may also encompass the notions of 

- risk minimizing wrt risks associated with signaling - particularly in the case of risks affecting agent's fitness!
- minimize costs/overhead associated with signaling (in rl there should be a cost associated with each marginal bit that the they send across the channel) 
- Minimizing signal length - This may be the reason why the most common states are the shortest signals - using the unmarked case as the default. This is a form of source coding. (Perhaps this items is more fundamental then risk and salience) It may also be the reason why we have vowel harmony in some languages and why there are other types of redundant agreement in different languages.
- A theorem: if a (natural) language arising via evolution has a redundancy that may be removed without loss of information or via context then it will be compressed and eroded or eliminated given time. Thus such features are that exist and are stable are will have a measurable benefits in terms of communication.

### Diminishing significance of salience

A final thought on salience. We considered a couple of examples like riskiness of predators and their frequency of occurrence. However many other factors may arise that contribute to salience and they may be due to cross-cutting concerns and create a pareto frontier of equilibria. These may be too complex for the agents to process or to plan for. 

Once a language is established in a large enough a population it would become impractical to coordinate all speakers to a equilibria with a greater salience.

salience will be ignored when:
$$
\text{Cost of new-coordination in the population} > \text{Benefits of salience}
$$

This is a form of the principle of least effort. But I doubt we can formalize this in a way that is useful as coordination costs are algorithmic while fitness an emergent property of fitness and depends on the different aspects for salience. These cost are generally incompatible units and thus a challenge to reconcile.


