## The signaling system should be able to generalize to new states

In its simplest for generalization is due to 

1. having reusable templates for recurring patterns 
2. having predictable semantics from those templates

i.e. if sender just picks all the 6 syllables sequences from a set of 10 symbols. Then are a million possible signals and assigns them arbitrarily to a meaning there is no generalization. Learning would require $10^12/2$ steps. 

$$
<\text{s-noun} , \text{declension} > <\text{verb} , \text{conjugation}> <\text{o-noun} , \text{declension} > \qquad \text{three word template}
$$ {#eq-six-syllables-template}

The above template might be used for SVO language with the same six syllables. This three word template is about the level mastered by a 3 year old. 

There agent need to learn 10 subject and 10 subject declensions, 10 verbs and 10 verb conjugations. And 10 objects and 10 object declensions. This is a total of 60 basic symbols that require 1800 steps to learn. But these give rise to a system that is highly predictable. More so if the same noun and declension is used for the subject and object where the learning is only 800 steps.

Three year olds typically have a larger vocabulary than 10 nouns and 10 verbs. But the point is that once this system is established the agent can expand the vocabulary of nouns and verbs without having to learn the declensions and conjugations again and can use to generate vast amount of new sentences with little effort in terms of learning.

### Contextual semantics and generalization

Now I want to point out that while this generlises nicely we have a finite number of words and sentences from this system. This is essentially a tabular lexicon. Also we do not consider the use of context. i.e. 

$$
<aa-ba> <ka-da> <ba-ra>
$$

$$
<aa-ba> <da-ra> <ba-ra>
$$


the nouns in the first sentence are assumed to mean the same things as the nouns in the second sentence. 

If the verbs were such that this semantics was incompatible, then we might assign different meanings to one or both nouns. This would however require more learning steps. 

Note: that in this case $<aa-ba>$ has two meanings $<aa-ba/1>$ $<aa-ba/2>$ and we need to pick the correct one using the verb. Thus there is a tradeoff between the number of meanings and the number of learning steps and the use of context for semantic disambiguation. 

So the problem isn't so much in terms of the learning but it is in terms of making sure we don't create collisions between the different semantics. 
$$
<aa-ba/1> <ka-da> <ba-ra>
$$

$$
<aa-ba/2> <ka-da> <ba-ra>
$$

We have to be sure there aren't some combination like the above that both make sense as we would not be able to tell which one was meant. I.e. we end with a partial pooling equilibrium.

An easier path to learning perhaps is to add more one word syllable nouns and verbs. Nowak and Krakauer (1999)  suggest though that after some point increasing the inventory of sounds leads to more errors in communication. 

At this point it might be easier to allow a second syllable to the noun slot. Again we run into some problems, we reused the same syllable for the noun and declension, so we can't be certain if a triplet is a long noun with a declension or a short noun with a declension and a verb. Again we might be able to figure this out from
the context but can we be sure there isn't a collision.

On way to dix this is to use a stress marker on the last sound of a verb or noun. This would be the penultimate sylable of the inflected form.


$$
<aa'-ba> <ka-da> <ba-ra>
$$

$$
<aa-ba'-ka> <da-ba'-ra> <ba'-ra>
$$

This allows us to have open categories of nouns and verbs. 

Another way to move forward is to have more templates that further increase semantics in a predictable ways. 

For example we might add adjective and adverbs. 

We can add up to 10 grammatical gender to a noun and assign each to some semantic category. This can allow us to use more verbs in a more
predictable way. 

For verbs we can enhance our 10 primative verbs with 10 coverbs to and have 100 derived verbs. Some might mark aspect and mood and become attached to the conjugation. 

So we have tabular systems


$$
<\text{gender}, \text{s-noun'}, \text{declension} > <\text{verb'} , \text{conjugation}, \text{co-verb}> < \text{gender}, \text{o-noun}, \text{declension} > \qquad \text{template with gender and coverbs}
$$ {#eq-nine-word-template}

$$
<\text{adj}, \text{s-noun'}, \text{declension} > <\text{verb'} , \text{conjugation}, \text{adverb} > < \text{adjective}, \text{o-noun}, \text{declension} > \qquad \text{template with adverbs and adjectives}
$$ {#eq-nine-word-template-2}


Ok so we have a system that is highly predictable, extendable and yet easy to learn. If the gender, co-verb, adjective and adverb are unstressed the agent should be able to make sense of the multiple templates with minimal collisions and we might even use a prefix to indicate the template being used.

An easier method might be to break the big templates into smaller ones. However this will be covered in the next section as it would complicate things in a way that might be unnecessary.

