
## Distributional Semantics

This central property does not arise in many signaling systems. 
However distibutional semantics is a property of natural languages. It is the good part of entanglement and disentanglement. It makes it easier to understand things by thier context^[a word is characterized by the company it keeps] & Distributed Representations

- Signaling systems should be alignable with 2000 discourse atoms c.f. [@arora2018linearalgebraicstructureword], or a subset if they come from a much simpler state structure.
- In fact a major point to research on emergent languages get to see if they manifest distributional semantics. I hypothesize that this will happen if the the state space is has a semantic basis - i.e. the state space is a vector space with dimensions that are semantically orthogonal. 
I now revised the above strong requirements to the following but perhaps they are even equivalent.
- prefix codes with compositionality.
- prefix codes learned with loss analogies.