
## Domain Specific Language (DSL) and General Purpose Language (GPL)

The languages that tend to emerge in one MDP would tend to be domain specific. However if agents experiences span multiple MDPs, their language may become more general purpose.

The DSL should encompass the states and action spaces of a particular MDP. 

The GPL  should have prelingistic objects that can be mapped to and from the states and action spaces of the MDPs. 

### Theories of Mind and Grounding

The agents need a DSL to think strategically about its own actions in terms of the actions of others agents. This is the domain of game theory. However the linguistic abstraction for this can be considered a theory of mind. The theory of mind is in some sense a mapping between the GPL and a specific DSL. It allows the agent to think in more general terms about the MDP it is in. 

The process of creating such a mapping in sometimes called grounding. It is  a process of identifying states, actions, rewards and higher order abstractions of a DSL for an MDP into a GPL.

For example even if the agent has learned some Options and Generalized Value Functions (GVFs) in previous MDPs, these may not be directly applicable to the current MDP. But if the agent has a theory of mind, it may be able to map the options and GVFs to the current MDP using its DSL. Its fairly clear that a option might transfer more readily while a GVF might require learning from scratch. However many concepts from Chess and Go and Black Jack might be directly applicable to other games or they may be need to be relearned in the new MDP. However a theory of mind should allow the agent to create hypotheses about such options and GVFs from the first game. It problem might be to identify what GVF best embodies ideas like the center or tempo and pawn structure in chess and or the concept of a bluff in poker and so on.


### Inductive Bias and Theories of Mind

To empower the agents to create a DSL with the GPL in a few shot fashion it would need to test many hypotheses and establish policies and or value functions for the current MDP but based on the DSL of the previous MDP.

These hypotheses might be derived using a bayesian approach to preexisting inductive biases. Simple models would seem to first first. More complex models would better at explain as more experience is gained. A hierarchical approach might allow it to assemble more complex models from pieces of existing models. This is one advantage of a bayesian approach.


Mapping the GSL and DSL

Pehaps also to operate in terms of temporal abstractions like options and generalized value functions that may be less obvious in the current MDP.


The mapping may be viewed as embedding the agents theory of mind and the process for this is grounding.

One way for an agents to quickly learn more general purpose language is to perhaps equip them with priors that embody and inductive bias towards the general purpose language. I.e. if they have access to priors that embody different theories of mind they can use baysian occums razor to pick the one most compatible with thier experience so far. 

This should let them find a GPL that is compatible with the current DSL for the MDP they are in. If they have access to temporal abstractions like options, they might repurpose then once they use the theory of mind to assign a symbolic mapping to the options's preconditions and post conditions in terms of the current language.

### Inductive Bias and Theories of Mind

The general purpose language encompasses the DSLs of specific mdps.


some ideas of what a general purpose language should have that may not be in a DSL:

A signaling system 
A Domain specific language

- arithmetic or at least a number systems 
- basic relations e.g. equality, and order relations.
- physics or at least spacio-temporal events
- semantic hierarchies aka thesauri
- first order logic + modal + contrafactual logic or at least propositional logic
- set theory
- basic notions from probability.

- its worth noting that set theory or logic might be all we need to get the rest, but we are not building mathematics but a language that needs to communicate.


