
# Desiderata from the Simulacra Project


## Vowel Harmony

<!--TODO: 
- [ ] move to Simulacra Project 
- [ ] reference in communication section
-->

If agents backprogogate with topographic similarity in mind and the 
basic signals (phonemes) are endowed with a similarity they may end up with systems with vowel harmony and alternation of consonants to capture sets normal subgroups with greater similarity.

if these regular configuration also lead to better channel coding the benefits should persist. 


## VO and OV via symmetry breaking etc


<!--TODO: 

- [ ] move to the Simulacra Project.
- [ ] reference in pertinent sections.

-->


If we use Huffman coding like process to organize the order of the morphological and syntactical elements (effectively making the fixing the on average most surprising partial signals before the next on average most surprising ones) we should have emergent languages that are rather similar and fairly easy to learn 

Like Turkish and Japanese. However there is at the start the question of how to apply aggregations. If action is first we get V O languages if it is second we get OV languages. I think that V carries more entropy in Predation and Resource gathering games so that VO should be more prevalent. However once this decision is made most practical algorithms will not be able to reverse it.
