---
date: 2025-04-03
title: "Langtalks Resources # 43"
category: "Langtalks"
description: "Exploring GenAI-powered tools"
tags: [langtalks, linkage]
categories: [generative AI, podcasts]
---

- #43 - Building with GenAI-powered tools | [Idan Benaun](https://www.linkedin.com/in/idan-benaun-824a0759)
    - Podcast with lots of tools, lots of crap to dig into.
    - Forms:
        - [typeform](typeform.com)
        - [KaliFroms](https://kaliforms.com/) - "90% of type form for 50% less"
    - No code: 
        - [zapier](zapier.com) - no code API integrator
        - [wix](https://www.wix.com/builder/no-code) -  site builder
        - [framer](https://www.framer.com/) - Just publish it with Framer
        - [webcode](https://webcode.tools/) - The best code generators for developers 
        - [make](https://www.make.com) Outgrowing Zapier? Advance with Make
        - [lovable](https://lovable.dev) Idea to app in seconds.
        - [bolt](https://bolt.new/) What do you want to build?
        - [cursor](https://www.cursor.com/) - The AI Code Editor
        - [windsurf](https://codeium.com/windsurf) Built to keep you in flow state
        - [v0](https://v0.dev/) ?? components for what
    - repos
        - [gpt engineer](https://github.com/AntonOsika/gpt-engineer) now wrapped in v0
    - [.cursorrules](https://github.com/PatrickJS/awesome-cursorrules)
        - O1 ?? 
        - Rules ??
    - tips (indie hacking)
        - small bits
        - advertising your work 
            - tictoc/reddit/twitter
    - Persona/avatar for social platforms
        - [fal](https://fal.ai/) - Generative media platform for developers.
        - [heygen](https://www.heygen.com/) - AI Video Generator
        - [revid](https://www.revid.ai/) create videos with your avatar
    - Seo
        - [seo](http://seobot.ai)
    - Customer support
        - [chatbase](http://chatbase.co) - AI Agents for magical customer experiences
    - My Take away
        - while AI disrupts everything in sight this is the age of opportunities for enterpanurship.
        - one quick way to make a business is to find a service and make a cheaper variant with just the top features. 
        - Drilling deeper
            - Less features easier to maintain with AI
            - Cheaper to run
            - Easier to automate via an API